### ISSUE TITLE
Game crashes when sleeping

### ISSUE THREAD

**Issue by zottelmann** [Pyrdacor/Ambermoon.net#104]
Hi!

Didnt find it mentioned here. When trying to buy a bed the game crashes with this error:
"object reference not set to an instance of an object"
Version: 0.94 RC1
Windows 10 64bit
Everytime so far right at the beginning in "Spannenberg". Doesnt matter if at the healer oder the tavern.

Still love the Game so far. Keep up the good work!

**Comment by Pyrdacor** [comment]
Hi this was reported in #96. I already fixed it. You can try the TestRelease at https://github.com/Pyrdacor/Ambermoon.net/releases/tag/TestRelease. You have to download it manually as it isn't fully released yet but this version will receive bugfixes and reflects the current state.

**Comment by zottelmann** [comment]
Ah thank you. I havent checked the closed issues. My bad.
