### ISSUE TITLE
Level Up UI-window gibberish

### ISSUE THREAD

**Issue by TalonRoo** [Pyrdacor/Ambermoon.net#105]
I think this happens when multiple characters level at the same time. Also, the window gets stuck there until I close/open the game again.

![image](https://user-images.githubusercontent.com/87539646/125978642-7acff1c3-fed7-4cf4-ab9f-5995b37077db.png)

**Comment by Pyrdacor** [comment]
Thanks for reporting. Will fix it soon.

**Comment by Pyrdacor** [comment]
Should be fixed. Just download the test release again. ;)
