### ISSUE TITLE
Objects disappear from containers after pressing the right mouse button

### ISSUE THREAD

**Issue by Uukrull** [Pyrdacor/Ambermoon.net#107]
Pick an object:

![1](https://user-images.githubusercontent.com/5891591/125999529-bd1677c1-0e8e-47e8-bc48-4fd03cc01fd7.png)

swap it with another one:

![2](https://user-images.githubusercontent.com/5891591/125999612-5f1e162f-f8bb-4a54-b587-c0749b64a01e.png)

and press the right button -> the object disappears and it is nowhere to be found.

![3](https://user-images.githubusercontent.com/5891591/125999725-1e2bd63c-098a-4b53-bca5-b5ea9b476621.png)

I tested it with closets and chests and always happens. I also tried it on WinUAE and works as intended (the objects are swapped)

Check the attached savegame:

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6833000/Saves.zip)

**Comment by Pyrdacor** [comment]
Thanks for reporting. Will investigate and fix it soon.

**Comment by Pyrdacor** [comment]
Should be fixed. Just download the test release again. ;)
