### ISSUE TITLE
The gold left isn't updated after the Sage identifies an item

### ISSUE THREAD

**Issue by Uukrull** [Pyrdacor/Ambermoon.net#108]
Identify an item:

![6](https://user-images.githubusercontent.com/5891591/126020924-5e1cfb6c-f9f9-49fc-b714-3f4b323f38d3.png)

The gold left should be 47 (I can't identify another item because there aren't enough gold pieces)

![7](https://user-images.githubusercontent.com/5891591/126020926-16972ab6-804b-4f04-a001-3f11aec8d35b.png)

If I enter and exit the inventory screen, the correct amount is showed:

![8](https://user-images.githubusercontent.com/5891591/126020928-b6f9bace-231a-4e05-ab96-592fce38aeaf.png)

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6833940/Saves.zip)

**Comment by Pyrdacor** [comment]
Ok so only the display isn't updated. Should be easy to fix. Thanks.

**Comment by Uukrull** [comment]
Indeed.

https://github.com/Pyrdacor/Ambermoon.net/blob/90b5cb8ca3f293439ae2a1a309594dba7a97d8cc/Ambermoon.Core/Game.cs#L9239

Adding `updatePartyGold?.Invoke();` fixes the issue.
The enchanter and the blacksmith also should update it.

**Comment by Pyrdacor** [comment]
Should be fixed. Just download the test release again. ;)
