### ISSUE TITLE
Feature: Map names in map window

### ISSUE THREAD

**Issue by Metibor** [Pyrdacor/Ambermoon.net#11]
I made a commit in my repository that adds the original map names to the main window:
https://github.com/Metibor/Ambermoon.net/commit/f51b32877607c4c542d94967ff1bd4ee767df461

I think it is not ready for a PR, yet, but if its okay, I will create one

Positive:
* Works for both languages
* Uses the world names from the executable data

Negative:
* Uses just White as text color => I don't know which one to use, but the layout also doesn't use the correct colors (palettes should be different the various layouts, see this [Let's Play](https://youtu.be/C8y0tCh_vD8?t=935) for example)
* Adds a new dependency from the Core project to Data.Legacy
* I don't know if I did the handling of the mapName object is correct, but I had to Delete it or it would render twice.

I am open for criticism. 😃

![grafik](https://user-images.githubusercontent.com/12674912/91666453-29f88600-eafd-11ea-933c-446f01ac83cd.png)

![grafik](https://user-images.githubusercontent.com/12674912/91666475-498fae80-eafd-11ea-92b8-9055c944f23b.png)

**Comment by Pyrdacor** [comment]
@Metibor I added some DataNameProvider that you can use/extend for world names.

See here: https://github.com/Pyrdacor/Ambermoon.net/blob/master/Ambermoon.Data.Common/IDataNameProvider.cs and https://github.com/Pyrdacor/Ambermoon.net/blob/master/Ambermoon.Data.Legacy/DataNameProvider.cs

**Comment by Metibor** [comment]
Oh cool, I had just figured it out myself!
But it was no problem to put my method into the new class & interface. :-)

I made a PR: #15

**Comment by Metibor** [comment]
This one is implemented
