### ISSUE TITLE
Horse disappears when saving

### ISSUE THREAD

**Issue by Uukrull** [Pyrdacor/Ambermoon.net#111]
Mount the horse and save:

![9](https://user-images.githubusercontent.com/5891591/126500710-96c6f00d-c36b-40d7-bc2f-7356ecbf1118.png)

Load the savegame and the horse disappears:

![10](https://user-images.githubusercontent.com/5891591/126500706-56f68324-cbcc-4f65-8e7c-5fd03986e7cb.png)

On WinUAE, it works as intended.

[saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6856281/saves.zip)

**Comment by Pyrdacor** [comment]
Thanks for reporting. Should be fixed now in most recent test release.

Unfortunately the horse will be gone forever. To make it easier the "give cheat" can now add money and food so you can give you the horse money and buy a new one.

Just type "give gold xxx" in the console where xxx is the amount. ;)

**Comment by Uukrull** [comment]
Tested and working. Many thanks!

I never cheat but I want my gold back, so thanks for the tip :)
