### ISSUE TITLE
Transparency issue 

### ISSUE THREAD

**Issue by Silverfox26** [Pyrdacor/Ambermoon.net#113]
There seems to be an issue with a transparency flag. Everything that is pure black in the illustration seems to be transparent, and the background grid is showing through. Especially visible on the back of the head in the bottom left. Whereas in the Amiga Version it is solid black. I've only checked this illustration so far. Don't know if it also shows up on other 'cutscene' illustrations.

![Transparency issue](https://user-images.githubusercontent.com/29178133/126543770-30fbb5b8-2965-4959-8a8b-4f96ba887814.png)
Amiga Version:
![Amiga Version](https://user-images.githubusercontent.com/29178133/126543782-2dcee53e-f212-42df-bf30-dfcb0706889a.png)

**Comment by Pyrdacor** [comment]
Good catch. I will check some more of them and fix it. ;)

**Comment by Pyrdacor** [comment]
Should be fixed now in most recent TestRelease.
