### ISSUE TITLE
The given key '0' was not present in the dictionary

### ISSUE THREAD

**Issue by Uukrull** [Pyrdacor/Ambermoon.net#116]
I get this error:

> The given key '0' was not present in the dictionary.
>    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
>    at Ambermoon.Data.Legacy.ItemManager.GetItem(UInt32 index)
>    at Ambermoon.Battle.RunBattleAction(BattleAction battleAction, UInt32 battleTicks)
>    at Ambermoon.Battle.Update(UInt32 battleTicks)
>    at Ambermoon.Game.UpdateBattle()
>    at Ambermoon.Game.Update(Double deltaTime)
>    at Ambermoon.GameWindow.Window_Update(Double delta)
>    at Silk.NET.Windowing.Internals.ViewImplementationBase.DoUpdate()
>    at Silk.NET.Windowing.WindowExtensions.<>c__DisplayClass2_0.<Run>b__0()
>    at Silk.NET.Windowing.Internals.ViewImplementationBase.Run(Action onFrame)
>    at Silk.NET.Windowing.WindowExtensions.Run(IView view)
>    at Ambermoon.GameWindow.Run(Configuration configuration)
>    at Ambermoon.Program.Main()

if I use the Firebrand against the Master Thief:

![25](https://user-images.githubusercontent.com/5891591/126672056-f1a0193e-a899-4cd7-9882-46bc898a5a67.png)

![26](https://user-images.githubusercontent.com/5891591/126672061-6ba8fa25-a3cc-457b-b9d7-278c9b5824c7.png)

![27](https://user-images.githubusercontent.com/5891591/126672062-20d1cc43-ecd9-4a00-bba5-306e4332d539.png)

Working on WinUAE:

![003](https://user-images.githubusercontent.com/5891591/126672866-4f2c9587-cf09-41c7-b74e-4093e4a51f60.png)

[saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6863764/saves.zip)

**Comment by Uukrull** [comment]
And another one:

> The given key '0' was not present in the dictionary.
>    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
>    at Ambermoon.UI.ItemGrid.DropItem(Int32 slot, DraggedItem item)
>    at Ambermoon.UI.ItemGrid.Click(Position position, DraggedItem draggedItem, ItemAction& itemAction, MouseButtons mouseButtons, CursorType& cursorType, Action`1 dragHandler)
>    at Ambermoon.UI.Layout.Click(Position position, MouseButtons buttons, CursorType& cursorType, UInt32 currentTicks, Boolean pickingNewLeader, Boolean pickingTargetPlayer, Boolean pickingTargetInventory)
>    at Ambermoon.Game.OnMouseDown(Position position, MouseButtons buttons)
>    at Ambermoon.GameWindow.Mouse_MouseDown(IMouse mouse, MouseButton button)
>    at Silk.NET.Input.Internals.MouseImplementationBase.HandleMouseDown(IMouse mouse, MouseButton button)
>    at Silk.NET.GLFW.Glfw.PollEvents()
>    at Silk.NET.Windowing.WindowExtensions.<>c__DisplayClass2_0.<Run>b__0()
>    at Silk.NET.Windowing.Internals.ViewImplementationBase.Run(Action onFrame)
>    at Silk.NET.Windowing.WindowExtensions.Run(IView view)
>    at Ambermoon.GameWindow.Run(Configuration configuration)
>    at Ambermoon.Program.Main()
> 

My Firebrand (two handed sword) broke, the X mark won't go away and if I try to equip a shield I get the error.

![28](https://user-images.githubusercontent.com/5891591/126747728-c9a4b99a-f31f-40cb-b818-a69dc95bdf09.png)


[saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6867060/saves.zip)

**Comment by Pyrdacor** [comment]
I will check those on Monday asap.

**Comment by Uukrull** [comment]
Compiled, tested and working. Many thanks!

**Comment by Uukrull** [comment]
I spoke too soon...
Now, if I try to put any item in a chest I get this error:

> The given key '0' was not present in the dictionary.
>    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
>    at Ambermoon.Game.InventoryItemRemoved(UInt32 itemIndex, Int32 amount, PartyMember partyMember)
>    at Ambermoon.UI.Layout.<>c__DisplayClass148_0.<StoreItem>g__StoreAmount|3(UInt32 amount)
>    at Ambermoon.UI.Layout.StoreItem(ItemGrid itemGrid, Int32 slot, ItemSlot itemSlot)
>    at Ambermoon.UI.Layout.<>c__DisplayClass153_0.<PickInventoryItemForAction>g__ItemChosen|0(ItemGrid itemGrid, Int32 slot, ItemSlot itemSlot)
>    at Ambermoon.UI.ItemGrid.Click(Position position, DraggedItem draggedItem, ItemAction& itemAction, MouseButtons mouseButtons, CursorType& cursorType, Action`1 dragHandler)
>    at Ambermoon.UI.Layout.Click(Position position, MouseButtons buttons, CursorType& cursorType, UInt32 currentTicks, Boolean pickingNewLeader, Boolean pickingTargetPlayer, Boolean pickingTargetInventory)
>    at Ambermoon.Game.OnMouseDown(Position position, MouseButtons buttons)
>    at Ambermoon.GameWindow.Mouse_MouseDown(IMouse mouse, MouseButton button)
>    at Silk.NET.Input.Internals.MouseImplementationBase.HandleMouseDown(IMouse mouse, MouseButton button)
>    at Silk.NET.Input.Glfw.GlfwMouse.<Subscribe>b__36_2(WindowHandle* _, MouseButton btn, InputAction action, KeyModifiers mods)
>    at Silk.NET.Input.Glfw.GlfwEvents.<.ctor>b__0_2(WindowHandle* a, MouseButton b, InputAction c, KeyModifiers d)
>    at Silk.NET.GLFW.Glfw.PollEvents()
>    at Silk.NET.Windowing.WindowExtensions.<>c__DisplayClass2_0.<Run>b__0()
>    at Silk.NET.Windowing.Internals.ViewImplementationBase.Run(Action onFrame)
>    at Silk.NET.Windowing.WindowExtensions.Run(IView view)
>    at Ambermoon.GameWindow.Run(Configuration configuration)
>    at Ambermoon.Program.Main()


![39](https://user-images.githubusercontent.com/5891591/126975254-6927d2f5-c347-4285-8889-0bc70add1ad0.png)


[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6877500/Saves.zip)

**Comment by Pyrdacor** [comment]
Should work now

**Comment by Uukrull** [comment]
Yes. Many thanks!
