### ISSUE TITLE
Containers are limited to 50000 pieces of gold

### ISSUE THREAD

**Issue by Uukrull** [Pyrdacor/Ambermoon.net#120]
![36](https://user-images.githubusercontent.com/5891591/126904761-a9058ad5-5e30-4e91-af0d-c491e0e2890d.png)

![37](https://user-images.githubusercontent.com/5891591/126904762-e12c6c7f-2bd5-406e-be65-d8be041ec404.png)

![38](https://user-images.githubusercontent.com/5891591/126904763-3fb48eed-b5c6-48f1-b44f-065711d5ee7c.png)

On WinUAE:

![011](https://user-images.githubusercontent.com/5891591/126904777-3c07f3a2-0039-4365-bb49-749b7bccfe39.png)

![012](https://user-images.githubusercontent.com/5891591/126904779-9686cf27-9f4e-4be0-988b-753c893e2f05.png)

![013](https://user-images.githubusercontent.com/5891591/126904780-6ef6aead-d2b6-4b61-9f7c-618c20014541.png)

I guess is related to this:
https://github.com/Pyrdacor/Ambermoon.net/blob/master/Ambermoon.Core/Game.cs#L13151

Is there any side effects after increasing that value?

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6874146/Saves.zip)

**Comment by Pyrdacor** [comment]
You should limit it to 0xffff (65535) as the value is stored as a 2 byte value which can only hold that range.

If you want you could create a pull request with changing that value to 0xffff. Same for food I guess.

**Comment by Uukrull** [comment]
Compiled, tested and working. Many thanks!
