### ISSUE TITLE
(Game Crash) Ref Error

### ISSUE THREAD

**Issue by TalonDarkclaw** [Pyrdacor/Ambermoon.net#122]
Game crashes on completion of a combat.

REPRODUCTION:

Load save game.
Enter any battle (for ease this could be the bandits in town at night.)
Win the battle.
Game crashes with the Ref error message.

SAVE ATTACHED.
[Save.01.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6881711/Save.01.zip)

**Comment by Pyrdacor** [comment]
Should be fixed now. Please download the TestRelease again.

**Comment by TalonDarkclaw** [comment]
Thank you very much, I will check it immediately.
