### ISSUE TITLE
Spell points bar isn't updated

### ISSUE THREAD

**Issue by Uukrull** [Pyrdacor/Ambermoon.net#123]
It's always full:

![image](https://user-images.githubusercontent.com/5891591/127201368-857cdfe3-c95d-41bf-b1b0-2e358554b948.png)

![image](https://user-images.githubusercontent.com/5891591/127201496-033f8fc4-d419-4494-a015-95db1047a82b.png)

WinUAE:

![image](https://user-images.githubusercontent.com/5891591/127201708-97c935c5-f964-4238-8cd2-bbf1cae65cf9.png)

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6887603/Saves.zip)

**Comment by Pyrdacor** [comment]
Hm I can't reproduce it on my end. What did you do exactly?

**Comment by Uukrull** [comment]
Just load the savegame I attached. The problem is the 1 SP. It's fixed on my end with this patch:

```
diff --git "a/Ambermoon.Core/UI/Layout.cs" "b/Ambermoon.Core/UI/Layout.cs"
index c35c1b0..a8f7e87 100644
--- "a/Ambermoon.Core/UI/Layout.cs"
+++ "b/Ambermoon.Core/UI/Layout.cs"
@@ -128,7 +128,7 @@ namespace Ambermoon.UI
         {
             int pixels = Util.Round(size * percentage);
 
-            if (forceNotEmpty && pixels == 0)
+            if (forceNotEmpty && pixels == 0 && percentage > 0)
                 pixels = 1;
 
             if (pixels == 0)
@@ -3306,10 +3306,10 @@ namespace Ambermoon.UI
             float spPercentage = partyMember == null || !partyMember.Alive || !partyMember.Class.IsMagic() ? 0.0f
                 : Math.Min(1.0f, (float)partyMember.SpellPoints.CurrentValue / partyMember.SpellPoints.TotalMaxValue);
 
-            characterBars[slot * 4 + 0]?.Fill(lpPercentage);
-            characterBars[slot * 4 + 1]?.Fill(lpPercentage);
-            characterBars[slot * 4 + 2]?.Fill(spPercentage);
-            characterBars[slot * 4 + 3]?.Fill(spPercentage);
+            characterBars[slot * 4 + 0]?.Fill(lpPercentage, true);
+            characterBars[slot * 4 + 1]?.Fill(lpPercentage, true);
+            characterBars[slot * 4 + 2]?.Fill(spPercentage, true);
+            characterBars[slot * 4 + 3]?.Fill(spPercentage, true);
         }
 
         public void AddActiveSpell(ActiveSpellType activeSpellType, ActiveSpell activeSpell, bool battle) 
```

**Comment by Pyrdacor** [comment]
The problem was a bit different. The bar at least would have been hidden but due to other code it would be shown again after that. That's why it appear filled (the size is not adjusted, it is only hidden in the first place). I fixed this so that empty bars are hidden now. And of course for LP/SP > 0 now there will be one tiny pixel row.

**Comment by Uukrull** [comment]
Compiled, tested and working. Many thanks!
