### ISSUE TITLE
Can't store items in chest

### ISSUE THREAD

**Issue by Uukrull** [Pyrdacor/Ambermoon.net#124]
The chest has available slots but the icon is disabled for all members except Selena:

![43](https://user-images.githubusercontent.com/5891591/127641368-9126a0b0-9d02-4523-85fa-8409543c2e0b.png)

![44](https://user-images.githubusercontent.com/5891591/127641391-5e4ef4c8-24a9-46f4-9d05-bcbdf14eedac.png)

WinUAE:

![018](https://user-images.githubusercontent.com/5891591/127641650-68b72fd8-8b13-4c3a-ad5e-775f8fa0bfb0.png)

This problem also happened days ago but I couldn't reproduce it because if I quit the remake and load the savegame all is good (when the bug appears that won't work: reloading the save doesn't fix it). So it could be a tricky one to fix for such a tiny bug.

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6907014/Saves.zip)

**Comment by Pyrdacor** [comment]
Is it possible that is not available for players who have no available slots in their inventory? Maybe the code checks the wrong item slots for free slots. Instead checking the chest it may check the inventory. Can you try to move an item from another inventory to Selena's inventory. Is the button available in that other inventory then?

**Comment by Uukrull** [comment]
>Can you try to move an item from another inventory to Selena's inventory. Is the button available in that other inventory then?

The problem is I'll have to wait until the next time the bug appears because, as soon as I restart the remake, all is fine.

**Comment by Pyrdacor** [comment]
Maybe fill the inventory of Selena completly. Perhaps then it will happen. What did you do before it happened? Did you move items from the chest to some inventory?

**Comment by Pyrdacor** [comment]
I looked at the code. The button can't be disabled at all while in inventory. So I guess he confuses the current window somehow.

**Comment by Uukrull** [comment]
> Maybe fill the inventory of Selena completly. Perhaps then it will happen. What did you do before it happened? Did you move items from the chest to some inventory?

I did nothing special. It has happened two times and seems completely random to me.

**Comment by Pyrdacor** [comment]
After checking the code I think some code still has some event handler active which will disable the button. Most likely is some place (merchant, healer, inn, etc) you visited beforehand or the camp window. Could that be the case?

**Comment by Uukrull** [comment]
> After checking the code I think some code still has some event handler active which will disable the button. Most likely is some place (merchant, healer, inn, etc) you visited beforehand or the camp window. Could that be the case?

Probably the merchant, because after selling the items I always go to my main chest at the healer to leave the gold and some items.

**Comment by Uukrull** [comment]
Maybe related, but I had a moment ago a similar bug with the merchant: the sell icon was disabled for some characters.

**Comment by Pyrdacor** [comment]
It's hard to track. If you are in the situation again could you attach a debugger to it and set a breakpoint to `ActivePlayerChanged?.Invoke();`? This of course needs the debug build. I don't know how you build the code and what tools you use.

If you can set the breakpoint, try switching the player and look what handlers are called then. This would give as a clue what's happening.

I will try to do the same if it happens on my end. But I don't playtest that much and if so only specific aspects and not game progression.

**Comment by Uukrull** [comment]
OK. I'll try to use Visual Studio.

**Comment by Pa9an** [comment]
Maybe ading to this...
I have the issue with seemingly random disabled buttons as well...in any case the is no obvious reason to have the button disabled (like when a char goes mad during a battle) and there are workarounds also, so I presume this button behaviour is actually buggy.
- Selena being the only Thief in the party, but when opening a chest, all buttons are disabled except "use item" > when going to the char screen and then back to the chest it is enabled again.
- when in a person's inventory, the button for character screen is disabled > when I select another person it's enabled again and with right-click I then can get into the person's char screen that was blocked before
- same issue as Uukrull describes above
- maybe other occasions I might have forgotten now, will add later

If you feel I should post them as a separate bug, let me know.
I think, though, the chest storing this is just one of multiple cases that the bbutton behaviour is wrong.

**Comment by Uukrull** [comment]
With a debug build and the process attached to Visual Studio I got these two cases:

[1] The program thinks is a trainer instead of a merchant:

![57](https://user-images.githubusercontent.com/5891591/128609662-615d6591-60be-423e-8862-43bc38761884.png)

![58](https://user-images.githubusercontent.com/5891591/128609665-ec7a682c-263f-49ec-b6c2-203a897de973.png)

[2] The program thinks the party is camping:

![59](https://user-images.githubusercontent.com/5891591/128609667-266c511b-44bb-4dbe-ba52-7743abaa1aaf.png)
![60](https://user-images.githubusercontent.com/5891591/128609669-1cab9ac1-5f64-4ea9-84d5-42d2a36a57e6.png)

I also got the chest problems a couple of times more but I couldn't attach the process at that moment.

**Comment by Pa9an** [comment]
Thanks Uukrull, that's good insight.
And it would explain the other occasions also where the program allocates the wrong "mask" to the buttons that make the wrong buttons disabled.

**Comment by Pyrdacor** [comment]
Thanks for reporting and investigating. I will try to fix this on Monday. I guess those events are not correctly detached after camp or trainer is closed so they are called in other windows later.

**Comment by Pyrdacor** [comment]
Ok the problem was the following: When opening a trainer or any other place, an event was attached to the action of switching the active player. On exit this event was detached. But this was only the case for the Exit button. When you switch to the inventory instead the event is not detached but the active window is changed. When you close the inventory the window is switched again to the place (trainer etc) and the switch player event is attached again. When you then close the window, only one of the two events is detached and the other one stays attached.

I fix this now. Will be part of the next release. ;)

**Comment by Pyrdacor** [comment]
It is now part of the most recent TestRelease.
