### ISSUE TITLE
Death animation and key are stuck after all characters are dead while swimming

### ISSUE THREAD

**Issue by Uukrull** [Pyrdacor/Ambermoon.net#125]
Load the attached save and go swimming (keep the down key pressed, for example) until the only survivor is Pepin.

![45](https://user-images.githubusercontent.com/5891591/127653899-6c50777a-68d5-40c6-b6e7-380f4047728e.png)

The "select a new leader" dialog appears, select Pepin and he'll keep going south plus the Nelvin portrait is in the middle of his death.

WinUAE:

![019](https://user-images.githubusercontent.com/5891591/127654483-a6ce9ec3-7eb9-4af6-b87c-63722088b289.png)

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6907581/Saves.zip)

**Comment by Uukrull** [comment]
After https://github.com/Pyrdacor/Ambermoon.net/commit/d723520489a3550ec7b72852cd5f3a38c166b472 swimming crashes the program:

> Collection was modified; enumeration operation may not execute.
>    at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
>    at Ambermoon.Render.RenderMap2D.RepositionTransports(Map lastMap)
>    at Ambermoon.Render.RenderMap2D.SetMap(Map map, UInt32 initialScrollX, UInt32 initialScrollY)
>    at Ambermoon.Render.RenderMap2D.Scroll(Int32 x, Int32 y)
>    at Ambermoon.Render.Player2D.Move(Int32 x, Int32 y, UInt32 ticks, TravelType travelType, Boolean& eventTriggered, Boolean displayOuchIfBlocked, Nullable`1 prevDirection, Boolean updateDirectionIfNotMoving)
>    at Ambermoon.Game.<Move2D>g__Move|358_0(<>c__DisplayClass358_0& )
>    at Ambermoon.Game.Move2D(Int32 x, Int32 y)
>    at Ambermoon.Game.Move()
>    at Ambermoon.Game.Update(Double deltaTime)
>    at Ambermoon.GameWindow.Window_Update(Double delta)
>    at Silk.NET.Windowing.Internals.ViewImplementationBase.DoUpdate()
>    at Silk.NET.Windowing.WindowExtensions.<>c__DisplayClass2_0.<Run>b__0()
>    at Silk.NET.Windowing.Internals.ViewImplementationBase.Run(Action onFrame)
>    at Silk.NET.Windowing.WindowExtensions.Run(IView view)
>    at Ambermoon.GameWindow.Run(Configuration configuration)
>    at Ambermoon.Program.Main()

**Comment by Pyrdacor** [comment]
This was quiet a hard one. But is now fixed in code.

**Comment by Uukrull** [comment]
After https://github.com/Pyrdacor/Ambermoon.net/commit/f736177ed279f79df8da7736ce101d4b9bae1e36, flying the eagle or the broomstick over water does damage:

![81](https://user-images.githubusercontent.com/5891591/128731203-0bc41012-8845-4005-98a1-4f2967fe085c.png)


[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6955549/Saves.zip)
