### ISSUE TITLE
Sequence contains no elements

### ISSUE THREAD

**Issue by Uukrull** [Pyrdacor/Ambermoon.net#126]
In the battle against Luminor:

![47](https://user-images.githubusercontent.com/5891591/127746983-f537791b-fb40-442a-9c0a-b3f6bcdd8c7a.png)

if the back row is killed:

![48](https://user-images.githubusercontent.com/5891591/127747001-040ece27-e62a-40e1-a3d3-40046ae43fef.png)

sometimes, when I press OK this happens:

> Sequence contains no elements
>    at System.Linq.ThrowHelper.ThrowNoElementsException()
>    at System.Linq.Enumerable.Average[TSource](IEnumerable`1 source, Func`2 selector)
>    at Ambermoon.Battle.PickActionParameter(BattleActionType battleAction, Monster monster, Boolean wantsToFlee, List`1 forbiddenMonsterMoveSpots)
>    at Ambermoon.Battle.AddMonsterActions(Monster monster, Boolean& monstersAdvance, List`1 forbiddenMonsterMoveSpots)
>    at Ambermoon.Battle.<>c__DisplayClass105_0.<StartRound>g__Start|3()
>    at Ambermoon.Battle.<>c__DisplayClass105_0.<StartRound>b__0()
>    at Ambermoon.Game.<>c__DisplayClass418_0.<DamageAllPartyMembers>b__5()
>    at Ambermoon.Game.<>c__DisplayClass333_0.<ForeachPartyMember>g__Run|0(Int32 index)
>    at Ambermoon.Game.<>c__DisplayClass333_0.<ForeachPartyMember>g__Run|0(Int32 index)
>    at Ambermoon.Game.<>c__DisplayClass333_0.<ForeachPartyMember>g__Run|0(Int32 index)
>    at Ambermoon.Game.<>c__DisplayClass333_0.<ForeachPartyMember>g__Run|0(Int32 index)
>    at Ambermoon.Game.<>c__DisplayClass333_0.<ForeachPartyMember>g__Run|0(Int32 index)
>    at Ambermoon.Game.<>c__DisplayClass333_0.<ForeachPartyMember>g__Run|0(Int32 index)
>    at Ambermoon.Game.<>c__DisplayClass333_0.<ForeachPartyMember>g__Run|0(Int32 index)
>    at Ambermoon.Game.ForeachPartyMember(Action`2 action, Func`2 condition, Action followUpAction)
>    at Ambermoon.Game.<>c__DisplayClass418_0.<DamageAllPartyMembers>b__1()
>    at Ambermoon.Game.<>c__DisplayClass333_0.<ForeachPartyMember>g__Run|0(Int32 index)
>    at Ambermoon.Game.<>c__DisplayClass333_0.<ForeachPartyMember>g__Run|0(Int32 index)
>    at Ambermoon.Game.<>c__DisplayClass333_0.<ForeachPartyMember>g__Run|0(Int32 index)
>    at Ambermoon.Game.<>c__DisplayClass333_0.<ForeachPartyMember>g__Run|0(Int32 index)
>    at Ambermoon.Game.<>c__DisplayClass333_0.<ForeachPartyMember>g__Run|0(Int32 index)
>    at Ambermoon.Game.<>c__DisplayClass333_1.<ForeachPartyMember>b__1()
>    at Ambermoon.Game.<>c__DisplayClass418_0.<DamageAllPartyMembers>g__Damage|2(PartyMember partyMember, Action finished)
>    at Ambermoon.Game.<>c__DisplayClass333_0.<ForeachPartyMember>g__Run|0(Int32 index)
>    at Ambermoon.Game.<>c__DisplayClass333_0.<ForeachPartyMember>g__Run|0(Int32 index)
>    at Ambermoon.Game.ForeachPartyMember(Action`2 action, Func`2 condition, Action followUpAction)
>    at Ambermoon.Game.DamageAllPartyMembers(Func`2 damageProvider, Func`2 affectChecker, Action`2 notAffectedHandler, Action followAction, Ailment inflictAilment, Boolean showDamageSplash)
>    at Ambermoon.Game.ProcessPoisonDamage(UInt32 times, Action followAction)
>    at Ambermoon.Battle.StartRound(PlayerBattleAction[] playerBattleActions, UInt32 battleTicks)
>    at Ambermoon.Game.StartBattleRound(Boolean withoutPlayerActions)
>    at Ambermoon.Game.<SetupBattleButtons>b__466_1()
>    at Ambermoon.UI.Button.ExecuteActions(UInt32 currentTicks, Boolean rightMouse)
>    at Ambermoon.UI.Button.LeftMouseUp(Position position, Nullable`1& cursorType, UInt32 currentTicks)
>    at Ambermoon.UI.ButtonGrid.MouseUp(Position position, MouseButtons mouseButtons, Nullable`1& newCursorType, UInt32 currentTicks)
>    at Ambermoon.UI.Layout.LeftMouseUp(Position position, Nullable`1& newCursorType, UInt32 currentTicks)
>    at Ambermoon.Game.OnMouseUp(Position cursorPosition, MouseButtons buttons)
>    at Ambermoon.GameWindow.Mouse_MouseUp(IMouse mouse, MouseButton button)
>    at Silk.NET.GLFW.Glfw.PollEvents()
>    at Silk.NET.Windowing.WindowExtensions.<>c__DisplayClass2_0.<Run>b__0()
>    at Silk.NET.Windowing.Internals.ViewImplementationBase.Run(Action onFrame)
>    at Silk.NET.Windowing.WindowExtensions.Run(IView view)
>    at Ambermoon.GameWindow.Run(Configuration configuration)
>    at Ambermoon.Program.Main()

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6911518/Saves.zip)

**Comment by Pyrdacor** [comment]
I will only be able to work on this in a week from now but then I'll fix your issues.

**Comment by Uukrull** [comment]
No problem. Enjoy your well deserved free time :)
