### ISSUE TITLE
Captain Torle's ship is nowhere to be found

### ISSUE THREAD

**Issue by Uukrull** [Pyrdacor/Ambermoon.net#127]
Load the attached save and talk to Captain Torle:

![49](https://user-images.githubusercontent.com/5891591/127763159-eba11487-32f0-4886-92cd-d361767ba118.png)

The ship should be at the quay but it isn't:

![50](https://user-images.githubusercontent.com/5891591/127763160-e43187eb-c5c7-439a-a99d-c9b47043c2a2.png)

WinUAE:

![020](https://user-images.githubusercontent.com/5891591/127763216-2fa975ba-390a-44ce-a644-ab875d9bdb1e.png)

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6912301/Saves.zip)

**Comment by Pyrdacor** [comment]
Can you try to move the raft away beforehand? I guess he can't place the ship on top of it.

**Comment by Uukrull** [comment]
If I move the raft:

![51](https://user-images.githubusercontent.com/5891591/127763993-cfe6beda-8ab0-4c4a-9a67-c6d66a259de8.png)

And If I buy a ship (before talking to Torle) there is no problem:

![53](https://user-images.githubusercontent.com/5891591/127764032-6d17d72d-2a53-4a04-bfa0-3f4cd36e947d.png)

**Comment by Uukrull** [comment]
OK. The ship is there so it seems a sprite priority problem to be like the Amiga version:

![54](https://user-images.githubusercontent.com/5891591/127764176-b660afc5-a23b-46db-9319-6fbd5b164db0.png)

**Comment by Pyrdacor** [comment]
So if you buy the ship instead of getting it from torle it is one tile lower? Is this also true in the Amiga version?

I will adjust the render order when I get time. I think last placed should be drawn last.

**Comment by Uukrull** [comment]
> So if you buy the ship instead of getting it from torle it is one tile lower? Is this also true in the Amiga version?

With the remake, yes it's one tile lower. With the Amiga version there must be a bug because the ship is truly nowhere (I checked with the raft docked and with the raft moved:

![023](https://user-images.githubusercontent.com/5891591/127766088-d80b2958-464d-4c56-af63-9a2ddb9d3bae.png)

Also, in the Amiga version with Torle's ship, the sprite priority doesn't mean a thing because the raft is the one you sail:

![021](https://user-images.githubusercontent.com/5891591/127766063-3d1b3e83-53b8-4352-ad29-bc119a11d094.png)

**Comment by Pyrdacor** [comment]
@a1exh: Might be worth to add to the bug list. I guess nobody had bought a ship in the original as you get one for free. :D

**Comment by Pyrdacor** [comment]
So I got a time slot to fix this one and the two with the door to Valdyn. Now I have to leave for some days. Have fun. ;)

**Comment by Uukrull** [comment]
Compiled, tested and working.

Nicely done:

![56](https://user-images.githubusercontent.com/5891591/127785508-1049a8f3-7516-49fd-85c2-4c84a5a1e53a.png)

Many thanks!
