### ISSUE TITLE
The level 3 door at Luminor's Tower is missing the information text

### ISSUE THREAD

**Issue by Uukrull** [Pyrdacor/Ambermoon.net#129]
I couldn't open that door so I checked out how to open it and the reason is because the information text is missing:

![55](https://user-images.githubusercontent.com/5891591/127776391-8252856a-bb0b-419e-9d99-16f2ab142d1f.png)

WinUAE:

![024](https://user-images.githubusercontent.com/5891591/127776433-064c45a0-b608-4300-806b-80d22575e0da.png)

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6912921/Saves.zip)

**Comment by Uukrull** [comment]
Also, the sphere of opening is destroyed after opening the door so this could be a game breaking bug.

On WinUAE is still there:

![025](https://user-images.githubusercontent.com/5891591/127777219-6f61347c-0e76-462e-8cb3-7f852ae2a835.png)

**Comment by Pyrdacor** [comment]
This is indeed a serious bug. I just destroy everything that opens a door and don't check if the item can be destroyed. Thanks for reporting, I will adjust this.

**Comment by Uukrull** [comment]
At least I can get it back with the cheat _give 287_ so I can continue the testing :)

**Comment by Pyrdacor** [comment]
Should work with the current code. You have to compile yourself though.

**Comment by Uukrull** [comment]
Compiled, tested and working.

Have a nice week :)
