### ISSUE TITLE
Airship - Forest Moon. Kire's chest isn't empty

### ISSUE THREAD

**Issue by Uukrull** [Pyrdacor/Ambermoon.net#130]
![61](https://user-images.githubusercontent.com/5891591/128629309-558f606c-01d4-4104-84dc-6e3f97d8474f.png)

WinUAE:

![029](https://user-images.githubusercontent.com/5891591/128629315-00c6e496-a92a-44bd-90e1-e993d2f4ebab.png)

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6950558/Saves.zip)

**Comment by Pyrdacor** [comment]
But the remake version seems to be right here, doesn't it?

**Comment by Uukrull** [comment]
No. The first time you visit the airship, the chest is full (you need those items to progress in the game). The problem is when you use the gravstone and fly to the forest moon: the chest shouldn't contain those items.

**Comment by skdubg** [comment]
the same at the Morag Airship - Kire's chest isn't empty

**Comment by Pyrdacor** [comment]
Fixed in latest commit.

**Comment by Pyrdacor** [comment]
Released

**Comment by Uukrull** [comment]
Tested and working. Many thanks!
