### ISSUE TITLE
[Data] Unsupported text character ' '

### ISSUE THREAD

**Issue by Uukrull** [Pyrdacor/Ambermoon.net#135]
Move the cursor to the goto-point.

![70](https://user-images.githubusercontent.com/5891591/128642200-5ff4a3ef-aa74-49e6-bc6e-63905afa3fe3.png)

Crash:

> [Data] Unsupported text character ' '.
>    at Ambermoon.Data.Legacy.TextProcessor.CharToGlyph(Char ch, Boolean rune, Nullable`1 fallbackChar)
>    at Ambermoon.Data.Legacy.TextProcessor.<>c__DisplayClass2_0.<CreateText>b__0(Char ch)
>    at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
>    at Ambermoon.Data.Legacy.TextProcessor.FinalizeText(IEnumerable`1 glyphs)
>    at Ambermoon.Data.Legacy.TextProcessor.CreateText(String text, Nullable`1 fallbackChar)
>    at Ambermoon.UI.Layout.SetActiveTooltip(Position cursorPosition, Tooltip tooltip)
>    at Ambermoon.UI.Layout.Hover(Position position, CursorType& cursorType)
>    at Ambermoon.Game.UpdateCursor(Position cursorPosition, MouseButtons buttons)
>    at Ambermoon.Game.OnMouseMove(Position position, MouseButtons buttons)
>    at Ambermoon.GameWindow.Mouse_MouseMove(IMouse mouse, Vector2 position)
>    at Silk.NET.GLFW.Glfw.PollEvents()
>    at Silk.NET.Windowing.WindowExtensions.<>c__DisplayClass2_0.<Run>b__0()
>    at Silk.NET.Windowing.Internals.ViewImplementationBase.Run(Action onFrame)
>    at Silk.NET.Windowing.WindowExtensions.Run(IView view)
>    at Ambermoon.GameWindow.Run(Configuration configuration)
>    at Ambermoon.Program.Main()

WinUAE:

![039](https://user-images.githubusercontent.com/5891591/128642231-1ad47117-657e-46a9-9ec6-36b5f136692d.png)

The text should be Magic Spring 4, so it also needs the data edited.

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6951301/Saves.zip)

**Comment by Pyrdacor** [comment]
This is indeed a bug in the original data. The text in the original is "MAGIC SPRING \04" where \0 means just a null byte.

It does not crash as the original seems to stop text processing when encountering the first 0 byte. But all the goto point names are 16 characters long so the remake just reads those 16 chars and only trims trailing 0 bytes and try to display the rest. As the 0 byte is inside valid characters the 0 byte is tried to display but this won't work of course.

The right approach is to fix this inside the original data which I will do now. @a1exh Could you add this to the bug list?

**Comment by a1exh** [comment]
Done

**Comment by Pyrdacor** [comment]
@Uukrull Please re-test with latest Test-Release. It contains an updated version of the original game data (I didn't increase the game data version numbers yet). If you want to try it with your own data you can download the bugfixed version at https://github.com/Pyrdacor/Ambermoon/tree/master/Disks/Bugfixing/English/Amberfiles. For this issue the file 2Map_data.amb should be sufficient.

**Comment by Uukrull** [comment]
Yes, I already tested it yesterday with the updated data (I play with the external 1.08 + bugfixing data). I think is a good idea to leave the code as it is in case there are more data errors, because the crash tells something is wrong.

**Comment by Pyrdacor** [comment]
> I think is a good idea to leave the code as it is in case there are more data errors, because the crash tells something is wrong.

Yes this was my intention. It may lead to more crashes but will reveal data bugs.

The original code is sometimes too forgiving.
