### ISSUE TITLE
S'Orel goes missing under certain circunstances

### ISSUE THREAD

**Issue by Uukrull** [Pyrdacor/Ambermoon.net#137]
Enter S'Orel's room, advance and wait for the message:

![75](https://user-images.githubusercontent.com/5891591/128643666-73569043-8f64-42f3-b34e-c7b863ae3bcc.png)

Exit the room before the combat is started and go here:

![76](https://user-images.githubusercontent.com/5891591/128643667-b84023e4-d5fa-4b62-9fcd-f17db1b124db.png)

Wait 8 hours:

![77](https://user-images.githubusercontent.com/5891591/128643668-b7f8bbfd-6220-40e7-9042-d34844da9652.png)

Sleep:

![78](https://user-images.githubusercontent.com/5891591/128643669-63f46213-0451-4c3f-8f6a-3066cd25cc0f.png)

Go back to his room and he is nowhere:

![79](https://user-images.githubusercontent.com/5891591/128643670-4aef81be-5116-4c11-838a-4ca61d150440.png)

Luckily, loading a save made now brings him back so it isn't a game-breaking bug.

WinUAE with the same steps:

![041](https://user-images.githubusercontent.com/5891591/128643806-d27a55ad-3c25-4d47-b121-f43b91406748.png)

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6951363/Saves.zip)

**Comment by Pyrdacor** [comment]
Hopefully fixed now in code.

**Comment by Uukrull** [comment]
Compiled, tested and working. Mnay thanks!
