### ISSUE TITLE
Issue at antique plant level 4 (create of navigation stones)

### ISSUE THREAD

**Issue by skdubg** [Pyrdacor/Ambermoon.net#139]
hello,

at antique plant level 4 its not possible to create the navigations stones in green and blue.
please us the save game to test it, i can create only the yellow stones.

greetings

[Save.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6956692/Save.zip)

**Comment by Pyrdacor** [comment]
Ok I fixed it in code. Thanks for reporting. Will update the release tomorrow.

**Comment by skdubg** [comment]
thanks, its fixed in Test-Release 10-08-2021
