### ISSUE TITLE
Every text character is rendered twice

### ISSUE THREAD

**Issue by Metibor** [Pyrdacor/Ambermoon.net#14]
While trying to figure out how to display the map name correctly, I found out, that all text characters and shadows are created and rendered twice, every time `Text.set(IText value)` is called.

The call stack for a hovered item:
![grafik](https://user-images.githubusercontent.com/12674912/91717973-d33d8b80-eb92-11ea-8a27-a5729d9eb495.png)

This is not visible on manually positioned texts, like in chests:
![grafik](https://user-images.githubusercontent.com/12674912/91718674-206e2d00-eb94-11ea-95de-775a994d165d.png)

But if I use for example `mapName.Place(new Rect(16, 40, 175, 10), TextAlign.Center);` and then change the Text-property to a new name one pair of characters is rendered correctly centered and the other one is rendered left aligned beginning from center of the rectangle.
![grafik](https://user-images.githubusercontent.com/12674912/91718533-da18ce00-eb93-11ea-90b1-a1138e38a79b.png)

If I change `UpdateTextSprites()` to the following code, the text is only drawn once, but at the wrong position.
```csharp
        void UpdateTextSprites()
        {
            if (!UpdateCharacterPositions())
                return;

            characterSprites.ForEach(s => s?.Delete());
            characterSprites.Clear();
            characterShadowSprites.ForEach(s => s?.Delete());
            characterShadowSprites.Clear();
```

Could you have a look at it?

**Comment by Pyrdacor** [comment]
Ok thanks. I will look at it tomorrow.

**Comment by Pyrdacor** [comment]
Could you check in most recent commit please?

**Comment by Metibor** [comment]
Thank you, it is working now. 
My debug ouput shows, that every character and shadow is only added once to the sprite lists and the rendering happens at the correct position.
