### ISSUE TITLE
Missing text when talking to a dwarf at Dor Kiredon

### ISSUE THREAD

**Issue by Uukrull** [Pyrdacor/Ambermoon.net#142]
![84](https://user-images.githubusercontent.com/5891591/128833815-3a76da54-6104-49e5-848f-711aad1399cd.png)

WinUAE:

![042](https://user-images.githubusercontent.com/5891591/128833851-a36d58a5-1f4b-4017-8344-6d30a06ce74c.png)

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6960135/Saves.zip)

**Comment by a1exh** [comment]
3Map_texts.amb subfile 157.amb (hex)

It looks like the text parser in the remake interprets part of the INK control code as a SPACE. This pushes all characters on by one and probably the reason it is not displayed correctly?

**Comment by Pyrdacor** [comment]
Commit cb4343f6e3b766d201dd9d7dfc7b44a77167622b should fix it.

**Comment by Pyrdacor** [comment]
@a1exh Something like you mentioned. There can be spaces around the INK placeholders but they are trimmed in original. I didn't do this until now. I wonder why the 'O' was not drawn though. Maybe the text length was calculated wrong. With trimming now it works.

**Comment by Uukrull** [comment]
It works for the most part, but I found out one conversation with missing text:

![85](https://user-images.githubusercontent.com/5891591/128854286-f942facc-04f5-42a3-b757-de931b03ed80.png)

WinUAE:

![043](https://user-images.githubusercontent.com/5891591/128854310-23e3cf94-75df-460d-a1ec-e6b0e0d89921.png)

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6960969/Saves.zip)

**Comment by a1exh** [comment]
> I wonder why the 'O' was not drawn though. Maybe the text length was calculated wrong.
This new example looks like a text length issue too. The same as when it dropped the O from TO in the first. It results in a blank line which prevents the rest of the text fitting in the text box.

**Comment by Pyrdacor** [comment]
This was a hard one but now it is hopefully fixed in 29a9a054b829e23290cda3c0b0c1852a81ef125a.

**Comment by Uukrull** [comment]
A billions thanks!
