### ISSUE TITLE
The program doesn't respond after walking towards a poisonous plant

### ISSUE THREAD

**Issue by Uukrull** [Pyrdacor/Ambermoon.net#143]
Load the attached save and walks towards the plant:

![86](https://user-images.githubusercontent.com/5891591/128858080-209a73aa-f4e9-4b1b-b82c-cf55b8e00e68.png)

I have to close the remake after this:

![87](https://user-images.githubusercontent.com/5891591/128858097-5845e02b-e976-479b-9c10-a4a16f8193da.png)

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6961153/Saves.zip)

**Comment by skdubg** [comment]
it could be the same error/issue as #140 i think

**Comment by Uukrull** [comment]
Yes, I just arrived at that point and it seems similar.

**Comment by Pyrdacor** [comment]
Both are fixed in most recent commit. Release comes soon.

**Comment by Uukrull** [comment]
Yep. Many thanks!
