### ISSUE TITLE
Game stuck after giving the Tarbos amulet to the madman

### ISSUE THREAD

**Issue by Uukrull** [Pyrdacor/Ambermoon.net#144]
Give him the amulet:

![88](https://user-images.githubusercontent.com/5891591/128923544-4bb0b586-6f29-42fc-92d9-f7fc4b86de99.png)

The game hangs after Pepin levels up:

![89](https://user-images.githubusercontent.com/5891591/128923541-7d7bd134-efe7-4df6-9085-def3012ac26f.png)

In the Amiga version all six characters level up:

![044](https://user-images.githubusercontent.com/5891591/128923886-3306b7ec-b092-4a81-8000-1b4a400e8751.png)

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6964103/Saves.zip)

**Comment by skdubg** [comment]
i doesn't have this issue, Tar was the first member of my party.
could this be only on the english game? i don't think so.
or a problem if you already have several members.

**Comment by Uukrull** [comment]
> or a problem if you already have several members.

That's what I think. IIRC the most members I ever had that leveled up at the same time were two. Here we have six.

**Comment by Pyrdacor** [comment]
I guess I might have introduced this issue in the last fixes. Should be fixed in code now. ;)

**Comment by Pyrdacor** [comment]
Released

**Comment by skdubg** [comment]
@Uukrull 
on Morag when i wanted to hand S'Krel the water bottle it also occurred, with the test release it is fixed

**Comment by Uukrull** [comment]
Yes, tested and working here.
