### ISSUE TITLE
Issue (?) at alchemist tower

### ISSUE THREAD

**Issue by skdubg** [Pyrdacor/Ambermoon.net#146]
hello,

I'm not sure if it's a bug, with the savegame i'm in the alchemist tower on Lyramion and i can't sell any scrolls there.

is this normal?
[Save.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6970587/Save.zip)

**Comment by Uukrull** [comment]
Yep, with the Amiga version you can't:

![047](https://user-images.githubusercontent.com/5891591/129170206-66094b3a-df50-4ed5-9e4c-364dfcf1ba08.png)


![045](https://user-images.githubusercontent.com/5891591/129169903-b810fce6-28b0-490e-829e-c4d8a682d195.png)

![046](https://user-images.githubusercontent.com/5891591/129169907-e3aed456-18ba-4431-ac8e-39abc77403ce.png)

**Comment by skdubg** [comment]
thanks @Uukrull 
I wasn't sure anymore, i haven't played the Amiga version for more then 10 years.
