### ISSUE TITLE
graphic error in credits/extro/outro

### ISSUE THREAD

**Issue by skdubg** [Pyrdacor/Ambermoon.net#147]
hello,

after finishing the game there is a graphical error at the outro/extro (could it be in the original game too/or at WinUAE ?)
on step four (Valdyn) the picture looks crazy.

you can use the savegame, but have to win first :)
[Save.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6970710/Save.zip)

![Unbenannt](https://user-images.githubusercontent.com/8874416/129088802-13817ca2-3cc0-4202-8331-86fb749eacc5.jpg)

**Comment by Pyrdacor** [comment]
Which game data do you use? Built-in English or your own source?

**Comment by skdubg** [comment]
built in german data

**Comment by Pyrdacor** [comment]
Hm I thought I tested the built-in data. Ok I will check it tomorrow. The other images and texts are ok?

**Comment by skdubg** [comment]
yes the others are fine. it's the only one

**Comment by Pyrdacor** [comment]
Ok found the issue and fixed it in code.

**Comment by Pyrdacor** [comment]
Released

**Comment by skdubg** [comment]
tested and it's look fine too. many thanks 👍
