### ISSUE TITLE
Game stuck after casting monster knowledge

### ISSUE THREAD

**Issue by Uukrull** [Pyrdacor/Ambermoon.net#148]
This can be a tricky one because is random and doesn't happen while debugging with Visual Studio, but I managed to reproduce it most of the times following these steps:

Fast Battle Mode must be ON. Load the attached savegame and open the door with Drek's key:

![90](https://user-images.githubusercontent.com/5891591/129232274-a4f00f13-ac91-43c0-885f-4dbe848e7ef7.png)

Pepin and Egil must attack the gargoyle in front of them:

![91](https://user-images.githubusercontent.com/5891591/129232280-0df006d8-9779-4a6f-ac79-9cb5ed81c346.png)

![92](https://user-images.githubusercontent.com/5891591/129232284-003b171b-baf1-462e-88df-bca34eb7f556.png)

Nelvin must cast Firepillar:

![93](https://user-images.githubusercontent.com/5891591/129232286-e7d36b1d-f319-4168-91cb-830291d34bf7.png)

Sabine must move to the right:

![94](https://user-images.githubusercontent.com/5891591/129232287-aa56bc00-f794-4b42-bd03-112bc8498eff.png)

Valdyn must cast Monster knowledge on that gargoyle:

![95](https://user-images.githubusercontent.com/5891591/129232291-afa7ab0c-6850-4821-9ee8-9639e514319e.png)

Press OK and the game will be stuck after Valdyn casts his spell and before the text dialog with the monster info appears:

![96](https://user-images.githubusercontent.com/5891591/129232292-d12b157f-012c-438a-bd0f-d2da1ced4962.png)

If I only use Valdyn in that turn and cast the spell, there are no problems:

![97](https://user-images.githubusercontent.com/5891591/129234006-011d1d85-4675-4a59-bd74-1cb4136ba9af.png)

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6977036/Saves.zip)

**Comment by skdubg** [comment]
hi,

i have try it several times, but can't reproduce it.
followed your steps, Valdyn spells, the text info appears and i can click to continue.
tested on internal english data with Test-Release from 12-08-2021

**Comment by Pyrdacor** [comment]
I will try to reproduce tomorrow.

**Comment by Uukrull** [comment]
I just tried the latest release instead of my own build and it happens only when using external data (1.08 + bugfixing)

**Comment by Pyrdacor** [comment]
Strange. The game code at this point should not be dependent on some game data.

**Comment by Pyrdacor** [comment]
I can't reproduce it. Is this still a thing with the current version?

**Comment by Uukrull** [comment]
I just tried it and works fine now so I'll close this.
