### ISSUE TITLE
Issue at second page in options

### ISSUE THREAD

**Issue by skdubg** [Pyrdacor/Ambermoon.net#149]
hello,

in the options on the second page there are the settings mixed up.
It always activates/deactivates a different setting than the one you are looking at.
The tooltips can also no longer be deactivated.

greetings

**Comment by Pyrdacor** [comment]
Thanks. I fixed it in code. Release comes later the day.

**Comment by Pyrdacor** [comment]
Released now

**Comment by skdubg** [comment]
its working now. thank you
