### ISSUE TITLE
Camera direction saved incorrectly

### ISSUE THREAD

**Issue by Talmit** [Pyrdacor/Ambermoon.net#150]
When saving and reloading the game, the camera direction seems to not be saved correctly. I entered "Großvaters Keller" and stood in front of the well, facing it, then saved. Once I loaded, the the camera was facing eastwards, while I saved with the camera facing southwards / towards the well. The bug seems easily reproduceable with my savegame (Save 3 in the attachment) by moving the camera, then saving again.

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6986057/Saves.zip)
1.0.0 Testrelease 11.08.2021 Windows 64 bit (German 1.07)

P.S.: Thanks for bringing my favorite game of all times to the PC

**Comment by skdubg** [comment]
this is similar to #151, at a certain angle the game changes the viewing direction. 
Someone might have to compare it with the original game.

**Comment by Uukrull** [comment]
I thougth the Amiga version had the same problem, but I just tested it and the camera position is saved and loaded correctly:

I saved using WinUAE facing the four directions, loaded them and works as intended:

[Saves_WinUAE.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6986191/Saves_WinUAE.zip)

TEST1
![057](https://user-images.githubusercontent.com/5891591/129440883-242a13af-2bd7-4ec1-a1c4-3dcb4ace279a.png)

TEST2
![058](https://user-images.githubusercontent.com/5891591/129440884-3cb98c07-dd89-4d9e-9b00-b8e55751254d.png)

TEST3
![059](https://user-images.githubusercontent.com/5891591/129440885-ee410b50-0105-4ede-92b8-e54669a18f29.png)

TEST4
![060](https://user-images.githubusercontent.com/5891591/129440886-9df7ddc3-f1c0-4d86-891b-ea3101b316f1.png)

I did the same with the remake and it always show the same direction:

[Saves_Remake.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6986209/Saves_Remake.zip)


![(747)](https://user-images.githubusercontent.com/5891591/129441063-410a64b2-f401-44d9-ade5-28e88d1ed62a.png)

**Comment by Pyrdacor** [comment]
Thanks for investigating. I will have a look at it. But most likely only on Monday.

**Comment by Uukrull** [comment]
The savegame direction is updated when the player moves, but not when the player rotates:

https://github.com/Pyrdacor/Ambermoon.net/blob/4175337a2dee063ba08a3bb746f48acef4a16305/Ambermoon.Core/Game.cs#L4972-L4982

**Comment by Uukrull** [comment]
I compiled and tested the latest code and doesn't seem to work.

After facing North and saving:

![126](https://user-images.githubusercontent.com/5891591/129582486-093a0977-2bc8-4a2b-99ba-15d488d40734.png)

If I load the save, the camera is facing West:

![127](https://user-images.githubusercontent.com/5891591/129582484-03bb7799-16eb-40de-9bba-9a7563fad052.png)

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6993244/Saves.zip)

**Comment by Pyrdacor** [comment]
Hm did you turn after map change? Maybe it does not save the direction on map change?

**Comment by Uukrull** [comment]
That was only an example. Here is another with the ruins:

I load a save:

![128](https://user-images.githubusercontent.com/5891591/129585300-bfd6dbbc-d503-4ba3-9332-3ad13d1f57b3.png)

Turn to the right and save:

![129](https://user-images.githubusercontent.com/5891591/129585365-3a973179-1531-4b4f-8e82-b78d3acbb75b.png)

and the new save doen't have the updated direction.

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6993383/Saves.zip)

**Comment by Pyrdacor** [comment]
Ok thanks. Do you turn by mouse or by keys? If mouse, on 3D view or with buttons?

**Comment by Uukrull** [comment]
I only tried with WASD.

**Comment by Pyrdacor** [comment]
Ok I think I forgot to adjust the code for key turning. ;) Will fix it tomorrow.

**Comment by Pyrdacor** [comment]
Should work now.

**Comment by Uukrull** [comment]
Yes. Many thanks!

**Comment by Pyrdacor** [comment]
Released
