### ISSUE TITLE
Character centered in tile after saving on 3D maps

### ISSUE THREAD

**Issue by Talmit** [Pyrdacor/Ambermoon.net#151]
When saving and reloading the game, the character appears to be centered on the tile the game was saved on. This can lead to the game being stuck, e.g. when saving on the tile containing the well in "Großvaters Keller". In order to reproduce the issue, one has to move inside that tile and save the game. I included a save game (Save 3) right before the well.

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6986057/Saves.zip)
1.0.0 Testrelease 11.08.2021 Windows 64 bit (German 1.07)

**Comment by skdubg** [comment]
I don't think this is a bug, if I remember correctly, in the original game it was also the case that you are centered on your "field".

**Comment by Pyrdacor** [comment]
I think those are two things. First of all the original savegame format is a bit limited. It only stores the tile position and the direction as north, east, south or west. So it cannot store your exact direction and location.

But the remake might have a little bit different conversion from tile position to exact 3D position and vice versa (the rendering code is totally different even if the result looks very similar). I think this leads to the issue. So I will have a look at it and maybe can adjust it.

**Comment by Pyrdacor** [comment]
Based on the research of @Uukrull in #150 I would guess that the precise position is not correctly saved as well.

**Comment by Pyrdacor** [comment]
Ok my remake is a bit more forgiving when it comes to partial tile moving. So you can move closer to small objects like the well. Imo this feels better as you won't have to move large circles around small objects. I guess in the original this is not necessary as the field of view is different but with the new engine this is necessary to feel ok.

As you can move closer to the well you can actually enter the tile partially and through rounding (partial tile coordinates to real tile coordinates) you actually have a tile position of a blocking tile. I could change that but as I said this would feel bad (I tested it). Small objects would have a large collision box and it feels like you run into larger invisible boxes around small objects.

So I decided to solve this differently. When saving, the current tile position is checked for blocking state and if it blocks, a nearby tile is chosen as the saved position. This is done in a way that the non-blocking position closest to you will be picked.

**Comment by skdubg** [comment]
thats sounds very well. thank you

**Comment by Pyrdacor** [comment]
Released
