### ISSUE TITLE
Index was outside the bounds of the array

### ISSUE THREAD

**Issue by Uukrull** [Pyrdacor/Ambermoon.net#153]
Inspect this compartment:

![115](https://user-images.githubusercontent.com/5891591/129442329-71b181a0-dd2a-4668-9efc-2bae525e085d.png)

Try to lockpick it:

![111](https://user-images.githubusercontent.com/5891591/129442277-a7e027ae-3264-4197-baf1-944883982ba4.png)

We fail:

![112](https://user-images.githubusercontent.com/5891591/129442278-4a22ae41-c570-499d-9833-26a05b2269c6.png)

Fight the robots:

![113](https://user-images.githubusercontent.com/5891591/129442279-22f58500-f513-4edb-a55e-bd33cbd4173a.png)

Advance:

![114](https://user-images.githubusercontent.com/5891591/129442281-95efc45a-08d5-4e7a-832c-c197c17f9477.png)

Crash:

> Index was outside the bounds of the array.
>    at Ambermoon.Battle.MoveCharacterTo(UInt32 column, UInt32 row, Character character)
>    at Ambermoon.Battle.MoveCharacterTo(UInt32 tile, Character character)
>    at Ambermoon.Game.<>c__DisplayClass470_1.<AdvanceParty>g__MoveAnimationFinished|1()
>    at Ambermoon.Render.BattleAnimation.Update(UInt32 ticks)
>    at Ambermoon.Game.UpdateBattle()
>    at Ambermoon.Game.Update(Double deltaTime)
>    at Ambermoon.GameWindow.Window_Update(Double delta)
>    at Silk.NET.Windowing.Internals.ViewImplementationBase.DoUpdate()
>    at Silk.NET.Windowing.WindowExtensions.<>c__DisplayClass2_0.<Run>b__0()
>    at Silk.NET.Windowing.Internals.ViewImplementationBase.Run(Action onFrame)
>    at Silk.NET.Windowing.WindowExtensions.Run(IView view)
>    at Ambermoon.GameWindow.Run(Configuration configuration)
>    at Ambermoon.Program.Main()

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6986259/Saves.zip)

**Comment by Pyrdacor** [comment]
Good catch! The problem was that the monsters in the back row are moved first. But this way they replace the monsters in the near row before they are moved. When trying to move them, they are no longer in the collection of battle fields and therefore this error happens. Now I move them from back to front (list-wise) which means from front row to back row.

**Comment by Uukrull** [comment]
Compiled, tested and working. Many thanks!
