### ISSUE TITLE
The teleporter at Antique Area 3 disappears

### ISSUE THREAD

**Issue by Uukrull** [Pyrdacor/Ambermoon.net#154]
It's there only at specific times (x:00 and x:10) and it never works:

![116](https://user-images.githubusercontent.com/5891591/129450016-e7af29b1-1147-4d01-8372-83bd1f2f1368.png)

![117](https://user-images.githubusercontent.com/5891591/129450018-1e4a3280-572b-4564-922b-a5efaed143a2.png)

The rest of the time, disappears:

![118](https://user-images.githubusercontent.com/5891591/129450019-130ac301-5369-42d3-a867-069f259ad3ab.png)

![119](https://user-images.githubusercontent.com/5891591/129450020-3f711ee5-fb39-4f96-991c-a8ba266990af.png)

With the Amiga version, it's always there and works:

![075](https://user-images.githubusercontent.com/5891591/129450280-58e1a61d-3553-4502-89b4-d7e05e086ea9.png)

![076](https://user-images.githubusercontent.com/5891591/129450281-df4ed7b8-7336-4c3c-a07e-cc48ab15ecfa.png)

![071](https://user-images.githubusercontent.com/5891591/129450071-12b7ccae-6ebe-4fd3-aa2b-37b620508a64.png)

![072](https://user-images.githubusercontent.com/5891591/129450072-1568d320-9e5e-478e-982b-64fcbdd46593.png)

You're teleported here:

![077](https://user-images.githubusercontent.com/5891591/129450868-3d4edcc5-19bf-4069-a65b-e17d10702f8a.png)

![078](https://user-images.githubusercontent.com/5891591/129450869-9e5d6c66-7edd-4945-9584-37f24e6b29c3.png)

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6986631/Saves.zip)

**Comment by Pyrdacor** [comment]
Should be fixed with 46fcfcd9afe33cf098f144c0bf50ce729fde1f47.

**Comment by Uukrull** [comment]
Compiled, tested and working. Many thanks!
