### ISSUE TITLE
Guardians respawn infinitely at Antique Area 4

### ISSUE THREAD

**Issue by Uukrull** [Pyrdacor/Ambermoon.net#155]
Fight this group:

![120](https://user-images.githubusercontent.com/5891591/129457666-00444a12-84f3-43cf-9ed1-b99ef9438dc4.png)

After killing it, another group awaits.

![121](https://user-images.githubusercontent.com/5891591/129457667-6d332c29-62d8-43ff-85fc-8d7d5d22cd50.png)

![122](https://user-images.githubusercontent.com/5891591/129457668-47099294-2193-4816-a1e5-1b35dcf42d4e.png)

I even tried godmode and there is no end :(

With the Amiga version I only have to kill one group.

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6987053/Saves.zip)

**Comment by Pyrdacor** [comment]
It's the hardcore mode. ;) Just kidding. I'll have a look soon.

**Comment by Pyrdacor** [comment]
Should be fixed with 163219f87897a8b06d131b4dbf57a73e47927dca.

**Comment by Uukrull** [comment]
Compiled, tested and working. Many thanks!
