### ISSUE TITLE
Rinakles has a tiny... teleporter

### ISSUE THREAD

**Issue by Uukrull** [Pyrdacor/Ambermoon.net#157]
![125](https://user-images.githubusercontent.com/5891591/129483258-9be3c947-8df5-4c0e-a226-1f4c68f50198.png)

WinUAE:

![081](https://user-images.githubusercontent.com/5891591/129483268-094c9368-b849-47d3-ae9d-d5d90598c718.png)

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6988374/Saves.zip)

**Comment by a1exh** [comment]
Could this be due to the change to 3Map_data.amb for fix #63?

**Comment by Uukrull** [comment]
I'm using 1.08+bugfixing with the remake and WinUAE so I don't think is a data problem.

**Comment by Pyrdacor** [comment]
I analyzed it and it is a skeleton in my cupboard I hoped it won't come up again.

The labdata object positioning is kind of strange for some objects. Especially those on the ceiling.

I came up with several logics and the current one works in the most cases. But not in all I guess. For example the plants hanging on the ceiling of grandfather's cellar are also too small in comparison to the original version. But there it isn't that obvious. But now you found a case where it looks too bad.

I will dig into this a bit more once again. But it will take some time.

**Comment by Uukrull** [comment]
No problem :)

**Comment by Pyrdacor** [comment]
Ok I fixed it. Now Rinakles has a huge ... teleporter. It appear even bigger than in the original. But it should be correct this way. I checked several other maps if they still look ok and found none which looks wrong. So I hope this works now for all maps.

**Comment by Uukrull** [comment]
Compiled, tested and working. Many thanks!
