### ISSUE TITLE
Game stuck after casting the resurrection spell

### ISSUE THREAD

**Issue by Uukrull** [Pyrdacor/Ambermoon.net#158]
Camp and cast the resurrection spell:

![130](https://user-images.githubusercontent.com/5891591/129595570-d1ff938f-995f-4321-813b-009e965286e5.png)

Game stuck:

![131](https://user-images.githubusercontent.com/5891591/129595595-2b475a0a-9325-4357-b0c6-53105ec07f27.png)

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6993830/Saves.zip)

**Comment by Pyrdacor** [comment]
I am pretty sure this worked but maybe your group alive-dead constellation is special. I hope "Wake the dead" works at least?

**Comment by Uukrull** [comment]
> but maybe your group alive-dead constellation is special

It happened with only one dead character: Egil; later I tried to reproduce it but that's the best I could get.

"Wake the dead" is working.

**Comment by Pyrdacor** [comment]
Should work now.

**Comment by Uukrull** [comment]
Compiled, tested and working. Many thanks!
