### ISSUE TITLE
Moving rays at Antique Area 2 are now impossible

### ISSUE THREAD

**Issue by Uukrull** [Pyrdacor/Ambermoon.net#159]
This happened after https://github.com/Pyrdacor/Ambermoon.net/commit/46fcfcd9afe33cf098f144c0bf50ce729fde1f47

The rays wait too much time at the corner before moving to the left and the rays behind catch us, so this zone is impossible without the jump spell.

Before that commit, the rays moved smoothly to the left but now they disappear and reappear abruptly.

![132](https://user-images.githubusercontent.com/5891591/129717888-e41279ac-ed47-4aea-b947-7cb8c86a72cd.png)

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/6999525/Saves.zip)

**Comment by Pyrdacor** [comment]
Should be fixed in most recent TestRelease now.
