### ISSUE TITLE
App won't start on Netbook (Atom N270)

### ISSUE THREAD

**Issue by skdubg** [Pyrdacor/Ambermoon.net#161]
hi,

i tried Ambermoon on my old Netbook. its run Windows 10 1507 very well.
the App crashes. is it possible to fix it?

![netbook](https://user-images.githubusercontent.com/8874416/129894090-6a6d330d-c603-4c4c-bf59-b594e80c3c5f.jpg)

**Comment by a1exh** [comment]
I suspect your Netbook doesn't have an OpenGL driver?

**Comment by skdubg** [comment]
it should be. driver is from Microsoft and the included GPU supports OpenGL i think

**Comment by a1exh** [comment]
This used to happen to me before @Pyrdacor integrated glfw.

Try downloading glfw and putting the files glfw3.dll and glfw3dll.lib in the Ambermoon.net directory.

https://www.glfw.org/download

**Comment by a1exh** [comment]
I think your Netbook doesn't support a high enough version of OpenGL. A quick google says it only supports OpenGL 1.5 perhaps that is not high enough for Ambermoon.net?

**Comment by skdubg** [comment]
this could be the problem now...

**Comment by Pyrdacor** [comment]
You need at least OpenGL 3.1 to play. Older versions cannot be supported as they don't support the features I need.

I wonder why he didn't find glfw in the first place. This should not happen in theory.

**Comment by skdubg** [comment]
Thank you very much. 😁
