### ISSUE TITLE
Crystal ball shouldn't work in the palaces

### ISSUE THREAD

**Issue by Uukrull** [Pyrdacor/Ambermoon.net#162]
![133](https://user-images.githubusercontent.com/5891591/129960665-f2f74ac8-54c5-405d-b29a-79f7a798d93c.png)

WinUAE:

![082](https://user-images.githubusercontent.com/5891591/129960700-ef895551-d0d8-4ac9-b2e6-6a17f180409e.png)

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/7009731/Saves.zip)

**Comment by Pyrdacor** [comment]
Could you be so kind to test if other items / spells are disabled as expected? I think only map related spells / items are disabled.

**Comment by Uukrull** [comment]
What other objects do you have in mind?

**Comment by Pyrdacor** [comment]
> What other objects do you have in mind?

Magic map comes to mind. I guess the magic compass works on Morag? Otherwise Netsraks staff.

**Comment by Uukrull** [comment]
OK. I'll try them tomorrow.

**Comment by Uukrull** [comment]
WinUAE:

Netsrak staff and magical compass work.
Map view scroll doesn't.
Mystical globe works but is useless because you can't use the map.

**Comment by Pyrdacor** [comment]
Should be fixed in most recent TestRelease now.
