### ISSUE TITLE
In battle, if no character is eligible to be a leader, the game over screen should be displayed

### ISSUE THREAD

**Issue by Uukrull** [Pyrdacor/Ambermoon.net#163]
In this example, Pepin fleed and can't be selected so the game is stuck. The same applies is the character is, for example, mad.

![134](https://user-images.githubusercontent.com/5891591/130101888-19c6c812-326c-4d27-92ff-bad9e3c58ff6.png)

WinUAE:

![083](https://user-images.githubusercontent.com/5891591/130101981-af1d37c4-0530-4059-a853-eec2defa2a2d.png)

**Comment by Pyrdacor** [comment]
Hm I thought this works. But maybe only outside battle? I will have a look.

**Comment by Uukrull** [comment]
This was in battle, in particular against a group of spiders while I was trying to reproduce a bug I encountered weeks ago:

>     Index was outside the bounds of the array.
>        at Ambermoon.Battle.GetCharacterAt(Int32 index)
>        at Ambermoon.Battle.RunBattleAction(BattleAction battleAction, UInt32 battleTicks)
>        at Ambermoon.Battle.NextAction(UInt32 battleTicks)
>        at Ambermoon.Battle.Update(UInt32 battleTicks)
>        at Ambermoon.Game.UpdateBattle()
>        at Ambermoon.Game.Update(Double deltaTime)
>        at Ambermoon.GameWindow.Window_Update(Double delta)
>        at Silk.NET.Windowing.Internals.ViewImplementationBase.DoUpdate()
>        at Silk.NET.Windowing.WindowExtensions.<>c__DisplayClass2_0.<Run>b__0()
>        at Silk.NET.Windowing.Internals.ViewImplementationBase.Run(Action onFrame)
>        at Silk.NET.Windowing.WindowExtensions.Run(IView view)
>        at Ambermoon.GameWindow.Run(Configuration configuration)
>        at Ambermoon.Program.Main()

This is the save where I simply keep pressing OK.

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/7016286/Saves.zip)

**Comment by Pyrdacor** [comment]
Should be fixed in most recent TestRelease now.
