### ISSUE TITLE
Issue when dismissing party members

### ISSUE THREAD

**Issue by skdubg** [Pyrdacor/Ambermoon.net#164]
hi,

its not possible to dismissing some party members.

greetings

![Unbenannt](https://user-images.githubusercontent.com/8874416/130102499-b42db5e0-1867-4951-9084-bd739bd79f15.jpg)

**Comment by Pyrdacor** [comment]
Can you tell me which party members? Thanks.

**Comment by skdubg** [comment]
i tried it with:

Tar the Dark, Leonaria, Nelvin, Egil.

Sabine is working now.

**Comment by Pyrdacor** [comment]
Ok than I think I know. Selena, Valdyn and Gryban should also work and the rest not.

**Comment by Pyrdacor** [comment]
I fixed it in code. Unfortunately it will not work with a savegame where you already invited them to your party. So I fear those savegames are lost. :( Sorry.

**Comment by skdubg** [comment]
no problem. i have lost 2 hours of gaming with this savegame, i forgot to save it before this error occure.
thanks for fixing.

**Comment by Pyrdacor** [comment]
I have an idea. I can provide a fix which can rescue the savegame. Will do so soon.

**Comment by Pyrdacor** [comment]
Oh ok I understand. But I will add the savegame rescue anyway. It fixes it then for all who have recent savegames.

**Comment by Pyrdacor** [comment]
> no problem. i have lost 2 hours of gaming with this savegame, i forgot to save it before this error occure.
> thanks for fixing.

I will add a crash savegame soon to avoid this. It will backup the current state on crashs.

**Comment by Pyrdacor** [comment]
Should be fixed in most recent TestRelease now. I also added some code to fix broken savegames. So even if it lead to a crash, it should not with the same savegame and new release.

**Comment by Pyrdacor** [comment]
Ah I almost forgot. When the game crashes, a backup savegame is created (if possible). It is stored in Save.99 folder. When you restart the game and choose "continue" there will be a popup which asks if you want to load it. After loading the backup save is deleted so be sure to save it immediately to another save slot. You can of course backup the Save.99 folder yourself or send this folder to me when a crash happens. I will create a pinned issue for that too.
