### ISSUE TITLE
Cannot move two tiles with Selena in battle

### ISSUE THREAD

**Issue by Talmit** [Pyrdacor/Ambermoon.net#165]
When trying to move with Selena, I can only select tiles in a distance of 1 to the character. Her speed is at 101, so she should be able to move two fields.

![image](https://user-images.githubusercontent.com/88923192/130315067-3b007878-9564-474e-9fb9-57fe060394a9.png)

![image](https://user-images.githubusercontent.com/88923192/130315031-738e18ae-27ec-49bc-87bf-4db4cd4d75fc.png)

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/7025128/Saves.zip)
(Relevant save is Siran2, just enter any of the teleporters and a battle with some golems should occur.)

**Comment by Uukrull** [comment]
I didn't know thas was even possible, but it is.

WinUAE:

![086](https://user-images.githubusercontent.com/5891591/130319713-5a7d37d9-b5cf-48dd-8169-25789366bb60.png)

**Comment by Pyrdacor** [comment]
Already fixed it locally. Will update soon.

**Comment by Pyrdacor** [comment]
Should be fixed in most recent TestRelease now.
