### ISSUE TITLE
Combat tooltip remains at original position

### ISSUE THREAD

**Issue by Talmit** [Pyrdacor/Ambermoon.net#166]
When moving in combat, the tooltip for the character remains at its original position. So if I for instance move Selena, her tooltip stays at the point where she was at the start of the combat:

![image](https://user-images.githubusercontent.com/88923192/130319725-b8dbbb59-6d64-4735-afc3-92868cef8eab.png)

![image](https://user-images.githubusercontent.com/88923192/130319716-c406437e-4b56-49a2-9cff-b6f05bf3db9e.png)

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/7025390/Saves.zip)
(Relevant Save: Siran2, move down the stairs)

**Comment by Pyrdacor** [comment]
Should be fixed in most recent TestRelease now.
