### ISSUE TITLE
Using item resets action of active (not using) character

### ISSUE THREAD

**Issue by Talmit** [Pyrdacor/Ambermoon.net#167]
When using an item, the action of the selected (yellow name) character is reset.

![image](https://user-images.githubusercontent.com/88923192/130319935-5fbfc867-d969-4daf-8d0a-f36b7c006e4b.png)

![image](https://user-images.githubusercontent.com/88923192/130319943-03e0ddf3-7d90-4ab5-bee2-daf40f16b305.png)

![image](https://user-images.githubusercontent.com/88923192/130319975-54a926d1-18ce-4565-b459-53952f306513.png)

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/7025390/Saves.zip)
(Relevant Save: Siran2, move down the stairs)

**Comment by Pyrdacor** [comment]
I can not see how this is a bug. Item usage is a battle action too so it replaces attacks etc. It is nearly the same as a spell cast. So you can only perform one action per round. Attack, cast spell, move, flee, parry or use an item. I think this is correct behavior.

**Comment by Talmit** [comment]
Sorry, I think I skipped a step in the explanation. Definitely my fault.

The actual issue with the behavior is that the character using the item in the above screenshots is Nelvin while Egils action is reset, as Egil is the selected (yellow name / yellow marked) character. When I'd select someone to use the potion on (e.g. Selena), the potion usage would still appear as an action on Nelvin. 

So Egil would neither be the one to activate the potion, nor the person receiving its benefits, but his attack action is still removed.

**Comment by Pyrdacor** [comment]
Ah ok now I get it. ;) Ok I will have a look soon.

**Comment by Pyrdacor** [comment]
Should be fixed in most recent TestRelease now.
