### ISSUE TITLE
Removing Nelvin from the party crashes the game

### ISSUE THREAD

**Issue by Talmit** [Pyrdacor/Ambermoon.net#168]
When removing Nelvin from the party, the game crashes:

![image](https://user-images.githubusercontent.com/88923192/130320243-467fac75-5f5d-47b7-9349-480521c26a30.png)

![image](https://user-images.githubusercontent.com/88923192/130320310-65e53491-f47a-4864-8db0-4d5e3354bfd9.png)

Game version 1.0.0 Test (17. August), Gamedata 1.0.7 German

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/7025414/Saves.zip)
(Relevant save is Siran2)

**Comment by skdubg** [comment]
Hi,

its fixed in #164

**Comment by Pyrdacor** [comment]
It's fixed on code but I have to release it. Will come soon.

**Comment by Pyrdacor** [comment]
Should be fixed in most recent TestRelease now.
