### ISSUE TITLE
Crash when opening inventory from other characters

### ISSUE THREAD

**Issue by Thallyrion** [Pyrdacor/Ambermoon.net#17]
The game crashes when i try to open the inventory from a character other than the main character. It just quits without any error message.
The inventory of the main character works.

**Comment by Metibor** [comment]
Is your main character female (WEIBLICH) and the others are male (MÄNNLICH)?
If that is the case than it is the same issue as #16 because of the encoding of the umlaut in the executable.
If you have the english data files and use them it should work.

**Comment by Thallyrion** [comment]
That is exactly the case. Didn't know that the problems are related.

**Comment by Pyrdacor** [comment]
Duplicate of #16
