### ISSUE TITLE
When saving in front of New Lake, the game loads in the south of New Lake

### ISSUE THREAD

**Issue by Talmit** [Pyrdacor/Ambermoon.net#170]
When saving in front of the city of New Lake, the game loads a few dozen tiles in the south of the city:

(Saving)
![image](https://user-images.githubusercontent.com/88923192/130343574-35399b82-b7bc-446a-9d2b-572c991c2a71.png)

(Loading)
![image](https://user-images.githubusercontent.com/88923192/130343625-8061ab1e-a46e-412c-bed7-2cddda7f080e.png)

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/7026633/Saves.zip)
(1.0.7 German, 1.0.0, 21.08.2021), relevant save is Siran2, I saved in front of the city, but you have to walk some tiles upwards if you want to save again)

When saving at the same spot again and reloading, I end up in the middle of the ocean.

**Comment by Pyrdacor** [comment]
Ok thanks. I will have a look.

**Comment by Talmit** [comment]
Thank you, you rock 👍. I kind of feel bad about posting these bugs, as you have done amazing work, so I thought I'd say something nice (if off-topic in an issue thread I suppose) for once. It's really great being able to play ambermoon without starting up WinUAE every time with faster loading times, fast battles and some cool new features (I do love the auto-rune translate for instance ;)). And I mean you even added the save-game rescue for issue #164 which is really nice, as I'd otherwise would have have to drown Nelvin when crossing over to Burnville :). So thanks once more for all the hard work and fixing everything so fast.

**Comment by Pyrdacor** [comment]
Thanks for the kind words. This is really valuable for me because it boosts my motivation even more. I'm glad my efforts are acknowledge. Thank you very much. :)

**Comment by Pyrdacor** [comment]
Ah and don't worry. Bug reports are important for me to make the game better, so you're helping me. Of course it is a bit frustrating when they are hundreds of them but this is the business of a developer I guess. :D

**Comment by Pyrdacor** [comment]
Released
