### ISSUE TITLE
When using identify from a scroll, the identification process breaks some functions of the game

### ISSUE THREAD

**Issue by Talmit** [Pyrdacor/Ambermoon.net#171]
When using identify from the scroll, a numerous amount of errors occurs:

1) The selection for the affected character seems wonky, as the text does not appear at the correct position (above the equipped items) but at another (probably at the text position of the rest-menu?):

![image](https://user-images.githubusercontent.com/88923192/130343759-170a1e0a-6ba0-4a43-b111-4abc6b4f9298.png)

2) After selecting a character, the icon is a click icon instead of a selection-cursor.

![image](https://user-images.githubusercontent.com/88923192/130343875-533483d1-e67e-4e37-921f-450794ded7ee.png)

3) After closing the identified item and the inventory, the inventory cannot be opened again. When closing the rest-menu, no movement on the map is possible.

![image](https://user-images.githubusercontent.com/88923192/130343927-2d3cc192-5b3f-4a85-91b4-1a0801e0b66b.png)

![image](https://user-images.githubusercontent.com/88923192/130343962-9d3ddcd1-df58-4e38-b2eb-8dfccaa9731e.png)

4) After saving and reloading, the scroll is not spent

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/7026642/Saves.zip)
(1.0.7 German, 1.0.0, 21.08.2021), relevant save is Siran2, I saved in front of the city, so due to #170 you should probably end up in the south of the city)

When using a spell instead of a scroll, the process works without a hitch.

**Comment by Pyrdacor** [comment]
Released
