### ISSUE TITLE
Neras "start of combat" animation is missing

### ISSUE THREAD

**Issue by Talmit** [Pyrdacor/Ambermoon.net#172]
Usually Nera turns into a dragon when the combat starts. However, that animation is currently missing, he starts combat in the form of a dragon.

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/7027956/Saves.zip)
(Version 1.0.0, German 1.0.7, Relevant Save Siran2, move through the corridor to encounter Nera)

**Comment by Pyrdacor** [comment]
Released
