### ISSUE TITLE
Showing Kay's amulett to Norel crashes the game

### ISSUE THREAD

**Issue by Talmit** [Pyrdacor/Ambermoon.net#173]
When showing Kay's amulett to Norel, the game crashes with the message "Object reference not set to an instance of an object":

![image](https://user-images.githubusercontent.com/88923192/130369749-a1e7d4f5-1d3b-4a1c-b549-be7b7bc04b3d.png)

![image](https://user-images.githubusercontent.com/88923192/130369769-4d230dcc-84a9-4842-9955-108c1d405f8a.png)

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/7028134/Saves.zip)
(Relevant Save: Crash or the Crash-Save itself, German 1.0.7, 21.08.2021)

When giving Norel the item, the game does not crash.

**Comment by Pyrdacor** [comment]
Fixed in code. Release is coming later.

**Comment by Pyrdacor** [comment]
Released
