### ISSUE TITLE
When aborting an item use in inventory, most game elements are blocked afterwards

### ISSUE THREAD

**Issue by Talmit** [Pyrdacor/Ambermoon.net#174]
Similar to #171 

Use an item in the inventory (e.g. in the 3D map)
![image](https://user-images.githubusercontent.com/88923192/130450349-ead2de3c-8008-4a68-9789-e02bd7ff417b.png)

Right-Click when prompted about the target person
![image](https://user-images.githubusercontent.com/88923192/130450431-df0e6c23-60d8-4a6a-8931-b77bae4496c8.png)

A right click on another character doesn't open their inventory screen. When clicking exit, the cursor in the main area does not switch to the movement cursors and movement is impossible.

![image](https://user-images.githubusercontent.com/88923192/130450679-a69f1205-f5a4-47fc-9838-2d9ffe8a54df.png)

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/7032079/Saves.zip)
(Version 1.0.7 German, 23.08.2021, relevant save game is Siran2)

**Comment by Pyrdacor** [comment]
The right click is correct. It aborts the usage as you should pick a character and not an item. So there is no need to enter the inventory. The cursor thing should not happen so I will have a look. ;)

**Comment by Talmit** [comment]
I seem to have phrased that unclear once more, sorry about that. Basically I tried two right clicks - one to intentionally abort the usage-action (which seemed to work at first), then one to enter the other players character (which should work as I wasn't in a special action anymore but in the normal "inventory mode"). That right click failed as well as most other actions (such as moving on the map, right-clicking to exchange the movement action grid by the action grid).

**Comment by Pyrdacor** [comment]
Released
