### ISSUE TITLE
SLP appear in inventory screen when storing items with Egil

### ISSUE THREAD

**Issue by Talmit** [Pyrdacor/Ambermoon.net#180]
This seems a bit silly to report as it's basically a non-issue but since I always notice it when interacting with the inventory I thought I'd mention it anyway:

When storing an item in a chest, the SLP appear on Egil, although they should of course remain invisible (as he isn't a caster)
![image](https://user-images.githubusercontent.com/88923192/131250467-babc0ad4-d4ce-4833-b46b-e8dd59897067.png)

![image](https://user-images.githubusercontent.com/88923192/131250498-b5b45fcb-e198-4bc6-842e-2debc67f53d4.png)

![image](https://user-images.githubusercontent.com/88923192/131250507-e7804aaf-138d-46da-ac87-8d8d2801d1a9.png)

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/7072487/Saves.zip)
Relevant save is Siran2, current version is Version 1.0.0 (27.08)

Storing food, storing gold, and transfering food create the same glitch in the ui.

**Comment by Pyrdacor** [comment]
It's totally fine to report this. I want to fix every detail even if it is no big issue. So thanks for that.

Now that 1.0 is released I will not release a new version for every bug fix but of course I will fix it and it will be available in version 1.1. But this version will take a bit longer as the daily updates for the pre-1.0 test release. Just in case you wonder.
