### ISSUE TITLE
When dismounting the eagle over water, the rest button remains disabled when leaving the water

### ISSUE THREAD

**Issue by Talmit** [Pyrdacor/Ambermoon.net#181]
When dismounting over water, the rest-button remains disabled when leaving the body of water.

![image](https://user-images.githubusercontent.com/88923192/131262587-60e5f8bf-d9e6-4bbf-aaba-0396a62176e9.png)

![image](https://user-images.githubusercontent.com/88923192/131262596-c5d007da-cab4-43c9-a40a-ce60010fc632.png)

![image](https://user-images.githubusercontent.com/88923192/131262607-6a9a05ad-4636-408c-9b49-3db8eb18601d.png)

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/7073086/Saves.zip)
(Ambermoon 1.0.0 27.08., relevant Save is Siran2)

The error occurs with regular bodies of water as well and is not specific to the water of life.

**Comment by Pyrdacor** [comment]
What's happening if you just go swim without the eagle? Is it disabled while swimming and re-enabled when going on land?

**Comment by Talmit** [comment]
Precisely. It's disabled when in water and re-enabled when going back on land.

**Comment by Pyrdacor** [comment]
So the bug basically is that resting isn't disabled in water. Thanks for clarification. I'll fix this the next days.
