### ISSUE TITLE
When moving around using the magic flying disc on the forest moon, the music is reset after being attacked

### ISSUE THREAD

**Issue by Talmit** [Pyrdacor/Ambermoon.net#183]
When moving around using the magic flying disc and entering and subsequently leaving combat, the music is reset to the default-wandering track instead of the track for the flying disc.

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/7084063/Saves.zip)
(Ambermoon 1.0.0, 27.08, relevant save is Siran2, the main character has the flying disc)

**Comment by Pyrdacor** [comment]
Thanks already fixed it in code. Will be part of 1.1.
