### ISSUE TITLE
When walking on a trap in S'Endars palace, a chest opens

### ISSUE THREAD

**Issue by Talmit** [Pyrdacor/Ambermoon.net#190]
This one seems kinda weird. When walking into one of the traps going up from the ground in S'Endars palace, a chest screen with a locked chest (containing Nav-Stones) appears after the surviors are determined.

![image](https://user-images.githubusercontent.com/88923192/131666107-0e6c4a52-a99b-401c-8fe9-d871d39a7a53.png)

![image](https://user-images.githubusercontent.com/88923192/131666164-a0788936-3626-4b46-ad1f-48a73329d034.png)

![image](https://user-images.githubusercontent.com/88923192/131666183-dab19439-e015-4dc2-a0f3-9fe996d79cd9.png)

[Save.07.zip](https://github.com/Pyrdacor/Ambermoon.net/files/7090791/Save.07.zip)
(Ambermoon 1.0.0 German)

**Comment by Pyrdacor** [comment]
Some others also reported this and after some research I found that this is a bug in the original game data.

@a1exh: Please add this to the bug list. This chest event is chained to the trap event of the spikes. The chest is also available as a real chest in a room nearby. The fix is simply to remove the chest event from the spike event chain.

**Comment by Pyrdacor** [comment]
Fixed. Will be part of the next releases.

**Comment by dlfrsilver** [comment]
@Pyrdacor : can you tell me which subfile has to be modified or updated please ? The information is missing from AlexH excel file, thank you :D

**Comment by Pyrdacor** [comment]
It is map file 1BF inside 2Map_data.amb.

**Comment by a1exh** [comment]
@dlfrsilver if you don't get an answer as quick as you would like. You can download the commit linked in the spreadsheet. And the previous commit of the same file. Unpack. Diff.

**Comment by dlfrsilver** [comment]
> It is map file 1BF inside 2Map_data.amb.

Thank you Robert :)

**Comment by dlfrsilver** [comment]
> @dlfrsilver if you don't get an answer as quick as you would like. You can download the commit linked in the spreadsheet. And the previous commit of the same file. Unpack. Diff.

There's no hurry, it's a hobby (i can also be not that quick to answer, i have my daughter to take care about and other things).

Just my 2cts :)
