### ISSUE TITLE
Error with a text panel in Burnville ?

### ISSUE THREAD

**Issue by skdubg** [Pyrdacor/Ambermoon.net#193]
hi,

i don't know if this is an error from remake or original game files.

at the text panels at the house of the healers in Burnville the text of the merchant from Burnville follows after the actual text.

But this should not be.
I have checked the text files again, it is not because of them, it also occurs in the English game.

![Unbenannt2](https://user-images.githubusercontent.com/8874416/131788989-68e23ef6-47d5-4de0-9228-d9e98cb37d93.jpg)
![Unbenannt3](https://user-images.githubusercontent.com/8874416/131789005-a357bcd2-62c2-4870-8253-839c6962cb98.jpg)

[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/7096402/Saves.zip)

**Comment by Pyrdacor** [comment]
Looks like a second text popup event is chained after the first one. So this is most likely a bug inside the map data. I don't think I changed the burnville map. Maybe someone can test this with 1.07 english or 1.01/1.05 german on Amiga/Emulator?

**Comment by Pyrdacor** [comment]
Nonetheless I have to fix this in 1.1 so we might get a new original game data release too. :)

**Comment by skdubg** [comment]
have tested it with German 1.01/1.05, but with the Remake.
messages are the same

**Comment by Pyrdacor** [comment]
Thanks then it is a bug in the original data. I will fix it soon.

**Comment by skdubg** [comment]
I really have found a 28 year old bug that no one has reported or knew about?
This is incredible 😄 

thanks for your efforts 👍

**Comment by Pyrdacor** [comment]
Afaik nobody before you reported it. But @a1exh would know better.

**Comment by Pyrdacor** [comment]
> I really have found a 28 year old bug that no one has reported or knew about?
> This is incredible 😄

Don't you fix German text bugs that are 28 years old the whole time since several days? 😝

**Comment by skdubg** [comment]
You're right about that, except that they don't necessarily have an effect on gameplay 🤣

**Comment by a1exh** [comment]
> But @a1exh would know better.

Nobody has ever reported this bug. 

The saves.zip in this bug-report includes 2-saves. Is it obvious which it is?

I'll try it in WinUAE with v1.07 

Perhaps it is one of those bugs that doesn't manifest itself on the Amiga?

**Comment by skdubg** [comment]
it's the first savegame inside the zip

**Comment by Pyrdacor** [comment]
I fixed this and the similar issue with the chest after the spike trap in palace of S'Endar. The events were just connected when they shouldn't be in both cases. ;)
