### ISSUE TITLE
missing Icewater at Luminor's Tower 2

### ISSUE THREAD

**Issue by skdubg** [Pyrdacor/Ambermoon.net#194]
hi,

in Luminor's Tower 2 is the Icewater missing

http://thethalionsource.w4f.eu/Artikel/AM_Walkthrough_17.png

![Unbenannt4](https://user-images.githubusercontent.com/8874416/131796578-89031b4f-2718-4c00-b261-655bf735f5fc.jpg)

[Save.zip](https://github.com/Pyrdacor/Ambermoon.net/files/7096713/Save.zip)

**Comment by fuckgithub42** [comment]
It isn't missing your walk-through is wrong.

**Comment by skdubg** [comment]
shame on me, oh no, you're right. thanks :D
one at third floor, two at fourth floor, one at fifth floor
