### ISSUE TITLE
1.0 Release on MACOSX opens windows with black canvas

### ISSUE THREAD

**Issue by spkrsmfx** [Pyrdacor/Ambermoon.net#195]
When running the 1.0 bundle and/or standalone release, it opens a window that remains black.
Nothing happens, no output to console.

**Comment by Pyrdacor** [comment]
Was a configuration file with the name "ambermoon.cfg" created? Did you try to start it from the command line (e.g. bash)?

**Comment by bboc** [comment]
I have the same issue, so I can add a few details

- MacOs 10.14.6
- bundled version (downloaded a couple of minutes ago)
- started from the command line
- a black window appears (title: Ambermoon.net v1.0.0)
- Activity Monitor says the app has 10 threads consumes 5-10% of my CPU (kept it running for 10 minutes and nothing changed)
- no sound output
- no config file in ~/.config (but .config exists and contains other config files already

**Comment by Pyrdacor** [comment]
Thanks for the information. This is hard to investigate. Can you try to install glfw via `brew install glfw`?

You can also try `brew install openal-soft`.

What is your graphic hardware and OS version?

**Comment by spkrsmfx** [comment]
Installing those dependencies and running the program dont change the situations.

**Comment by Pyrdacor** [comment]
Mojave (10.14) seems to have broken OpenGL support. Can you upgrade to a more recent version?

Can you also test if something is rendered when you move the window or hit F11?

**Comment by santiontanon** [comment]
I can confirm the 1.0 bundled version works fine on Mac OS 11.4 Big Sur with an M1 Macbook pro. So, it could be an OS version issue.

**Comment by Pyrdacor** [comment]
@spkrsmfx @bboc Can you try the things I mentioned in my last post or give and feedback regarding this? Otherwise I will close this until someone reports back.

**Comment by spkrsmfx** [comment]
I upgraded to Big Sur, and now it works. I had my issues on Catalina.

**Comment by Pyrdacor** [comment]
Great. So I close this now. If someone still has such issues, feel free to reopen this.
