### ISSUE TITLE
Wind Shrine bugs

### ISSUE THREAD

**Issue by ThalionFan** [Pyrdacor/Ambermoon.net#196]
Ran into a couple of bugs in the Wind Shrine - combining the Xenobil Staff and gem on the left altar gave the the message that they had fused into the Construction Staff, but while it did consume the components the staff didn't appear in my inventory. What was even stranger was when I tried to make the Wind Chain itself - I combined the mother-o-pearl chain and twelve windpearls on the right altar, got the message that I had reconstructed the Wind Chain, but what appeared in my inventory was Kay's Amulet, not the Wind Chain. I worked around this by getting the items from the hidden Thalion Offices in Spannenberg but thought I should report it. In any case, thanks for all your work into making the PC release - I think I must have played for at least twelve hours yesterday.

**Comment by Pyrdacor** [comment]
Thank you for reporting this. I will have a look into it as soon as I can . I am happy that you had some joyful hours with the remake. That's exactly why I made it. :)

**Comment by fuckgithub42** [comment]
Neither items are just added to your inventory but you have to pick them up from the altar via interacting with them.

When playing through the game I could obtain both items just fine.

**Comment by Pyrdacor** [comment]
True now I also remember. Thanks. You have to use the eye cursor on the altar afterwards to get the items. So this is no bug I guess.

**Comment by Pyrdacor** [comment]
@ThalionFan Can you re-check it please? Maybe you already had Kay's amulet in your inventory and missed to examine the altars after combining the items?

**Comment by ThalionFan** [comment]
Confirmed - I'm an idiot lol. I was convinced I had given Kay's Amulet back to Norel but apparently not. I went back and checked both altars and the items were there.

**Comment by Pyrdacor** [comment]
Don't worry. Just recently I noticed that I already found a reported bug a long time ago and was too blind to see it until now. :D
