### ISSUE TITLE
When recruiting Valdyn / Gryban, their right-hand slot is empty

### ISSUE THREAD

**Issue by Talmit** [Pyrdacor/Ambermoon.net#198]
When recruiting Valdyn or Gryban, their right hand slot is empty, although their weapon requires two hands:

![image](https://user-images.githubusercontent.com/88923192/132285384-e7cb2227-f733-44d9-8bb5-b53c269da042.png)

![image](https://user-images.githubusercontent.com/88923192/132285440-273d1473-fbd7-4591-b726-0c5e3a34ed6c.png)

[Save.03.zip](https://github.com/Pyrdacor/Ambermoon.net/files/7119166/Save.03.zip)
(Ambermoon 1.0.0, German)

**Comment by Pyrdacor** [comment]
Thanks. Already fixed in code. Will be part of 1.1.
