### ISSUE TITLE
Shield disappear when 2-hand weapons is equipped (in combat)

### ISSUE THREAD

**Issue by kovacm** [Pyrdacor/Ambermoon.net#200]
I was in fight with Orcs.
1. Thalion weapons disappeared after dozen of turns (this is normal right? When weapons broke it combat then it will disappear?)
2. Thalion still have shield in right hand
3. I equipped Two hand Battle Axe and shield in right hand disappeared!

**Comment by Pyrdacor** [comment]
Thanks This is a known bug that I already fixed. It will be part of the 1.1 patch update.

And yes it's correct that broken items disappear in battle. You can collect them after the battle.

**Comment by Pyrdacor** [comment]
It is related to #187 but not exactly the same thing. Nevertheless I fixed it already.
