### ISSUE TITLE
Handover of keys from Father Anthony

### ISSUE THREAD

**Issue by AndreasNick** [Pyrdacor/Ambermoon.net#208]
After the dungeon in the grandfather's house is completed, father wants to give Antonius the key for the chest of drawers. Unfortunately, this does not work because the dialog with Antonius ends immediately.

**Comment by Pyrdacor** [comment]
This is correct this way. He tells you that the key is on the table in your room. You should have a look there. ;)

**Comment by AndreasNick** [comment]
Oops! And thank you - also for the wonderful new conversion. I last played this gem almost 30 years ago :-)

**Comment by Pyrdacor** [comment]
You are very welcome. I hope you enjoy it. ;)
