### ISSUE TITLE
Issue with the snake helmet (values are wrong)

### ISSUE THREAD

**Issue by skdubg** [Pyrdacor/Ambermoon.net#228]
hi,

currently i use the snake helmet. This is cursed and should reduce the values accordingly, but they are added. look at the screenshots

weight without snake helmet
![Unbenannt](https://user-images.githubusercontent.com/8874416/137622464-16330c75-a5b8-4117-8c49-466fafea67c4.jpg)

weight with snake helmet (should be 85kg)
![Unbenannt2](https://user-images.githubusercontent.com/8874416/137622474-a65a82c5-c19d-495c-b208-be19fa797977.jpg)

the same happens with attack and SP-Max

**Comment by Pyrdacor** [comment]
Fixed in 1.3
