### ISSUE TITLE
[Feature request] Import Savegames

### ISSUE THREAD

**Issue by madelgijs** [Pyrdacor/Ambermoon.net#231]
Hello,

it's more of a question, but maybe a feature request, too. Is there any way I can import savegames from my old Amiga Savedisk into Abermoon.net?

Kind regards,

**Comment by madelgijs** [comment]
Well, I can answer my question myself. I just copied the savegames from the WHDLOAD-Version of Ambermoon into the saves-folder of Ambermoont.net and could easily load them afterwards. Great!

**Comment by Pyrdacor** [comment]
Sorry I am bit late. Great that you figured it out yourself. ;-) Ambermoon.net supports the original saves so it's possible to exchange the saves between Amiga and the remake. You can also use the remake saves in the original version.
