### ISSUE TITLE
[Bug report] Battle freezes when no Leader is available

### ISSUE THREAD

**Issue by iancrossfield** [Pyrdacor/Ambermoon.net#232]
**Describe the bug**
The game will freeze (and has to be force-quit and restarted) during certain battle situations. For example: some characters flee or are killed, and the remaining character is driven Mad or put to Sleep. Then the user is asked to "Select a New Leader," but the only remaining PC is Mad/Sleeping and cannot be selected.

**To Reproduce**
A bit tricky; but see the attached screenshot for an example: everyone but the main PC ("Elsie") has fled, and she was driven Mad:
![Screenshot from 2021-11-14 09-45-06](https://user-images.githubusercontent.com/8728644/141689066-21d0c0e1-b583-4439-a2ca-ff6b5959a022.png)

**Expected behavior**
The game should not freeze - battle should continue until the remaining PC is killed (if sleeping) or is killed or wins the battle (if Mad).

**Screenshots**
See attached screenshot, above.

**Desktop (please complete the following information):**
Ubuntu 20.04
Ambermoon.net v1.1.0
English version, 1.10

**Additional context**
Thanks for making such a great resource available!

**Comment by Pyrdacor** [comment]
In the original the game over screen is shown even if you are just asleep as the last member. I thought this is also correctly implemented in the remake. I already tested it. But maybe some circumstances are not handled correctly. I will have a look. Thanks for reporting.

**Comment by Pyrdacor** [comment]
I fixed it in code. Will be part of 1.3.

**Comment by Pyrdacor** [comment]
Fixed in 1.3
