### ISSUE TITLE
[Bug report] Tiles borders visible when Graphic Filter is turned off

### ISSUE THREAD

**Issue by cachaito** [Pyrdacor/Ambermoon.net#237]
First of all - I'm impressed with your work in this project! 
I noticed, that when I turn off Graphic Filter, on Full screen or in Window mode bright borders around tiles in main window are visible. When dialog box appears on top of those tiles marks, they are visible too around it edges.

**Screenshots**
![Screenshot_21-11-2021 19-00-56](https://user-images.githubusercontent.com/4311424/142774631-c2439b30-114f-40e4-81f8-3aed25153176.png)
![tiles](https://user-images.githubusercontent.com/4311424/142774796-e07fc1a0-7611-4164-b3e7-06c92ea62ae6.png)

**Desktop (please complete the following information):**
 - OS: Windows 7 64-bit
 - Version 1.2.2 & 1.3

**Comment by Pyrdacor** [comment]
Unfortunately I can't reproduce this on my end (also Win7 64 Bit). Looks like its caused by how the graphic hardware handles drawing. Is this Nvidia, Intel or AMD?

**Comment by cachaito** [comment]
> Is this Nvidia, Intel or AMD?

Actually it's GeForce 750 Ti with pretty old drivers: 460.89
I will try to update them today and give you an update.

**Comment by Pyrdacor** [comment]
> First of all - I'm impressed with your work in this project!

Thank you very much.
