### ISSUE TITLE
[Bug report] poison damage - bandit house

### ISSUE THREAD

**Issue by invisiblehsadow** [Pyrdacor/Ambermoon.net#240]
if you fly over the bandit house in superman mode, either some or all of them get poison damage

**Comment by Pyrdacor** [comment]
It seems like the tiles of the bandit house have the "auto-poison" flag set. Or I missinterpret it. Nevertheless it should not affect flying players. I fixed this. As non-flying players can't access those tiles, the auto-poison will never happen.

**Comment by Pyrdacor** [comment]
This is fixed in 1.4 for flying. But you are still poisoned on a horse etc sometimes around the bandit house. I don't know if this is a bug in the original tile data or by design.

**Comment by Pyrdacor** [comment]
Ok I think it is by design that the yellow flowers(?) around the bandits' hideout poison. I fixed some issues with that poison and leave the rest as it was.
