### ISSUE TITLE
[Bug report] problems with the light

### ISSUE THREAD

**Issue by invisiblehsadow** [Pyrdacor/Ambermoon.net#248]
sometimes there are problems with the light,
even around midday, the light radius is not maximized
when you saved and loaded again, the bug was automatically eliminated
![12](https://user-images.githubusercontent.com/95400798/144368417-c2b7b836-0e0d-422e-bad9-918106ec75f1.png)

**Comment by Pyrdacor** [comment]
I couldn't reproduce this yet. Do you have an idea when this happens?

**Comment by invisiblehsadow** [comment]
I guess it was a coincidence, I think I always edited something in the inventory and then left the inventory. otherwise I couldn't make out any concrete characteristics.

**Comment by Pyrdacor** [comment]
Thanks for the hint. Maybe I can reproduce it.

**Comment by Pyrdacor** [comment]
I adjusted some stuff with the light for the 1.8 release. Can't promise this issue is resolved but it might be. If you find this bug again with 1.8 or later, feel free to reopen this then.
