### ISSUE TITLE
[Bug report] problems with the music

### ISSUE THREAD

**Issue by invisiblehsadow** [Pyrdacor/Ambermoon.net#251]
I also had problems with the music, which was sometimes extremely distorted

especially heard at the end of the video 

https://user-images.githubusercontent.com/95400798/144369916-81129843-7a34-4f31-89f9-2cdda076ae9a.mp4

**Comment by Pyrdacor** [comment]
In 1.8.2 I reworked parts of the music playback. I don't know if this changes anything but please give it a try.

**Comment by Stutchen** [comment]
It looks like that fixed the problem. Thanks. :)

**Comment by Pyrdacor** [comment]
Let me know if this still is an issue.
