### ISSUE TITLE
[Bug report] Text stays in inventory

### ISSUE THREAD

**Issue by invisiblehsadow** [Pyrdacor/Ambermoon.net#252]
If you add objects to the inventory (left or right mouse button) and then do not want to hand them in, the text above will unfortunately continue to be displayed (although you have no longer selected the object).
![01](https://user-images.githubusercontent.com/95400798/144370130-3de127fb-9014-413c-9a7f-25fa0015151b.png)
![02](https://user-images.githubusercontent.com/95400798/144370133-8cac7bf6-e08b-471d-8510-ae8ec4967471.png)
![03](https://user-images.githubusercontent.com/95400798/144370135-5221be05-08ad-4010-8e4c-9a67c8343113.png)

**Comment by Pyrdacor** [comment]
How do you cancel the item dragging? If I put the item back to some slot, the text disappears. Right click also removes the text. So please tell me exactly what you do to make the text stay.

**Comment by invisiblehsadow** [comment]
I am 99% sure that I canceled this with the right mouse button

**Comment by Pyrdacor** [comment]
Did you test with version 1.3?

**Comment by invisiblehsadow** [comment]
yes

**Comment by Pyrdacor** [comment]
Did this happen again? With 1.4 so far?

**Comment by Pyrdacor** [comment]
Feel free to reopen if this still happens.
