### ISSUE TITLE
[Feature Request] don't show text for chests with changed content

### ISSUE THREAD

**Issue by invisiblehsadow** [Pyrdacor/Ambermoon.net#253]
this is not a special bug, as it was also included in the original: if you empty the chest with important objects and then open the chest again, the text is still displayed although the chest is empty.
![01](https://user-images.githubusercontent.com/95400798/144370417-22781b67-fe4e-4d7d-bd1a-c3aef80b17dc.png)
![02](https://user-images.githubusercontent.com/95400798/144370419-fee8a56d-f9eb-4ee3-b18f-8beb9a236e7c.png)

**Comment by Pyrdacor** [comment]
I can fix this in the remake but it will be hard to fix in original. If there would be texts that should be displayed for empty chests though, this would be bad. Things like "Ha, you found just an empty chest" come to mind. But I think there is no such thing in Ambermoon so I will change it.

**Comment by Pyrdacor** [comment]
I won't hide the text for empty chests only though because you can put in some item and the text would still appear and also would make no sense.

But I can just check if some things changed from the initial contents and then hide the text.
