### ISSUE TITLE
[Bug?] chris has a broken boots

### ISSUE THREAD

**Issue by invisiblehsadow** [Pyrdacor/Ambermoon.net#254]
another bug that already existed in the original: in thalion's office chris has a broken boot, that doesn't make any sense and you can easily repair it. It would be nice if it hadn't broken in the first place 
![00](https://user-images.githubusercontent.com/95400798/144370691-92fc3109-182d-41df-bc6b-bcc178d12999.png)

**Comment by a1exh** [comment]
I think we should ask Thalion if this is an important easter egg? Perhaps Chris Jungen actually did break his foot?

**Comment by Pyrdacor** [comment]
I asked Jurie on Twitter. Let's see. ;)

**Comment by Pyrdacor** [comment]
Ok Jurie confirmed it is most likely a bug. So I'll fix it.
