### ISSUE TITLE
ice water vs luminor

### ISSUE THREAD

**Issue by invisiblehsadow** [Pyrdacor/Ambermoon.net#256]
is there any indication of how much each individual ice water weakens luminor? or do you only weaken luminor if you really pour all 4 ice water into the device? I also find the fight at the time too difficult for ambermoon beginners. I would suggest that every ice water would weaken luminor e.g. in the attack values and life points.

**Comment by Pyrdacor** [comment]
Afaik there are 5 versions of the monster Luminor. Each with different max hitpoints. Dependent on the amount of used ice water a different monster is spawned. But this won't work if you already triggered the event and Luminor is already running around. Using ice water then will have no influence anymore. Maybe that's the problem?

**Comment by invisiblehsadow** [comment]
ah that makes sense, yes you are surely right because every time I was first at luminor and had cleared the chest ^^
