### ISSUE TITLE
[Change request] learning points - luminor

### ISSUE THREAD

**Issue by invisiblehsadow** [Pyrdacor/Ambermoon.net#258]
level 3 in luminors tower, there is a special at the bottom right where you can increase your learning points, in the original it was by chance, so you could save and invite and sometimes that was really a lot of learning points .... in ambermoon.net it seems always to be exactly 50 learning points, intention? 

level 3 in luminors turm, gibt es ganz rechts unten ein special wo man seine spruchlernpunkte erhöhen kann, im original war das per zufall, somit konnte man abspeichern und einladen und manchmal waren das echt viele spruchlernpunkte.... in ambermoon.net scheinen es immer genau 50 spruchlernpunkte zu sein, absicht?

**Comment by Pyrdacor** [comment]
Are you sure about this? The event data says 50 point increase.

**Comment by invisiblehsadow** [comment]
i loaded the game 5 times, each time it was always exactly 50 points

**Comment by Pyrdacor** [comment]
I mean are you sure that it was different in the original?

**Comment by invisiblehsadow** [comment]
100% sure

**Comment by Pyrdacor** [comment]
I will investigate this.

**Comment by Pyrdacor** [comment]
Ok it is indeed random. You get 1 to 50 learning points in the original. I will adjust it likewise. The remake granted the full 50 points always.

**Comment by Pyrdacor** [comment]
Actually I just missed to consider the random flag which is part of such events. I already store this but I failed to make the values random in those cases. This affected all events, even wishing wells etc. So thanks for that. I could now fix them all. ;)
