### ISSUE TITLE
[Feature Request] Cheat to unlock whole map

### ISSUE THREAD

**Issue by invisiblehsadow** [Pyrdacor/Ambermoon.net#259]
Suggestion for a further function in the cheat menu: it would be great if you could get the whole map revealed in the 3D worlds, so that when you open the map, everything is revealed possibly even with a mystical map as well 

vorschlag für eine weitere funktion im cheatmenü: toll wäre es wenn man noch die ganze karte aufgedeckt bekommen würde in den 3D welten, so das wenn man die karte öffnet, alles aufgedeckt ist eventuell sogar mit mystischer karte ebenfalls

**Comment by Pyrdacor** [comment]
Added a new cheat called "explore" which will explore the whole 3D map.
