### ISSUE TITLE
Floor and Ceiling have border pixels missing or have garbage pixels

### ISSUE THREAD

**Issue by Metibor** [Pyrdacor/Ambermoon.net#26]
In the 3D maps the floor and ceiling textures are missing a pixel or have garbage pixels on two of the borders.
I am pretty sure that this is another 0.5f problem (the color index is 0 or something else instead of the correct value because the index is read on the border of the pixel instead of the middle), but I was not able to tweak the shaders to get it working.

**Ceiling**
Missing pixels on the border with tilted camera
![grafik](https://user-images.githubusercontent.com/12674912/92406237-d0650c80-f137-11ea-9469-88c6b57d8530.png)

[Extracted graphic](https://github.com/Pyrdacor/Ambermoon/blob/master/Graphics/Floors/002.png) with the missing pixels of one square marked in red
![grafik](https://user-images.githubusercontent.com/12674912/92406669-e6bf9800-f138-11ea-9476-aab51b09f664.png)

**Floor**
Missing pixels and garbage pixels on the border with tilted camera
![grafik](https://user-images.githubusercontent.com/12674912/92406300-fbe7f700-f137-11ea-9cd4-114334e405fc.png)

[Extracted graphic](https://github.com/Pyrdacor/Ambermoon/blob/master/Graphics/Floors/016.png) with the missing pixels of one square marked in red and the garbage pixels marked in yellow (I flipped the image to have the same orientation)
![grafik](https://user-images.githubusercontent.com/12674912/92408059-b24ddb00-f13c-11ea-98da-ab855a14bb73.png)

Ignore the palettes, it seems to be off in the extracted images the 3d palette is fine.

According to your screenshots I don't think it is just me again with my AMD gpu. ;-)

**Comment by Metibor** [comment]
Interesting: The yellow marked pixels on the floor texture seem to be the missing part from the ceiling (it is just flipped because of the perspective)!

**Comment by Pyrdacor** [comment]
They are in the same texture atlas. I guess the texture offset is 1 pixel off. Try to adjust it in the shader by 0.5f. Maybe it helps. Floor and ceiling use a texture repeat logic. I guess there is something wrong.

**Comment by Pyrdacor** [comment]
I'm not on any PC right now but try to change the 2 comparisons in the textured fragment shader which test against the tex end cord to greater-equal instead of greater. Maybe that is enough.

**Comment by Pyrdacor** [comment]
Closed by #27
