### ISSUE TITLE
[Feature Request] lower text speed in fast battle mode

### ISSUE THREAD

**Issue by invisiblehsadow** [Pyrdacor/Ambermoon.net#261]
an adjustment of the text speed in the battle would be great
(example as with albion) in ambermoon.net the scrolling speed is very high, which results in a super brisk game flow, but for beginners of the game the combat texts will certainly be too fast and you will hardly be able to read them.

possibility as an alternative:
It might also be possible that the text pauses when an object is broken, so you don't necessarily have to constantly follow the text like crazy at the beginning of the game (where you can't repair it yet) to find out whether a weapon has broken (what to invite would lead) or would not have to constantly look in the inventory to see whether something was broken. you could lean back and know that the display text would pause in the fight anyway if a weapon broke. but that's just a thought by the way 

eine anpassung der textgeschwindigkeit im kamp wäre großartig
(beispiel wie bei albion) in ambermoon.net ist die scrollgeschwindigkeit sehr hoch, dadurch ein ensteht ein super flotter spielfluß, jedoch für anfägner des spiels werden die kampftexte sicherlich zu schnell sein und sie werden sie kaum lesen können.

möglichkeit als alternative:
eventuell wäre es ja auch möglich das der text pausiert wenn ein gegenstand zerbrochen ist, somit muss man nicht zwangläufig ständig wie verrückt am anfang des spiels (wo man noch nicht reperariren kann) den text verfolgen um herauszufinden ob eine waffe zerbrochen ist (was zum einladen führen würde) oder müsste nicht ständig im inventar suchen ob was zerbrochen wurde. man könnte sich zurück lehnen und wissen das der anzeigetext im kamp eh pausieren würde wenn eine waffe zerbrochen ist. aber das nur ein gedanke nebenbei

**Comment by Pyrdacor** [comment]
The text will now be shown a bit longer (1 second) and important texts like broken equipment will be shown for 3 seconds.
