### ISSUE TITLE
[Feature request] music mp3?

### ISSUE THREAD

**Issue by invisiblehsadow** [Pyrdacor/Ambermoon.net#263]
I hope not that I will post this twice and that it has not already been discussed:
it would be great if you could play the music via mp3 or .ogg files. this would be in a folder in ambermoon.net. this would have two advantages:
1: there would be no mentioned problems with the music (see above)
2: you could easily integrate other music into ambermoon

**Comment by Pyrdacor** [comment]
Alex suggested to allow the Atari music to be used here: #110. I decided to add a general music Interface to allow different inputs like Atari, mp3, etc. So you might even use your own music, the new Ambermoon remixes, etc.

But some problems occured with the Atari formats, so I put it on hold for now and wait for @a1exh for news regarding this.
