### ISSUE TITLE
[Bug report] windows overlapped

### ISSUE THREAD

**Issue by invisiblehsadow** [Pyrdacor/Ambermoon.net#267]
the windows overlapped and i couldn't close the item window
also only happened once in the game and I believe that it was not because of the robe of valdy but a random bug because it was not reproducible: 

![01](https://user-images.githubusercontent.com/95400798/144374186-5ff54266-f9fc-42d5-b548-6776fb82a39a.png)
![02](https://user-images.githubusercontent.com/95400798/144374188-a5f50bbf-2814-4119-bf17-27ec2f0a1e0b.png)

**Comment by Pyrdacor** [comment]
Maybe when clicking the item view button while already dragging an item? Will have a look at it for 1.5.

**Comment by krater** [comment]
I had one time a similaer problem but didn't documented it. Looked like a race condition because it was during I was using the GUI relatively fast. Maybee clicking a button during the fade in.

**Comment by Pyrdacor** [comment]
There have been quite a lot of changes in so many places that this might be fixed already. Feel free to reopen this if it occurs again.
