### ISSUE TITLE
[Change request] magic flying disc is broken

### ISSUE THREAD

**Issue by invisiblehsadow** [Pyrdacor/Ambermoon.net#270]
in thalion's office the magic flying disc is broken and it has to be repaired first, but since thalion's office is something like cheating, i find it a bit strange when there are broken objects lying around 
![00](https://user-images.githubusercontent.com/95400798/144374896-f57aa4e0-42b2-4053-89a5-4757b1ce24eb.png)

**Comment by Pyrdacor** [comment]
@a1exh: Change byte 0x33 in sub-file 125 in Chest_data.amb from 0x02 to 0x00.

**Comment by a1exh** [comment]
Ambermoon Data (fixed) bugs spreadsheet updated.
