### ISSUE TITLE
[Bug report] not attacked

### ISSUE THREAD

**Issue by invisiblehsadow** [Pyrdacor/Ambermoon.net#273]
In the ruin tower it can happen that you are not attacked, although you are moving right in front of the monsters. saving and loading eliminates the bug. 
![Screenshot_01-12-2021 18-12-34](https://user-images.githubusercontent.com/95400798/144376217-207ede21-1e82-4cc8-ad4f-de6135fb7d40.png)
![Screenshot_01-12-2021 18-12-35](https://user-images.githubusercontent.com/95400798/144376221-44c306f0-2f8b-4cd6-b9f4-c23d7bd2c489.png)
![Screenshot_01-12-2021 18-12-37](https://user-images.githubusercontent.com/95400798/144376223-88e683ef-3999-400e-9979-f70d31b67e0c.png)

**Comment by Pyrdacor** [comment]
We had something similar a while back. To avoid multiple attacks at the same time I memorize if the player is already interacting with a monster. This should be reset after the fight so other monsters can attack again. But there might be a rare case where this still can happen. Did you flee a fight or killed a monster group before on the map?

**Comment by invisiblehsadow** [comment]
I didn't flee 100%. Unfortunately, I can no longer say exactly whether I had fought before

**Comment by Pyrdacor** [comment]
I added some changes that hopefully avoid that. I think we should leave this open for a while and check if it happens in the future.

**Comment by Pyrdacor** [comment]
As no further reports occured for some time I will close this now. If anybody stumbles onto this again, feel free to reopen this or create a new issue.
