### ISSUE TITLE
more experience points

### ISSUE THREAD

**Issue by invisiblehsadow** [Pyrdacor/Ambermoon.net#274]
i find the experience points per fight with many of the monsters on the forest moon extremely annoying and i'm not the only one. certainly it was deliberately wanted by the developers that one is even more annoyed by the insects, but personally i find at least an increase in experience points per fight very desirable
![Screenshot_01-12-2021 17-52-08](https://user-images.githubusercontent.com/95400798/144376440-04839a83-9c75-4205-b3ac-59e458a23104.png)

**Comment by Pyrdacor** [comment]
I also think that is wanted. You should walk carefully on the moon's surface and avoid those insects. And you should listen to the people and carry the mushrooms etc with you. I think Erik Simon planned it exactly that way. You should not fight or grind those monsters. The whole moon is full of them and they won't vanish. So you can level there unlimited if they gave reasonable exp.
