### ISSUE TITLE
[Bug report] female tornack too big

### ISSUE THREAD

**Issue by invisiblehsadow** [Pyrdacor/Ambermoon.net#275]
the female tornack is calibrated so large that it floats through the ceiling 
![Screenshot_01-12-2021 18-01-41](https://user-images.githubusercontent.com/95400798/144376616-f03d9420-db16-4073-87a5-02b9c8cdac33.png)
![Screenshot_01-12-2021 18-01-42](https://user-images.githubusercontent.com/95400798/144376619-2bd64f8a-5196-43b5-8dde-f0b59a35a404.png)

**Comment by Pyrdacor** [comment]
The Tornak is also too big in the original but the original renders the ceiling first so it always stays in the back of the objects. My engine used real depth testing and so the head was stuck in the ceiling. I now render the ceiling behind everything else as well and so it looks like in the original.
