### ISSUE TITLE
[Bug report] 0 experience point

### ISSUE THREAD

**Issue by invisiblehsadow** [Pyrdacor/Ambermoon.net#276]
When fighting with the female Tornack in the mine, you get 0 experience points, and the female Tornack is also too big.
in addition, after the fight you can still see the tornack female bos you closed the text message. (see the screenshot) 

![Screenshot_01-12-2021 18-59-20](https://user-images.githubusercontent.com/95400798/144376852-ade5d92f-93d0-4ade-b038-b170285969bb.png)
![Screenshot_01-12-2021 18-59-23](https://user-images.githubusercontent.com/95400798/144376859-055332d4-59bf-4889-a8cc-7d78c5bcfe1e.png)
![Screenshot_01-12-2021 18-59-48](https://user-images.githubusercontent.com/95400798/144376861-71d8240d-ed34-4ed7-b15a-fdb74f4fc175.png)

**Comment by Pyrdacor** [comment]
The fact that the monster stays after defeat is not fixable. But I fixed the size already and now the female Tornak will grant 650 Exp.
