### ISSUE TITLE
colour Dorinia's cave

### ISSUE THREAD

**Issue by invisiblehsadow** [Pyrdacor/Ambermoon.net#277]
The "bug" already existed in the original: I think the black frame has a purple tinge in Dorinia's cave, which is somehow a bit tiring for the eyes, below: to compare the normal color of the picture frame: 

den "bug" gab es auch schon im original: ich finde der schwarze rahmen hat einen lila stich in dorinias höhle, was irgendwie etwas anstregend für die augen ist, unten: zum vergleich der normale farbton beim bildrahmen:

![Screenshot_01-12-2021 18-21-26](https://user-images.githubusercontent.com/95400798/144377339-535f5f1f-986e-4e5a-8f0d-93ebb8eb7ffc.png)
![Screenshot_01-12-2021 18-21-38](https://user-images.githubusercontent.com/95400798/144377345-82af30a8-2e09-4532-96ba-e448e50fa206.png)
![Screenshot_01-12-2021 18-58-08](https://user-images.githubusercontent.com/95400798/144377347-5da37dff-5393-4cb8-9982-964d90611357.png)

**Comment by Pyrdacor** [comment]
This is no bug imo. The UI uses the last 8 colors of the current map's palette. The palette in Dorina's cave explicitly uses these colors. I think this is on purpose.
