### ISSUE TITLE
[Bug report] cannot pick up any amber chunks

### ISSUE THREAD

**Issue by invisiblehsadow** [Pyrdacor/Ambermoon.net#278]
in the mine on the forest moon you cannot pick up any amber chunks from the ground. they are shown on the map, but even vady (looking for treasures at value 95) cannot record them. no matter whether you walk over it or press examine. There are several places in the mines where pieces of amber lie on the ground and this bug is everywhere. 
![Screenshot_01-12-2021 18-58-20](https://user-images.githubusercontent.com/95400798/144377685-0d2199f8-0a07-4faf-9274-6352def0157e.png)
![Screenshot_01-12-2021 18-58-22](https://user-images.githubusercontent.com/95400798/144377688-3cbfc14d-dc95-4dde-83a7-c6fad2ec3240.png)
![Screenshot_01-12-2021 19-01-53](https://user-images.githubusercontent.com/95400798/144377689-3c69fc4f-64ec-4041-aa3c-cc743d38167d.png)

**Comment by Pyrdacor** [comment]
Hm I can pick the amber up without problems by using the eye cursor.

**Comment by invisiblehsadow** [comment]
the only thing I did "special" was to use the noclip function beforehand to get to the important points, maybe that has an influence? if not, it was a coincidence. after you have ended the gadlons you have to run up through the mines again, there was the bug again.

**Comment by Pyrdacor** [comment]
Can you please test the following:
- Start a brand new game
- Teleport to Mine at 20, 14
- Try to pick up the amber

**Comment by invisiblehsadow** [comment]
it works :) 
![Screenshot_08-12-2021 07-39-27](https://user-images.githubusercontent.com/95400798/145160960-c502629b-a1d1-4d42-ba09-9cc517db6821.png)
![Screenshot_08-12-2021 07-39-53](https://user-images.githubusercontent.com/95400798/145160967-d79c620e-f114-445b-8ad7-6f4c6b3c5f03.png)
t

**Comment by Pyrdacor** [comment]
I guess your savegame got somehow corrupted.

**Comment by iancrossfield** [comment]
Though this Issue was closed, I can reproduce it in my game. I could post screenshots but they would be exactly the same as those of @invisiblehsadow above (except mine are in English). None of my 6 characters can pick up the amber chunks in the Mine location shown above -- whether by walking over the chunk, or clicking the eyeball or hand buttons.  The same behavior occurs in both Ambermoon.net Version 1.1 (where I've been playing) and Version 1.3 (I copied the save-game directory into a new download) -- both games were run under Linux. 

@Pyrdacor , I don't know how to teleport (per your advice above, to "Teleport to Mine at 20, 14") so I'm not sure how to test this or otherwise make headway... Any suggestions? or should I just wait until v1.4 ?

**Comment by Pyrdacor** [comment]
The issue seemed to be related to the savegame. I guess it was broken in an older Ambermoon release somehow. It worked for @invisiblehsadow  with a fresh new game.

If you send me your savegame I can check if it is broken.

The teleport cheat can be used from the console. But before 1.4, this will only work if you won't start the game from a terminal/bash/shell. Then there should be an additional console window (at least on Windows, I can only hope that it only is shown in Linux). If you then enable cheats in the options, you can use the teleport cheat inside that console window. In 1.4 you will be able to do this in the terminal as well if you started the game from there. 1.4 will be there in a very short time. Very short. :D

**Comment by iancrossfield** [comment]
Yes, I still can't pick up the Amber bits even in v1.4.  The cheat console does work 
at the Linux command line, and I can successfully give myself Amber chunks 
'manually' with that.

Just in case you wanted to look at them, my Saves directory is attached.
[Saves.tar.gz](https://github.com/Pyrdacor/Ambermoon.net/files/7799791/Saves.tar.gz)

Looking forward to finishing the game (though I came to the Green Jewel way too underpowered!).  Thanks as always.

**Comment by Pyrdacor** [comment]
Thanks. I will look at the save soon. If you have time for it, maybe you can start a new game, teleport (with cheat) to the spot with the amber and try to pick it up then.

You can use `maps Mine` to see the map index. Then use `teleport <mapid> 20 14`.

**Comment by Pyrdacor** [comment]
I had a bit time to investigate this and finally found the cause. In Ambermoon chest content is stored in Chest_data.amb. The Amber pieces are chests as well. A chest with one item. For normal chests where you can also store stuff, each real ingame chest has one data chest in Chest_data.amb. But for single item pickups like the Amber the data entry in Chest_data.amb is re-used multiple time. Each piece of Amber shares the chest data. But in general when you change the content of a chest by removing or adding items, the chest data is changed accordingly. This was the same for the Amber. So when you picked up an Amber anywhere, the associated chest data was emptied. And when you approach another Amber, as the chest is "empty", it won't show anything and not even open the loot window.

I changed that. When you empty a pickup chest, it refills the chest data to the initial state. So the next Amber "chest" will contain an Amber again.

I tested it. Without the change after the first pickup, all other Amber pieces can't be picked up. But now as I fixed it, it works. Unfortunately this won't repair savegames that are already affected as the chest data is empty there already.

The fix will be part of the upcoming 1.5.2 patch release.
