### ISSUE TITLE
[Bug report] graphic errors on the morag

### ISSUE THREAD

**Issue by invisiblehsadow** [Pyrdacor/Ambermoon.net#280]
There were graphic errors on the morag with the given coordinates, even when saving and loading this was not eliminated
![Screenshot_02-12-2021 19-43-33](https://user-images.githubusercontent.com/95400798/144492470-eda84710-e7fd-4185-9e4e-8c5e0143360b.png)
![Screenshot_02-12-2021 19-43-37](https://user-images.githubusercontent.com/95400798/144492473-fa1dbf76-25ec-411a-870a-b643358e705e.png)

**Comment by Pyrdacor** [comment]
This bug is already present in the original. I'll have to edit the map and hope I can fix it this way.

**Comment by Pyrdacor** [comment]
I edited to map. It now looks like this. Had to trick a bit with the bushes.

![grafik](https://user-images.githubusercontent.com/8607784/145643568-ecd21d7d-8154-4c62-b4b9-db83c411d67b.png)

**Comment by Pyrdacor** [comment]
Not perfect but the tiles are very limited.

**Comment by macce2** [comment]
How about the location X:100 ; Y:95.
