### ISSUE TITLE
[Bug report] Can't enter Kire's treasure chamber

### ISSUE THREAD

**Issue by iancrossfield** [Pyrdacor/Ambermoon.net#282]
**Describe the bug**
After completing the Kire & Dorina quest, I am given "Kire's Key" to open his treasure chamber. Using it on the locked door gives the message "[yourname] has opened the door" -- but immediately after that the game returns to the map with the player still outside the locked door. Moving toward the door just brings up the 'locked door' screen again.

**To Reproduce**
See above.

**Expected behavior**
After using the key on the door, I should be able to enter the treasure chamber (at least, I presume so!).

**Desktop (please complete the following information):**
 - Ubuntu 20.04
 - Ambermoon.net v1.1.0

**Comment by iancrossfield** [comment]
Sorry, I see this is a duplicate of Issue #271 .

**Comment by Pyrdacor** [comment]
I will put this on high prio so that it is fixed in 1.4.

**Comment by Pyrdacor** [comment]
I fixed it in code already. Will be part of 1.4. Tracked here: #271
