### ISSUE TITLE
[Bug report] Ambermoon 1.4 needs external libglfw.so.3 on Linux

### ISSUE THREAD

**Issue by cbrueffer** [Pyrdacor/Ambermoon.net#284]
**Describe the bug**
With the Ambermoon.net 1.4 Linux tarball, running the Ambermoon.net binary results in the following:

```
$ ./Ambermoon.net 
Couldn't find a suitable window platform. https://docs.ultz.co.uk/silk.net/windowing/troubleshooting.html
   at Silk.NET.Windowing.Window.GetView(Nullable`1 options)
   at Ambermoon.GameWindow.Run(Configuration configuration)
   at Ambermoon.Program.Main()
```

I needed to compile a custom libglfw.so.3 and place it in the program directory to make it work, while Ambermoon.net 1.3 worked out of the box.

**To Reproduce**
1. Download https://github.com/Pyrdacor/Ambermoon.net/raw/master/Downloads/1.4/Ambermoon.net-Linux.tar.gz
2. Unpack
3. ./Ambermoon.net

**Expected behavior**
Ambermoon.net works out of the box.

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu 18.04.6 LTS)
 - Version Ambermoon.net 1.4

**Comment by Pyrdacor** [comment]
Thanks for the report. I will try to fix this in the new year asap. I guess it is related to the new NET6 single file executables.

**Comment by Pyrdacor** [comment]
Can you please test this updated version without copying the so file in there: https://github.com/Pyrdacor/Ambermoon.net/releases/download/v1.4.0/Ambermoon.net-Linux.tar.gz

**Comment by cbrueffer** [comment]
Works, thanks! The tarball only contained the binary FYI (I assume that was on purpose?).

**Comment by Pyrdacor** [comment]
Yes was for testing. I would only pack the other stuff in there if I'm sure it works. ;) Will update the real releases soon.

**Comment by Pyrdacor** [comment]
Thanks for testing.

**Comment by iancrossfield** [comment]
I get the same error message as listed above, even when I try downloading the newer, linked tarball above.  This is v1.4, and I'm running Ubuntu 20.04 LTS.  Thanks for the New-Years treat; looking forward to trying it out soon.

**Comment by Pyrdacor** [comment]
I just updated the 1.4 release. Please download again and try it out. Feel free to re-open this issue if it still doesn't work for you.

**Comment by seaben** [comment]
I have the exact same error with Ambermoon.net 1.10.0 on Ubuntu 20.4 with libsdl2. Then I tried Ambermoon.net 1.9.10 and it works fine on the same system. I hope this helps. (I love your projects, btw.)
