### ISSUE TITLE
Can lockup yourself in Neras House

### ISSUE THREAD

**Issue by praschl** [Pyrdacor/Ambermoon.net#288]
Playing Ambermoon Advanced 0.01 in German on Windows:

I entered Neras cellar and touched the wall (as the cat told me to).
Once I killed all the gargoyles, I talked to the riddlemouth, gave him the correct answer, and it dissappeared, BUT: then I moved back into the room where I got teleported to, and a wall came down, and I cannot remove it - I guess, when the riddlemouth disappears, the trigger for the wall should be removed.

This project is amazing work. Thank you very much :-)

**Comment by Pyrdacor** [comment]
Normally you would take either the riddlemouth or the secret wall to get to Nera. The riddlemouth wall always comes down after you passed it into the main room with the kettle. And so, as you found out, you can reopen it. ;)
