### ISSUE TITLE
[Bug report] Advanced: "Error creating game: The given key '9' was not present"

### ISSUE THREAD

**Issue by iancrossfield** [Pyrdacor/Ambermoon.net#291]
**Describe the bug**
When starting a new instance of Ambermoon.net from the Linux terminal and selecting "Advanced English (0.01)", then "Continue," the program immediately crashes with the terminal messages:

> Error while preparing game: The given key '9' was not present in the dictionary.
> Error creating game: The given key '9' was not present in the dictionary.

HOWEVER: there is a repeatable workaround:

- I start a fresh instance of Ambermoon.net, select the normal (non-advanced) English version, I can continue or start a game normally
- Then I quit
- When I then start Ambermoon.net a second time, I can select "Advanced English v0.01" and continue my game as before.

It's very strange, but highly repeatable.

**To Reproduce**
1. start a new instance of Ambermoon.net from the LInux terminal
2.  selecting "Advanced English (0.01)", 
3. select "Continue" 
4. the program immediately crashes with the terminal messages listed above.

**Expected behavior**
The program should not crash! :)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Ambermoon.net 1.4
 - Ambermoon Advanced v0.01
 
**Additional context**
Thanks as always for all you do!

**Comment by Pyrdacor** [comment]
I just tested with 1.4.1 on Ubuntu and can't reproduce this.

The strange thing is that you even have the "Continue" option in the first place. A fresh new installation should not have an existing savegame and therefore no "Continue" option. Maybe this is some special case where you have some older savegame inside your folder?

Maybe you could try with 1.4.1 and check if this happens there too.

**Comment by Pyrdacor** [comment]
Ok I could reproduce it. The problem is that you can click on the area where the "Continue" would be, even though it isn't there.

**Comment by Pyrdacor** [comment]
In 1.5 the continue option can't be clicked any longer if there is no continue savegame.
