### ISSUE TITLE
[Bug report] Pelani does not give eagle-flute after receiving Sansri's blood

### ISSUE THREAD

**Issue by HptmKarotte** [Pyrdacor/Ambermoon.net#292]
**Describe the bug**
Chapter: Kill Sansri
To get the flute for the eagles from Pelani you have to kill Sansri and give her blood to Pelani. After that you will get the flute and a key for the treasure room.
In Ambermoon.net 1.4.0 I do not receive the flute - only the pipe.

**To Reproduce**
1. Kill Sansri
2. Go to Pelani's palace
3. Give blood to Pelani
4. Only key is retrieved, no flute

**Expected behavior**
Pelani should give flute and key, as he says in the text

**Screenshots**
Text from Pelani when receiving blood
![blood_sansri_text](https://user-images.githubusercontent.com/98125920/150421460-04c26c5f-7723-4034-8950-0581c9ea62eb.png)

Received item from Pelani
![blood_sansri_given](https://user-images.githubusercontent.com/98125920/150421518-8f885dc7-ea6c-4d22-8f89-719f69c0f9c5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Ambermoon original 1.11. Deutsch

**Comment by Pyrdacor** [comment]
Oh nice, a Discworld fan. :) Thanks for reporting. I will have a look at it soon.

**Comment by Pyrdacor** [comment]
Should be fixed in hotfix 1.4.1 which is now available for download.

**Comment by madelgijs** [comment]
Wow. That was really fast! Thank you so much!

**Comment by Pyrdacor** [comment]
This really broke the game so I decided to create a hotfix. Others reported similar things as well and they all had the same cause. ;)

**Comment by HptmKarotte** [comment]
Great! Thank you very much for the fast fix. :-)
You are really doing an amazing job!
