### ISSUE TITLE
[Bug?] Tolimar doesn't hand over a pickaxe

### ISSUE THREAD

**Issue by madelgijs** [Pyrdacor/Ambermoon.net#293]
I successfully retrieved the four golden horseshoes at the bandit's home and handed them over to Tolimar. But in exchange he only offers a shovel and a crowbar, but no pickaxe. Anything I missed? Or could this be a bug?
Any help would be thankfully appreciated.

**Comment by Pyrdacor** [comment]
Hi there. Yes this is a bug. Which version do you play?

**Comment by madelgijs** [comment]
Hi, thanks for the quick reply. I'm playing the most recent German version 1.4.0.

**Comment by iancrossfield** [comment]
I think I also noticed this, in the English Version of Ambermoon Advanced (v0.01).

**Comment by Pyrdacor** [comment]
Should now be fixed in 1.4.1 for any language and even the advanced version. 1.4.1 is now available for download.

**Comment by madelgijs** [comment]
Wow, really fast. Thanks!
