### ISSUE TITLE
[Feature request] Show info after quicksave

### ISSUE THREAD

**Issue by Pyrdacor** [Pyrdacor/Ambermoon.net#294]
Maybe just a simple text popup with a OK button.

**Comment by hubblec4** [comment]
Without the OK-button, only a small hint. That's totally enpugh.

An OK-Button needs a confirmtion click.

**Comment by Pyrdacor** [comment]
So it should be closed automatically after a brief moment instead?

**Comment by hubblec4** [comment]
Yes, one or two seconds is enough for reading.

**Comment by Pyrdacor** [comment]
Added. See #295.
