### ISSUE TITLE
[Feature request] Quick load

### ISSUE THREAD

**Issue by hubblec4** [Pyrdacor/Ambermoon.net#295]
I said on Discord CTRL+SHIFT+numbers, but maybe better ALT+numbers??

**Comment by Pyrdacor** [comment]
I think 3 keys are better as it would be painful to load accidentally.

**Comment by Pyrdacor** [comment]
I implemented it with CTRL+SHIFT+number. I also added brief info messages for quicksave and quickload. Will be part of the 1.5 release.

**Comment by hubblec4** [comment]
sounds great
