### ISSUE TITLE
[Feature request] External music interface

### ISSUE THREAD

**Issue by Pyrdacor** [Pyrdacor/Ambermoon.net#298]
I want to add an interface to enable using external music.

First the interface should be implemented with mp3s as the first usable format. The interface will be designed to support multiple formats easily.

- [x] Added general interface
- [x] Added mp3 support
- [x] Add support for non-Windows platforms
- [x] Stream music and lazy load instead of loading everything at startup

**Comment by a1exh** [comment]
How are you going to link the alternative files with the internal song numbering? 

Mandatory prefix "01-" "02-" the new filenames to map to internal song numbers?

A GUI so you can map any filename to any of the internal songs?

Do you have to replace every song? Or just one or two?

**Comment by a1exh** [comment]
I don't know anything about the internal structure of the music player in Ambermoon but other than song selection does the game have any other music player control? Does it always start songs from the beginning and loop? Can the game starts songs from an arbitrary time?

**Comment by a1exh** [comment]
FYI a fan recorded all the original Ambermoon direct from a real Amiga in the late 90s early 00s. I think they were in CDDA format. i.e. Stereo WAV @ 44.1KHz I have those files somewhere. Not really necessary as you wrote your cool native player but might be useful for debugging this?

**Comment by Pyrdacor** [comment]
> How are you going to link the alternative files with the internal song numbering?
> 
> Mandatory prefix "01-" "02-" the new filenames to map to internal song numbers?
> 
> A GUI so you can map any filename to any of the internal songs?
> 
> Do you have to replace every song? Or just one or two?

I haven't decided this yet. I guess it will be a specific sub-folder like "music" and maybe just "01.mp3" or "01.wav" etc. Maybe you can just specify the folder in the ambermoon.cfg or even a "format string" to match/map filenames.

**Comment by Pyrdacor** [comment]
> FYI a fan recorded all the original Ambermoon direct from a real Amiga in the late 90s early 00s. I think they were in CDDA format. i.e. Stereo WAV @ 44.1KHz I have those files somewhere. Not really necessary as you wrote your cool native player but might be useful for debugging this?

Sure, would be cool if you can provide them.

**Comment by Pyrdacor** [comment]
> I don't know anything about the internal structure of the music player in Ambermoon but other than song selection does the game have any other music player control? Does it always start songs from the beginning and loop? Can the game starts songs from an arbitrary time?

At least it shouldn't be hard to implement such control. Why are you asking?

**Comment by a1exh** [comment]
> Why are you asking?

If the game engine just starts a song at the beginning and plays it on loop (or once through) until a change of location triggers a different song then you can replace any song with any other song regardless of the length.  However if the Ambermoon music player can jump mid-way into songs, uses fixed time offsets etc. then that might be problematical.

I was thinking about replacing songs with the Atari Ambermoon music to begin with.

https://youtu.be/0-T43wOKacg

I can generate MP3s from the SNDH files that will be identical length and tempo to the Amiga originals.

Then I thought about the Matthias Steinwachs re-mixed Ambermoon songs. I'm not sure they are the same length / tempo as the originals?

https://soundcloud.com/audiotexturat/sets/soundtrack-ambermoon

**Comment by Pyrdacor** [comment]
I already implemented it. You can now just put mp3s in a folder called "music" next to the exe. Unfortunately only for Windows as of now. You can use any mp3 with any length. The only limitation is that it should have 1 or 2 channels and 8 or 16 bits per sample. The filenames must be 1.mp3 (or 01.mp3) and so on. It is used in place of the associated song with that ID. I can provide a list later if you need it. You can also provide only some mp3s and the rest is still used from the original music.

There is a new option called "External music". You can switch back to the original music this way.

But if you replace the files while the game is running, this won't update the songs as they are loaded on program start.

So you can use Matthias' songs or the Atari sounds as long as you have them as mp3. I might add other formats later and hopefully add an mp3 loader which is cross platform.

This already works on my end and will be part of 1.5.

**Comment by Pyrdacor** [comment]
@a1exh Could you please provide the Atari sounds as mp3s? I could add a download link for a zip with correctly named mp3s to enable it's usage in 1.5.

**Comment by a1exh** [comment]
Not in the short term. I can convert them but it is a very manual process. Will take about 2hrs. The most representative SNDH player I have found is to use WAV recording within the emulator "Hatari 2.3.1" and the Atari ST player "sndplay 1.51"

https://hatari.tuxfamily.org/download.html
http://sndplayer.atari.org/downloads.php

I've just noticed that there are only 18 songs in the Atari SNDH. I'll work out which are which and what the missing songs are.

**Comment by Pyrdacor** [comment]
Btw invisibleshadow already provided all the Atari songs in two versions and also the MIDI versions and the remakes of Matthias.

**Comment by Pyrdacor** [comment]
https://filehorst.de/d/etqgCgEe

**Comment by a1exh** [comment]
Did you work out which tracks were missing? There are 32 tracks in the Amiga version and only 18 tracks in the Atari SNDH file I was sent.

**Comment by a1exh** [comment]
Ah yes, there are only 13 of the 32 tracks in Atari format. Ah well. It is what it is.
