### ISSUE TITLE
[Bug report] No monster attack (Dorina's cave)

### ISSUE THREAD

**Issue by hubblec4** [Pyrdacor/Ambermoon.net#299]
**Describe the bug**
In Dorina's cave you can not attack the monsters, and the monster don't attack you.
After a reload it works.

**To Reproduce**
- not reproducible
- seems it occurs randomly

**Expected behavior**
monster can attack the party

**Screenshots**
---

**Desktop (please complete the following information):**
 - Win10

**Additional context**
---

**Comment by Pyrdacor** [comment]
I possibly have fixed it but I can't tell for sure as it only occurs rarely. Still I will consider this as "fixed" for now. If anyone encounters this again in 1.5, please let me know.
