### ISSUE TITLE
[Bug report]Dor KireDon Mine Level 2 - no Amber

### ISSUE THREAD

**Issue by hubblec4** [Pyrdacor/Ambermoon.net#300]
**Describe the bug**
In Dor KireDon's Mine Level 2, you can not take up the Amber.

**To Reproduce**
Go to the room with the Ambers on the ground.

**Expected behavior**
you can take up the Ambers

**Screenshots**
![A DorKireDon Mine2](https://user-images.githubusercontent.com/25957077/155906220-248f7e24-0774-4013-9c62-ad9030b8bf6c.JPG)

**Desktop (please complete the following information):**
Win7 64 bit

**Comment by a1exh** [comment]
This is a known issue #278. 

I think it is due to the corruption of the save game from changing Ambermoon.net versions.

Currently the only solution seems to be to cheat (give yourself the Amber with the cheat console) or start again.

**Comment by hubblec4** [comment]
Ok, then this issue can be closed.

**Comment by Pyrdacor** [comment]
Wait a sec. Is this from a fresh new game or did you use some older savegame?

**Comment by hubblec4** [comment]
No, it is my current game, fresh from scratch.

**Comment by Pyrdacor** [comment]
There was really an issue which will be fixed in 1.5.2.
