### ISSUE TITLE
[Bug report] Game freezes when enemies use fire spells and combat speed is +100%

### ISSUE THREAD

**Issue by sisch** [Pyrdacor/Ambermoon.net#306]
**Describe the bug**
I had the game freeze multiple times when an enemy (dragons, firegiant (not sure the translation is correct), luminor) would use fire spells. However, oddly not if the spell is the first spell in the whole combat. And this only happens on combat speed +100%. A workaround for me was reducing the combat speed.

**To Reproduce**
1. Set Combat speed to +100%
2. Find an enemy that casts a fire spell
3. Cast some spell (I used sleep or irritation) before the enemies turn
4. If the enemy casts fire spell, at the end of animation, the battle pauses and you need to close the app.

**Expected behavior**
Next person in battle should run their moves or control panel (bottom right) should return.

**Desktop:**
 - OS: Windows 10
 - Version app v1.5.1 game data v1.11 German

**Comment by sisch** [comment]
If it is of any help, I can try to reload an old save and record a video clip. Just let me know

**Comment by Pyrdacor** [comment]
Hi there. Sorry for the late answer. A video would be awesome as I couldn't reproduce this yet. What versions of the remake did you try?

**Comment by Pyrdacor** [comment]
Is this still happening with 1.6.4?

**Comment by sisch** [comment]
Video should be available as unlisted on [YouTube](https://youtu.be/KqTSJYGc9pY)

It is still happening in 1.6.4

If you need anything else recorded, let me know. It doesn't take too much effort.

PS: I wanted to set a debug breakpoint to provide some more detailed info, but I can't seem to run it after compilation in Rider. It is missing some File called AM2-CPU (not sure what that means, but maybe I'm using the wrong build config). If this is something easily fixed I could potentially document the state the game is in while the bug happens.

**Comment by Pyrdacor** [comment]
Thanks. The file AM2_CPU is part of the original game data files. Head over to https://GitHub.com/Pyrdacor/Ambermoon and download the English or German Amiga version (extracted files). They have all files you need. The exe must be next to AM2_CPU etc. There is also a config file (next to the exe or in ~/.config/Ambermoon) which is called ambermoon.cfg. In there you can specify a data path (folder where the AM2_CPU etc is located after extraction) and there is a boolean "UseDataPath" you have to activate. Those settings are good for testing. You can debug then. The version selector is skipped and you will immediately use the given data from that path.

If you have questions, just let me know.

Here in the repo there is a Configuration.md file which documents the config file as well.

**Comment by xenonmb** [comment]
Hi,

i seem to have the same problem, I am using the latest version 1.6.5, and playing original german. Let me know if you need a savefile or similar.

**Comment by Pyrdacor** [comment]
Sure a save game would be good. But in the past I couldn't reproduce it so I guess this is also dependent on other factors. I think this has something to do with timing so maybe the CPU plays a role in it.

**Comment by xenonmb** [comment]
I have uploaded my save folder here, the latest save has a fight against a fire dragon and giant in the room where the freeze happens, also there are two seperate saves before fire giant battles. https://we.tl/t-kownL0GrQI

For CPU i got an Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz   3.80 GHz running on Win11 64bit

**Comment by Pyrdacor** [comment]
Thanks. I will have a closer look at it tomorrow.

**Comment by xenonmb** [comment]
Just as a heads up, i just had the freeze happen in the fight against luminor at +90% combat speed. So it also seems to happen on lower speed, but much less frequently.

**Comment by Pyrdacor** [comment]
Yeah I think something finishes too early so that the "finished" notification of the spell is handled in a wrong way and the following action is not performed anymore. But it is hard to pin down.

**Comment by Pyrdacor** [comment]
Maybe I can't reproduce it because my PC is too slow. :D

**Comment by sisch** [comment]
I stared a bit into the code and it started staring back at me 👀

What I could find out so far:
- Removing the Burn ParticleAnimation (CombatGraphicIndex.SmallFlame)  makes the bug appear even on Standard speed (0)
- All timedEvents are emptied when it crashes, so it doesn't really freeze, it just gets stuck in a state where no new battletick is evaluated, but the round is also not marked as over yet.
- The game does not really crash, because the config is saved, when I close the game window, even if the game is stuck already.
- If I increase the small flame delays by factor 10 (so it takes around 2 seconds until the third mini flame appears) the hurt animation (scratches) starts earlier than the third mini flame. I couldn't find where the hurtAnimation is triggered though
- The only interaction I could find between what happens and the battle speed is Game.cs:4629 which calculates a Factor for scaling down delays. However arbitrarily increasing the delays to say at least 50 µs did not do anything. (at this point I was just trying to fuzz the bug out)
- While it looks like that in the video and in idk 7/10 tries, the problems does not lie in the change between row 4 and 3, I had occasions where half chars of row 3 is hurt before the freeze.
- Also I was suprised to see the finishActions of the SmallFlame to be empty lambdas (2x) and null (1x), but it is the case for other particleEffects as well, and I didn't find reported bugs on those.
- A battle with gargoyles did not yield any problems, and despite the target type (single versus battlefield) being different, the sequence of function calls seems comparable and here again the difference is the particle effect.

At this point I'm out of ideas, but had a great weekend code reading exercise (and if I may, I'd like to stress what an amazing project it is). Maybe any of the aforementioned point rings a bell or helps you find other possible sources quicker.

**Comment by Pyrdacor** [comment]
This sounds very promising. I know the code in detail so maybe I can find something. Will have a closer look tomorrow. Thanks for you efforts!

**Comment by Pyrdacor** [comment]
I had a quick look. Can you test something for me?

Go to the local function `PlayParticleEffect` inside the `MoveTo` method. There are two calls to `AddTimedEvent` and in their passed lambda another animation is added.

Can you move that lambda content to the previous `AddAnimation` call instead and delete the `AddTimedEvent` calls? Maybe this will fix it.

**Comment by Pyrdacor** [comment]
Sorry it's a bit difficult on my mobile phone. Something like this:

```cs
AddAnimation(combatGraphicIndex, frameCount, position, position - new Position(0, 6), Game.TicksPerSecond / 4, 1, 1, displayLayer, () =>
                {
                    position.X += 6;
                    position.Y += 6;
                    AddAnimation(combatGraphicIndex, frameCount, position, position - new Position(0, 6), Game.TicksPerSecond / 4, 1, 1, displayLayer, () =>
                {
                    position.X -= 12;
                    position.Y -= 4;
                    AddAnimation(combatGraphicIndex, frameCount, position, position - new Position(0, 6), Game.TicksPerSecond / 4, 1, 1, displayLayer);
                })})});
```

**Comment by sisch** [comment]
No worries I knew what you meant right away and yes chaining the animations this way makes it work (at least for the Luminor fight at +100% speed) 👍

**Comment by Pyrdacor** [comment]
Oh nice. I will provide a fix tomorrow then. If you want you can provide a PR and I will merge it tomorrow. Thanks for your help.

**Comment by sisch** [comment]
Sure, will do :)
I am so happy it works now :D

**Comment by Pyrdacor** [comment]
> Sure, will do :) I am so happy it works now :D

You have no idea how happy I am! This bugged me for quite some time now and as I couldn't reproduce it, it was really hard to find the cause.

As you might have seen I already had this in mind and increased the times for the `AddTimedEvent` calls a bit higher. The animations use ticks per second divided by 4 (so 250ms in theory) and I put a little extra on top for the timed events to ensure they fire later. Both times are scaled later. But as the ticks are very low, rounding and dividing might lead to edge cases where the event fires first, adds the second animation and then as the first Animation finished, it deletes/zeros the second animation as well.

But I don't know why I didn't just chain them in the first place. 🤔
