### ISSUE TITLE
[Bug report] Game becomes unresponsive when cancelling click-cursor with rightclick at blacksmith

### ISSUE THREAD

**Issue by xenonmb** [Pyrdacor/Ambermoon.net#307]
**Describe the bug**
When you backout of the blacksmiths "not enough money" message with a rightclick, most of the controls don't work anymore.

**To Reproduce**
1. Go to blacksmith in burnsville
2. choose an item to repair that you don't have enough money for
3. acknowledge the message with a rightclick

You can get control back if you open and close the map, options, or "talk to"

**Expected behavior**
Normal controls continue to work.

**Screenshots**
Right click here: https://imgur.com/zG41iwA

**Desktop (please complete the following information):**
 - OS: Win11
 - Ambermoon.net 1.6.5

**Comment by xenonmb** [comment]
just noticed it also happens in other menus, like at the shop when trying to sell items the merchant doesnt want.

**Comment by Pyrdacor** [comment]
Thanks. If you find more specific places where this is happening, please let me know.

**Comment by sisch** [comment]
I'm guessing a bit, but to me it seems to be happening, whenever you use an abort action (right click or escape) when captured inside an item selection and presented with a message.

Could reproduce at blacksmith and other merchants with:
- Repair on undamaged Item
- Buying an item that exceeds available gold
