### ISSUE TITLE
[Bug report] Oasis not triggered repeatedly; also drowning damage in nearby sand when loading a game..

### ISSUE THREAD

**Issue by kermitfrog** [Pyrdacor/Ambermoon.net#310]
**Describe the bug**
When visiting the Oasis to replenish LP & SP and Identify a Items, the Text popup and restoring powers are not triggered repeatedly. To trigger it again you have to walk away quite far (maybe 50 tiles?) and come back or save and load the game.
Waiting several hours does not help.

I also noticed that when saving on some of the tiles near the oasis (e.g. X 527, Y 102), loading a game will change the player icon to a swimming one and apply drowning damage to the party. This does not seem to happen on other beaches. I wonder if this is related.

**To Reproduce**
1. Go to Oasis
2. Enjoy the mystic healing powers
3. Cast spells
4. Move
5. Move some more
6. Be sad about not getting your SP back :(

**Expected behavior**
Moving to another water-edge-tile should re-trigger oasis-effect

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 1.6.6

**Comment by xenonmb** [comment]
I just encountered the swimming/drowning bug while saving and loading in front of Newlake. https://imgur.com/T3HtrXC

**Comment by xenonmb** [comment]
Save files here: https://we.tl/t-jxn4iuIlhq
Latest save is the one in question.

**Comment by Pyrdacor** [comment]
Both bugs should be fixed in 1.6.7 now.
