### ISSUE TITLE
[Bug report] Audio device can not be changed (Linux / Pulseaudio)

### ISSUE THREAD

**Issue by kermitfrog** [Pyrdacor/Ambermoon.net#311]
**Describe the bug**
Under normal circumstances, I can change the audio output device for every application by using the plasma applet or pavucontrol.
For Ambermoon, this does absolutely nothing

**To Reproduce**
1. Start Ambermoon.net
2. start pavucontrol (or other pulseaudio control program)
3. Go to Playback Tab
4. Change output device for Ambermoon.net to something else
5. Nothing changes, sound coming from same device

**Expected behavior**
I should be able to change output to a different device

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 1.6.6

**Additional context**
As playing sound on the default device works for me (for Ambermoon.net) and I normally don't need to change it, that bug might have always been there.. unnoticed..

**Comment by Pyrdacor** [comment]
This is no real bug. OpenAL is not capable of detecting device changes. So the current implementation uses the default output at the time the game is started and sticks to it for the whole time.

I think to detect device changes and react to them it would need some OS related code.

**Comment by kermitfrog** [comment]
Hm.. ok, then the correct way is fixing OpenAL first?

> I think to detect device changes and react to them it would need some OS related code.

Linux is in a kind of transition here (pulseaudio is getting replaced by pipewire on more and more distributions), so I'm not even sure which API to use for this.
However I'm not quite happy with the sound device management stuff and wanted to dig deeper into it, anyway. Maybe I can help with this then.. although "then" might not be before winter

**Comment by Pyrdacor** [comment]
Winter is quite far away. There are some OpenAL extensions. Maybe they can do what you had in mind. Cross-platform development sometimes is a burden. It's a shame dotnet won't provide any universal abstraction through the framework for audio at all.

**Comment by Pyrdacor** [comment]
Maybe you can come back to this at a later point in time. For now I will close this as I do not plan to add such OS dependent functionality in the near future.

**Comment by kermitfrog** [comment]
That's ok. It's a minor issue and I don't think I'll get this done this year (maybe in 2024).
