### ISSUE TITLE
[Feature request] Remember window position

### ISSUE THREAD

**Issue by kermitfrog** [Pyrdacor/Ambermoon.net#312]
**Is your feature request related to a problem? Please describe.**
I have a 3 Screen Setup, with resolutions of (left to right) 1024x1280, 1920x1200, 1024x1280
Ambermoon always starts at 0,0, which means one half of it is on the left screen and the other half on the middle one.

**Describe the solution you'd like**
Instead of moving it to the middle screen every time, I'd like it to remember the position when the window is closed.

**Describe alternatives you've considered**
Detecting the screens and letting me choose the one to use in the game options would be ok, too.

**Additional context**
A bit different, but related:
* Now that I think about it... why can't I just resize the window?
* Also, remembering the state of the window border would be nice..

* I could solve all this problem and the window border with KWin's settings if the window class text was stable, but I don't know of any way for non-KDE-users

**Comment by Pyrdacor** [comment]
I added it with latest commit. Will only be part of next major release I guess. But if you can compile it on your end I would be happy if you can test some usecases and see how it works.

Ctrl+Shift+C can be used to center the window on the main monitor.

**Comment by kermitfrog** [comment]
Yep, works (at least with KDE) :)

However, it should be noted that the `C` in `Ctrl+Shift+C` is `KEY_C` (meaning the key, where C would be on a qwerty-based layout), not `c` where it's on your current layout

**Comment by Pyrdacor** [comment]
Is the C key ever somewhere else?

**Comment by kermitfrog** [comment]
Have you really never heard of dvorak layouts?

In any case, with more than 100 different keyboard layouts (not even counting layout variants and custom modifications) and several hardware keyboard placement variants out there, one should never assume any key to be in the same position (or even any character to be reachable without a modifer) everywhere.

If you'd like a more in depth description of my take on input ergonomics (mostly relevant to #65), I hereby happily redirect you to a [post](https://steamcommunity.com/app/892970/discussions/2/5879990700797105749/) I wrote last year...
