### ISSUE TITLE
[Bug report] Ambermoon Advanced (1.6.8) start failed

### ISSUE THREAD

**Issue by skdubg** [Pyrdacor/Ambermoon.net#314]
**Describe the bug**
start of Ambermoon Advanced failed

**To Reproduce**
start Ambermoon Advanced

**Screenshots**
![grafik](https://user-images.githubusercontent.com/8874416/174591515-911c9d5e-8d71-4410-b4e5-8e78b527c6d0.png)

**Desktop (please complete the following information):**
 - OS: W11 22621.160

**Comment by Pyrdacor** [comment]
Thanks. Will work on a fix asap.

**Comment by skdubg** [comment]
thanks. its working again :)
