### ISSUE TITLE
[Bug report]: game window "over-scales" display on MacBook Pro (M1)

### ISSUE THREAD

**Issue by TheYoctoJester** [Pyrdacor/Ambermoon.net#315]
**Describe the bug**
The Application scales such that it requires more space than the laptop screen has. The window cannot be resized. To give a rough estimate, on the 14" MBP, when the Lyramion starting screen appears, the "QUIT" menu item is roughly at the lower border of the display.

**To Reproduce**
Start game on M1-based MacBook Pro

**Expected behavior**
Optimum: the window being resizable
Okay: the window at least fitting on the (only) available screen

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.4

**Comment by Pyrdacor** [comment]
So the width of the window fits the screen but the height overscales? What resolution is used?

Did you try another resolution in the option menu? What options are present?

**Comment by Pyrdacor** [comment]
Is fullscreen mode working?

**Comment by TheYoctoJester** [comment]
I am unable to find any options menu, so I cannot set anything related to resolution or fullscreen. According to Apple, the display is 3024x1964, and I'm running it on default settings. Side observation: This only happens on original, advanced immediately closes. Here's a screenshot to explain better:
<img width="1512" alt="Screenshot 2022-06-21 at 08 47 30" src="https://user-images.githubusercontent.com/67025528/174736458-259ebd32-c791-4a1c-b3b8-fa903cbea920.png">
:

**Comment by Pyrdacor** [comment]
After you started the game you have to right click the area in the bottom right with the arrow buttons. Then there will be a disk symbol button which is the option menu. You can also hit Enter/Return to toggle to those buttons.

**Comment by TheYoctoJester** [comment]
I can't reach the bottom right area at all, unfortunately.

**Comment by Pyrdacor** [comment]
The config is located inside the bundle so you have to use Ctrl+Click on the bundle and then "Inspect package" or something similar. There is a folder Contents and then MacOS. In there the config file should be located.

**Comment by TheYoctoJester** [comment]
Sorry for taking so long - work travels interfered. Changing the config file manually did the trick. Just a thought then: would it be good to set the defaults in a way they will "probably be okay for starting" on most machines? If so, want me to try and prepare a PR?

**Comment by Pyrdacor** [comment]
I would prefer to use something like 3/4 of the current (or main) screen at first start.

In addition at each start a check could be performed to check if the window is larger than the screen and shrink it if necessary.

If you could do a PR, this would be very helpful.

**Comment by Pyrdacor** [comment]
I can assist it you need some help or information about the code.
