### ISSUE TITLE
additional movement mappings on keyboard

### ISSUE THREAD

**Issue by nsklaus** [Pyrdacor/Ambermoon.net#319]
could you map strafe left and right to keys too ?
using wasd it's currently possible to move forward, backward and to rotate left or right. that is good but,
what is missing is ability to move laterally (i think it's called "strafing" in english).
lateral steps can be done with the mouse, but not with keyboard unfortunately.
you could use Q and E for those.  
so A and D would rotate as they already do, and Q and E would allow lateral moves.

**Comment by Pyrdacor** [comment]
Good idea. Will do.

**Comment by nsklaus** [comment]
nice :)

on a 2nd thought, i'd do rotate on Q and E and strafe on A and D.
but you decide. if these moves could be mapped on the keyboard that would already be nice.
whatever key you end up choosing for it.
