### ISSUE TITLE
[Bug report] 1.7.1 crashes on mac after version selection

### ISSUE THREAD

**Issue by export2file** [Pyrdacor/Ambermoon.net#327]
**Describe the bug**
After starting Ambermoon 1.7.1 I see the Pyrdacor intro, then the version selection (DE, EN, Advance etc). When clicking 'OK'  the program crashes to desktop. This happens with all 4 versions.

**System description**
Macbook Air 2020, M1, 8GB
MacOS Ventura 13.0.1
Ambermoon.net-Mac-ARM.zip

** Reproduction procedure **
- Download zip from Github
- unpack
- start Ambermoon.app (security popup appears)
- allow application in System Configuration -> Security
-  start Ambermoon.app again

I am not a regular Mac user, so I don't know how to gather debugging data. If you tell me where to look, I am happy to support.

**Comment by Pyrdacor** [comment]
I don't know Mac very well. I know it runs on the MacBook Air of my wife but a crash could be all kind of stuff.

Can you try to run the game from a terminal? It should print something to the terminal window if there is a problem.

**Comment by export2file** [comment]
Interesting.

I tested 2 scenarios:

Scenario 1:
right-click Ambermoon.app -> show content; locate app and drop to terminal
`<username>@<macbookname> ~ % /Users/<username>/Downloads/Ambermoon.net/Ambermoon.net.app/Contents/MacOS/Ambermoon.net `
--> DOES work

Scenario 2
directly start app from Terminal via
`<username>@<macbookname> Ambermoon.net % open ./Ambermoon.net.app `
--> does NOT work..   no debugging info in the terminal though :-/



also re-tested double-click of "Ambermoon.app".  -->  still crashes

**Comment by Pyrdacor** [comment]
Means "DOES WORK" that there is no crash anymore? If so it is most likely a file the game can't locate or read/write. Could be the config file or the folders for the savegames.

I would assume that the working scenario tries to create the stuff inside the MacOS folder where it has access rights and the non-working scenario tries to do so in the folder where the app is located. Maybe it has no access rights there?

**Comment by export2file** [comment]
an error that does keeps popping up in console if I try to start the app directly via double-click is the following one. It does not show up in console after the I start the codefile directly.

```
2022-11-16 09:41:21.732996 (pid/751/com.apple.speech.MacinTalkFramework.WardaSynthesizer.x86-64 [3293]) <Warning>: Could not find and/or execute program specified by service: 86: Bad CPU type in executable: /System/Library/PrivateFrameworks/MacinTalk.framework/Versions/A/PlugIns/WardaSynthesizer_x86_64.appex/Contents/MacOS/WardaSynthesizer_x86_64
2022-11-16 09:41:21.733014 (pid/751/com.apple.speech.MacinTalkFramework.WardaSynthesizer.x86-64 [3293]) <Error>: Service could not initialize: posix_spawn(/System/Library/PrivateFrameworks/MacinTalk.framework/Versions/A/PlugIns/WardaSynthesizer_x86_64.appex/Contents/MacOS/WardaSynthesizer_x86_64) EBADARCH, error 0x6f - Invalid or missing Program/ProgramArguments
2022-11-16 09:41:21.733023 (pid/751/com.apple.speech.MacinTalkFramework.WardaSynthesizer.x86-64 [3293]) <Error>: initialization failure: 22A400: xpcproxy + 20904 [957][B30CB606-420B-3CE0-A165-BD6E5BEB8E94]: 0x6f
2022-11-16 09:41:21.733029 (pid/751/com.apple.speech.MacinTalkFramework.WardaSynthesizer.x86-64 [3293]) <Notice>: Service setup event to handle failure and will not launch until it fires.
```

**Comment by export2file** [comment]
Yeah "does work" means: no crash. Thalion logo shows up, everything fine.

Not sure about the permissions: if I open any file within the .app and press CMD+I. I see that my user has read/write permissions. There is probably more sophisticated ways to review that, but I am a pretty novice Mac user. :-/

**Comment by Pyrdacor** [comment]
Unfortunately I am a novice Mac user as well and even more so when it comes to development for Mac. It's strange that it works when you execute the real exe manually so I guess it has either to do with some configuration or with accessing some file or folder. But from your error messages I can't think of anything specific.

**Comment by export2file** [comment]
I had another look at it. Seems you need to enable error logging in Console manually. 8-)

This post is a bit a shot in the dark, but maybe it spawns some ideas..


**Trail 1 "AVAudioPlayer"**

The error message I found in Console:
`AddInstanceForFactory: No factory registered for id <CFUUID 0x6000004c6320> F8BB1C28-BAE8-11D6-9C31-00039315CD46`

...leads me to this page, with the exact same error ID
[https://stackoverflow.com/questions/58360765/swift-5-1-error-plugin-addinstanceforfactory-no-factory-registered-for-id-c](url)

Maybe that has similarities with your code? They also mention that the audio output device could have issues.. well I have MacBook Audio and Headphone Output and switching does not make a difference.


**Trail 2 "Relative path"**

I tried to investigate what the actual different between double-click and console execution is and saw this:
[https://stackoverflow.com/questions/32594175/what-is-the-difference-between-launching-a-mac-os-x-app-via-the-finder-open-and](url)
...which stated "The major difference is the working folder. "

So I looked closer at the error message and actually this is the ONLY error in the Console, but it shows up in both scenarios

Start from Finder/Binary/Open
```
fehler	22:26:47.790661+0100	Ambermoon.net	AddInstanceForFactory: No factory registered for id <CFUUID 0x600001174e40> F8BB1C28-BAE8-11D6-9C31-00039315CD46
standard	

22:26:47.808104+0100	tccd	AUTHREQ_ATTRIBUTION: msgID=182.1430, attribution={accessing={TCCDProcess: identifier=com.pyrdacor.ambermoon.net, pid=6623, auid=501, euid=501, binary_path=/private/var/folders/zm/j8cv60xn32n495ngx_dc9l440000gn/T/AppTranslocation/FA5AC12C-7BCB-4247-B4B9-D86D3EE8C28A/d/Ambermoon.net.app/Contents/MacOS/Ambermoon.net}, requesting={TCCDProcess: identifier=com.apple.tccd, pid=148, auid=0, euid=0, binary_path=/System/Library/PrivateFrameworks/TCC.framework/Support/tccd}, },
standard	

22:26:47.813319+0100	tccd	AUTHREQ_SUBJECT: msgID=182.1430, subject=com.pyrdacor.ambermoon.net,
```

Start codefile from Terminal

```
fehler	22:30:43.909445+0100	Ambermoon.net	AddInstanceForFactory: No factory registered for id <CFUUID 0x6000002fcc80> F8BB1C28-BAE8-11D6-9C31-00039315CD46
standard	

22:30:43.928831+0100	tccd	AUTHREQ_ATTRIBUTION: msgID=182.1432, attribution={responsible={TCCDProcess: identifier=com.apple.Terminal, pid=2351, auid=501, euid=501, responsible_path=/System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal, binary_path=/System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal}, accessing={TCCDProcess: identifier=com.pyrdacor.ambermoon.net, pid=6650, auid=501, euid=501, binary_path=/Users/<username>/Downloads/Ambermoon.net/Ambermoon.net.app/Contents/MacOS/Ambermoon.net}, requesting={TCCDProcess: identifier=com.apple.tccd, pid=148, auid=0, euid=0, binary_path=/System/Library/PrivateFrameworks/TCC.framework/Support/tccd}, },
```
.. and  I saw a difference in the binary_path variable with the existing of the "AppTranslocation" string, which I googled and found this post. Seems this is used for "unsigned" applications to obfuscate the file path.

[https://forum.openframeworks.cc/t/possible-permissions-issue-with-downloaded-apps/26946](url)
These guys have issues loading external data, which is probably not the problem here, because I would assume that the required media files are within the binary (at least that's the only thing I downloaded). But it's relatively easy to test:  you just download the distributed binary as "untrusted application" to your Mac instead of testing directly from Xcode

That article is also linked to this one. And while I don't have the same error message as this guy, my test results are exactly the same (binary does fail, codefile execution from Terminal works), so maybe that could also give you an idea where to look
[https://andymakesgames.tumblr.com/post/161517690384/why-particle-mace-and-all-of-my-other-games-and](url)

**Comment by Pyrdacor** [comment]
There is still external data. Technically the app is just a folder with some files. Important is the file versions.dat. It contains all the versions (including the game data) you see it the version selector. But as you can see this, the file should be loaded. Other external files are the config and the savegames. Config loading takes place first so it also should work. If you select a version I think it will look for savegames and especially for the file "Saves" which stores the slot for the continue game option. So if I had to guess I would say it looks for the savegames at a place where it has no access.

When you start from terminal, is there some savegame folder created by any chance?

**Comment by Pyrdacor** [comment]
Btw audio errors are handled. If it fails to init the audio, it will just disable the audio output.

**Comment by Pyrdacor** [comment]
The path randomization is there for a while now. If I understand it right it is only active if the app is still inside the download folder. If you would move the whole app somewhere else it should not randomize the path anymore and thus it should work if this is the issue.

**Comment by export2file** [comment]
Just moved the application over to the "applications" folder. Still the same error. :-/

> When you start from terminal, is there some savegame folder created by any chance?

Where is the "saves" folder supposed to be created?

**Comment by Pyrdacor** [comment]
I guess next to the app. Did you try to create a new sub folder inside the "applications" folder and move the app there? And maybe grant that folder full permission.

**Comment by export2file** [comment]
"Next to the app" is correct, just tested it.

And if I open the app, the 'Saves' folder does NOT get created, while if I execute the codefile it DOES get created. So it may be very well related to permissions.

I tried to fix it by giving r/w permissions to "everyone" on Ambermoon.net folder level and then "applying it to enclosed items", but that did not work as fix. :-/ If I restart the app it still crashed/closes.

**Comment by Pyrdacor** [comment]
Can you check if the following folder is there?

`/Users/yourUserName/.config/Ambermoon`

If not, please create it manually.

And in all cases, ensure that the game has write access there.

Then try again.

**Comment by Pyrdacor** [comment]
The first issue is as I thought. The app translocation moves the app somewhere else and restricts write access.

Normally the game falls back to the application folder (as you mentioned) which is ~/.config/Ambermoon.

Instead of touch, you should use mkdir as Ambermoon is a folder, not a file.

**Comment by sisch** [comment]
Fair point, I didn't properly read the comment above.
And with the folder created it works indeed.

Ah, I just found the FallBackDirectory a few lines above BundleDirectory.
However, when started with double-click, the game does not try to use and create the backup directory.
If I can provide more info, let me know.

**Comment by Pyrdacor** [comment]
Ok I moves that method a few days ago but the old implementation for 1.7.1 should also not show the described behavior. Have to investigate this a bit more.

**Comment by Pyrdacor** [comment]
@export2file @sisch Can you please test with the following test version?

[ARM processor](https://ambermoon-net.pyrdacor.net/download/test/Ambermoon.net-Mac-ARM.zip)
[Intel processor](https://ambermoon-net.pyrdacor.net/download/test/Ambermoon.net-Mac.zip)

**Comment by sisch** [comment]
Similar error, but uses GetSavePath from Configuration now

```
Read-only file system : '/private/var/folders/8v/_2gd5zc910z6yqk2bl8tvc1r0000gn/T/AppTranslocation/E6BBFC68-F56C-4E9D-95F1-353C88F688C9/d/Ambermoon.net.app/Contents/Resources/Ambermoon/SavesRemake/german'
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Ambermoon.Configuration.GetSavePath(String version, Boolean createIfMissing)
   at Ambermoon.GameWindow.<>c__DisplayClass70_0.<ShowVersionSelector>b__12(Int32 gameVersionIndex, IGameData gameData, Boolean saveInDataPath)
   at Ambermoon.UI.VersionSelector.<>c__DisplayClass29_0.<.ctor>b__2()
   at Ambermoon.UI.Button.ExecuteActions(UInt32 currentTicks, Boolean rightMouse)
   at Ambermoon.UI.Button.LeftMouseUp(Position position, Nullable`1& cursorType, UInt32 currentTicks)
   at Ambermoon.UI.Button.LeftMouseUp(Position position, UInt32 currentTicks)
   at Ambermoon.UI.VersionSelector.OnMouseUp(Position position, MouseButtons buttons)
   at Ambermoon.GameWindow.Mouse_MouseUp(IMouse mouse, MouseButton button)
   at Silk.NET.Input.Internals.MouseImplementationBase.HandleMouseUp(IMouse mouse, MouseButton btn)
   at Silk.NET.Input.Glfw.GlfwMouse.<Subscribe>b__36_2(WindowHandle* _, MouseButton btn, InputAction action, KeyModifiers mods)
   at Silk.NET.Input.Glfw.GlfwEvents.<.ctor>b__0_2(WindowHandle* a, MouseButton b, InputAction c, KeyModifiers d)
```

Unfortunately I could not investigate with my debugger, because running it from my IDE in debug mode, doesn't raise any error :/

**Comment by Pyrdacor** [comment]
This should not be possible when the path in the code is equal to this. But I guess the path is just changed when accessing something outside the program by macOS. Such a shitty thing. Don't know if I can or want to keep up Mac support if Apple continues to do such awkward things.

**Comment by sisch** [comment]
That really sounds shitty. 
If you plan to close the issue as wontfix for now, let me know, and I'll clone it to my fork. As I might have some time right after christmas to take a deeper dive.

**Comment by Pyrdacor** [comment]
I am not sure yet. The best bugfix would be to not upgrade to the latest macOS version. So much trouble just because of that gatekeeper stuff which won't prevent any real bad guy of producing malware but prevents all indie devs to deliver software and games.

**Comment by Pyrdacor** [comment]
I uploaded another version (same link). Please try again.

**Comment by sisch** [comment]
Still the same. `Read-only file system : '/private/var/folders/8v/_2gd5zc910z6yqk2bl8tvc1r0000gn/T/AppTranslocation/EAF6B0DB-547E-41C6-8B28-E32C7A36C463/d/Ambermoon.net.app/Contents/Resources/Ambermoon/SavesRemake/german'`

However, I checked the system logs and among a million other messages related, in this latest download version I found
```
'/private/var/folders/8v/_2gd5zc910z6yqk2bl8tvc1r0000gn/T/AppTranslocation/8E90DB67-7C52-4F3E-9D4B-197331BCC59A/d/Ambermoon.net.app/Contents/MacOS/Ambermoon.net' is adhoc signed.
default	13:04:01.045927+0100	kernel	AMFI: code signature validation failed.
```

That error does not show in the original repository release.

**Comment by Pyrdacor** [comment]
The most recent version 1.8.7 should work now. Feel free to reopen if not.
