### ISSUE TITLE
[Feature request] For Mac the supporting document should be in the .zip not in the .app

### ISSUE THREAD

**Issue by export2file** [Pyrdacor/Ambermoon.net#328]
Just something I recognized earlier. In the MAC .zip if you want to access the map+manual etc, you need to right-click the App icon, select "show contents" and then you'll be able to the those files.

I would be more obvious if you unpack the zip and have the files in parallel to the .app.  Basically the same way it is in Windows.

Maybe that is a limitation of the packaging process. But if it's possible it will help the Mac Users I guess.

(picture attached: supporting files should be in the left folder, not in the right folder)

<img width="1181" alt="Bildschirm­foto 2022-11-15 um 19 28 53" src="https://user-images.githubusercontent.com/34287248/201998057-5cb6936f-0e0c-4450-bbf4-e8e84699f0f7.png">

**Comment by Pyrdacor** [comment]
Good point. I will change the packaging for the next release. ;)
