### ISSUE TITLE
[Bug report] Battle advance issue

### ISSUE THREAD

**Issue by export2file** [Pyrdacor/Ambermoon.net#330]
** Bug Descripton **
During a fight if I use "Vorrücken" / "Advance" and then press "9" on the numpad instead of left mouse-botton, the command is executed twice and may end in an undefined state

** Reproduction steps **

- during a fight press „vorrücken“ (picture 1)
- Cursor shows „click“ smybol (picture 2)
- Now press „9“ on number block. instead of left-click
- The group moves forward, everything looks normal as if the system would wait for the next command
- But if you THEN click anywhere the group moves again and may get stuck in an enemy - in case there happens to be one (picture 3)
- the "collided" character can not be controlled anymore (can't move etc) and is often display on a box outside of the fighting grid (picture 4)

Well.. it's not a major problem, but I keep hamming 9 all the time during fights, so it happened pretty frequently to me. At least with bandits as they try to flee all the time :D

![advance_1](https://user-images.githubusercontent.com/34287248/202027811-6e255fc3-c640-4076-bebd-b3e7e4efda2d.png)

![advance_2](https://user-images.githubusercontent.com/34287248/202027831-b4437ecb-dedb-46ca-a5b2-4c876ea6d6dd.png)

![advance_3](https://user-images.githubusercontent.com/34287248/202027849-24bd8f7a-a21a-4f72-af8a-3a5d74564c15.png)

![advance_4](https://user-images.githubusercontent.com/34287248/202027860-3f9b8d6d-0155-4d13-aff7-22fbf4205159.png)

**Comment by Pyrdacor** [comment]
The numpad should not work in this situation. Only a click or ESC. I will check that.

**Comment by Pyrdacor** [comment]
Note to myself: numpad/action buttons should be disabled during battle messages.
