### ISSUE TITLE
[Question] Right-click on Macbook without external mouse?

### ISSUE THREAD

**Issue by export2file** [Pyrdacor/Ambermoon.net#331]
If I play the game on Mac, is there a way to switch the Numpad-menu on the bottom right without an external mouse?

The usual "CTRL + Trackpad-click for right-click" does not work

I can't save :)

**Comment by Pyrdacor** [comment]
Yes just hit the Enter/Return key.

**Comment by Pyrdacor** [comment]
In general you should be able to replace the right mouse everywhere.

- Toggling buttons with enter.
- Enter inventories with F1 to F6
- Abort actions with ESC

There is no "take all" alternative for item pickup but you can use the PageUp key in the amount popup to immediately select the full amount and then hit enter.

**Comment by export2file** [comment]
Ahhhhhh, thanks! Didn't see it in the readme or the FAQs. Did I miss it?

**Comment by Pyrdacor** [comment]
It will be described in the Controls.pdf which is part of the next release. ;)

**Comment by Pyrdacor** [comment]
You can already view it here: https://github.com/Pyrdacor/Ambermoon.net/blob/master/Package/Controls.pdf

There is also a download button.

**Comment by Pyrdacor** [comment]
Oh just saw it is missing there as well ... will add it

**Comment by Pyrdacor** [comment]
It is not added under section "Maps".
