### ISSUE TITLE
Crash: Application tried to remove more items than existed

### ISSUE THREAD

**Issue by krater** [Pyrdacor/Ambermoon.net#332]
Observed on Ambermoon.net V1.7.1, Ambermoon Advanced 0.01 German on Windows 7.
Go to a shop and try to sell a item. When the request if you want to sell it really comes, press fast 'j' more than one time.
-> Game crashes

After restart, crashed game will be recovered but all gold are gone.

**Comment by Pyrdacor** [comment]
FYI: there is a repository for Ambermoon net. I moved this issue there now.

**Comment by krater** [comment]
Oh, I missed that. Nice :)
