### ISSUE TITLE
[Bug report] Crash while taking a screenshot

### ISSUE THREAD

**Issue by TobiasReich** [Pyrdacor/Ambermoon.net#341]
**Describe the bug**
I'm not sure how these cheats are meant to be used but when I discovered them in the code I was playing around a little bit.

**To Reproduce**
1. play the game
2. Hold CONTROL key and type "help"
3. game crashes to desktop with Segementation Fault

Happens to most of the other "codes" as well.

**Expected behavior**
Not sure what is supposed to happen but this is surely not correct. 

**Desktop (please complete the following information):**
 - OS: Arch Linux
- .NET version is 7.0.100
 - Latest Ambermoon Release

**Comment by TobiasReich** [comment]
Haha, yes the CONTROL key was actually more a kind of an experiment since someone in the internet wrote something about old cheat codes which had to be written while holding the ALT key so I was curious if the "new" cheats were working somehow similar.
To be honest, I was not starting the program via the terminal but simply (lazily) by clicking on it in the Dolphin Filebrowser and had no clue on how these cheat modes were supposed to work.

That might perhaps be an improvement for new players. Since you upgraded the options menu already, there could be a cheat console perhaps so users not using the terminal might have easier access. Then again, perhaps not the highest priority. Thanks in any case! 

Regarding what causes the game to crash, I have no idea. After all that crash returns a segmentation fault (e.g. when closing then. This still indicates something might be wrong - even though low priority).

**Comment by TobiasReich** [comment]
On a side note, that could be a system specific thing.
Thinking about it, I guess CONTROL + P (as it is the last key pressed) is for printing in many applications. 
I could imagine this starts the menu options for the application and the RETURN afterwards executes it.
So this probably just crashes because some window actions like moving, resizing... or "print" is executed. 

So that is no game issue but more a "menu issue". I guess this error is even less serious then. Not sure if you want to follow that or just close the ticket. Sorry for the annoyance!

**Comment by Pyrdacor** [comment]
Control+P is a game shortcut for taking a screenshot. There is a similar report that this features crashes on Mac. Can you try to use the PrintScreen button? Has the same functionality and should then crash as well.

If you start from terminal, you should see an error or even call stack.

Regarding the cheat console. On Windows when starting the game, a console window is opened in the background. But I guess Linux does no such thing?

**Comment by Pyrdacor** [comment]
@TobiasReich Did you have the time to check on this?

**Comment by Pyrdacor** [comment]
Ok I found the issue and already fixed it. Will be part of next release. See #334
