### ISSUE TITLE
[Bug report] Only 3 gongs in the orc cave

### ISSUE THREAD

**Issue by Marathony** [Pyrdacor/Ambermoon.net#345]
I searched the orc cave several times and also solved the riddle of the mouth. But I find only 3 gongs. In my opinion, the fourth gong is missing.

BS: Linux / Ubuntu 22.04

**Comment by Pyrdacor** [comment]
I am pretty sure there are all gongs and you can explore the whole map. Maybe you forgot to activate one of the three gongs you already found? The game data is the same as in the original so such bugs are very unlikely if it worked in the original.

**Comment by Marathony** [comment]
Okay, the problem has been solved. I thought the two round doors were locked. But they were unlocked and I only had to touch them to make them open :)

Thanks for the support and the fantastic implementation :)
