### ISSUE TITLE
[Bug report] Problem with learning spells

### ISSUE THREAD

**Issue by AdamDybich** [Pyrdacor/Ambermoon.net#360]
When trying to learn spells (with the main character and Nelivin, I haven't gone further yet), the game crashes and throws the error "Unknown task: lead"

**Screenshots**

![Przechwytywanie1](https://github.com/Pyrdacor/Ambermoon.net/assets/124807044/2a50568c-dc68-4455-aa79-fb388599f786)

**Desktop (please complete the following information):**
I play on PC on Windows 10 Pro, version 22H2

**Comment by Pyrdacor** [comment]
Hi. Thanks for the report. I will try to fix this asap.

**Comment by AdamDybich** [comment]
Do you see any possibility to simply make the characters available to them all black with some small patch. Until this can be fixed?

**Comment by Pyrdacor** [comment]
What do you mean? I don't understand. If you want to learn all spells with a cheat, you can do this already. Activate cheats in the options. Then enter the cheat "netsrak". But this will also max all other values beside learning all spells.

I most likely can provide the fix tomorrow btw.

**Comment by AdamDybich** [comment]
Ok, I didn't want to train all the characters to the max. Only without spells, after a certain point the game becomes extremely difficult (:

**Comment by Pyrdacor** [comment]
Should be fixed now in 1.9.2.
