### ISSUE TITLE
[Bug report] - Cant start Ambermoon 1.9.2

### ISSUE THREAD

**Issue by Felipefpl** [Pyrdacor/Ambermoon.net#362]
**Describe the bug**
I downloaded the 32 bit Ambermoon and i couldnt start the game.

**Screenshots**
![Sem título](https://github.com/Pyrdacor/Ambermoon.net/assets/5569804/73e70bed-e94e-47a6-b1c3-ada406294d17)

**Desktop (please complete the following information):**
 - Windows 7 x64
 - Basilisk, Firefox

I attached the .cfg file because i guess it can help you:
[ambermoon.zip](https://github.com/Pyrdacor/Ambermoon.net/files/13582113/ambermoon.zip)

**Comment by a1exh** [comment]
I think this means your gfx card isn't good enough to run Ambermoon .NET

You could try and update / re-install your gfx card drivers.

**Comment by Pyrdacor** [comment]
Don't use the 32 bit version on a 64 bit machine. Try the 64 bit version please.

**Comment by Pyrdacor** [comment]
Well as Alex mentioned your video card is not good enough. You can try to look for a driver update but sometimes the hardware is just to old. OpenGL 3.1 is required as the engine is using shaders. Even though someone states that it is 100% supported is no guarantee. I mean in the end if some OpenGL function is missing you will receive an error. And this is happening here. I don't think I can do much about it beside rewriting the whole rendering code. Sorry.

Maybe you can find a more recent driver which works.

**Comment by Pyrdacor** [comment]
There are some articles and video online where they tackle the issue. But mostly it is about updating their drivers. Sometimes they use some manual driver updates, maybe even 3rd party. But I won't recommend this here. It is just another possibility maybe.
