### ISSUE TITLE
[Bug Report] Enemies can walk into walls on 2D maps

### ISSUE THREAD

**Issue by Talmit** [Pyrdacor/Ambermoon.net#363]
**Describe the bug**
When moving into the fireplace, the bandit moves into the wall.

**To Reproduce**
1. Go to the bandit's house
2. Spawn the bandit captain
3. Move to the unlit fire place
4. Move inside
5. The bandit is standing in the wall

**Expected behavior**
The bandit shouldn't stand in the wall.

**Screenshots**
![image](https://github.com/Pyrdacor/Ambermoon.net/assets/88923192/2fbede3d-a8e9-42b6-8924-9c4819012290)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
I'm using ambermoon advanced (1.03) and ambermoon 1.9.2. The attached Save 1 is directly before spawning the bandit, Save 2 was before I would have entered the fireplace with the bandit right next to me, but the bandit's position seems to have been reset. I think that's default ambermoon behaviour though.

**Comment by Pyrdacor** [comment]
Hopefully this is fixed in 1.9.3. If not, feel free to reopen.
