### ISSUE TITLE
[Bug report] [Render] Unable to create layer 'Map3DCeiling': Fragment info

### ISSUE THREAD

**Issue by 76joda** [Pyrdacor/Ambermoon.net#365]
**Describe the bug**
After Starting ambermoon.net.exe I get this:

![ambermoon](https://github.com/Pyrdacor/Ambermoon.net/assets/155030526/1a59b62f-59b5-4d1d-b3de-48d75adbb299)

Windows 10 Pro 20H2
GTX 1060 (driver: 546.33)

**Comment by Pyrdacor** [comment]
Those graphic drivers... Some are very restrictive like in your case and produce errors. And some do not like in my case (so I couldn't see the issue on my end). Thanks for letting me know with detailed error information. I hopefully fixed this now and will provide a new release asap.

**Comment by Pyrdacor** [comment]
Can you please test with 1.9.4

**Comment by 76joda** [comment]
It works, thank you!
