### ISSUE TITLE
[Bug report] When using a potion to increase attributes, the relevant values are not updates

### ISSUE THREAD

**Issue by Talmit** [Pyrdacor/Ambermoon.net#366]
**Describe the bug**
When using a potion (strength or constitution, although I only tested strength) to increase attributes, the carrying capacity, damage and defense are not updated.

**To Reproduce**
1. Open Inventory of a character with a strength potion
2. Use the potion on the same character
3. Look at the carrying capacity / damage

**Expected behavior**
Both carrying capacity and damage should reflect the new maximum strength value

**Screenshots**
![image](https://github.com/Pyrdacor/Ambermoon.net/assets/88923192/4ecf10d6-5cc5-404c-ae2e-8ae9551acf4e)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.9.3 / Ambermoon Advanced 1.3

**Additional context**
The attached Save 3 has the appropriate setup. Aret has a strength potion in her inventory, use it on her to observe the behavior.
[Saves.zip](https://github.com/Pyrdacor/Ambermoon.net/files/13795192/Saves.zip)

**Comment by Pyrdacor** [comment]
Was the character maybe already at max strength? It can not exceed that.

**Comment by Talmit** [comment]
No, the character had a maximum of more than 50 (I actually do not know why, I figure it's one of those strange lights in the tempel?). The strength itself was increased (if you closed and reoped the window or opened the stats screen), but the displayed maximum weight / maximum damage were not updated.

**Comment by Pyrdacor** [comment]
Is now fixed. Is part of the next release.

**Comment by Pyrdacor** [comment]
Fixed in 1.9.5
