### ISSUE TITLE
[Feature request] Shortcuts for convenience

### ISSUE THREAD

**Issue by Talmit** [Pyrdacor/Ambermoon.net#368]
**Is your feature request related to a problem? Please describe.**
Whenever I get a confirmation dialog, I automatically want to confirm it using enter and abort it using escape.

When I move on the map I sometimes default to the arrow keys to move instead of using wasd.

**Describe the solution you'd like**
I'd like to propose the following shortcuts:
- Yes / No Dialogs: Enter confirms, Escape aborts
- Yes / No Shopping Confirmations: Enter confirms, Escape aborts
- Escape closes the options menu

Furthermore (I think this is probably actually a bug, since I think it worked in an older version and in the amiga version of the game) I'd suggest using the left / right keys to change the camera direction similar to a/d on the world map. This currently seems a bit strange as the up / down keys move the character, but the left / right keys do not rotate them.

**Comment by Pyrdacor** [comment]
Added in 1.9.5
