### ISSUE TITLE
3D Movement

### ISSUE THREAD

**Issue by Thallyrion** [Pyrdacor/Ambermoon.net#37]
The 3D movement via the movement arrows (num key movement) does not resemble the original behaviour yet. 

The Num 7+9+1+3 should only rotate the perspective and not move + rotate
The arrow keys left + right do it correctly

**Comment by Pyrdacor** [comment]
Are you sure about that? I tested it a few days ago and it looked like the player moves too. I even added the movement only after that test in original game. Before that those buttons only rotated.

**Comment by Thallyrion** [comment]
Yes i checked with original game. If you use the arrows from the menu you only rotate. If you use the arrows in the 3D Viewscreen you have rotation and movement.

**Comment by Pyrdacor** [comment]
Ah ok that makes sense. I thought the cursors and buttons have equal functionality and I only checked the cursors. The buttons use the same logic as the cursors at the moment so I will have to add some distinction.

Thank you for your efforts. Will fix this. The video is very helpful.

**Comment by Pyrdacor** [comment]
I implemented it in v1.1.6. Please have a look. :) Release is coming in a second.

**Comment by Pyrdacor** [comment]
Did you try? Link for 1.1.6 was wrong before. But now it should work.

**Comment by Thallyrion** [comment]
Tried 1.1.7 and movement works like a charm :D

**Comment by Pyrdacor** [comment]
Great. I'll close this now.
