### ISSUE TITLE
[Bug report] Options Menue crashes the game

### ISSUE THREAD

**Issue by Retrokind** [Pyrdacor/Ambermoon.net#374]
**Describe the bug**
As soon as you open the options menue the game crashes with the error message: 
"The type initializer for 'Ambermoon.UI.Layout' threw an exception."

**To Reproduce**
1. Click on 'Options' in the action icons
2. Click on 'Options' in the new action icons
3. The error message appears and the game crashes

**Expected behavior**
Open the Options menue to look and perhaps change the settings of the game.

**Screenshots**
![OptionsOptions](https://github.com/Pyrdacor/Ambermoon.net/assets/160653225/d729488a-2c87-4ae7-97f0-33d9539eee26)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Game Version [1.9.7] - I play the Ambermoon original Version.

**Additional context**
I play the game in German.
[error.txt](https://github.com/Pyrdacor/Ambermoon.net/files/14350190/error.txt)

**Comment by Pyrdacor** [comment]
Thanks for reporting. Will work on a fix ASAP.

**Comment by Retrokind** [comment]
Similar happens if I use the action keys for moving in 3D. Here is the error log:

[error.txt](https://github.com/Pyrdacor/Ambermoon.net/files/14351372/error.txt)

Do you want that I register a new bug for this?

**Comment by Pyrdacor** [comment]
No it's fine. I will check both

**Comment by Pyrdacor** [comment]
I think it is the same cause

**Comment by Pyrdacor** [comment]
Should work now in 1.9.8
