### ISSUE TITLE
[Bug report] INVENTORY: Defence display is changing when picking up items

### ISSUE THREAD

**Issue by Retrokind** [Pyrdacor/Ambermoon.net#375]
**Describe the bug**
As soon as you pick up an item from the inventory or from the body parts the defence display changes back to +1.
You need to close the inventory window or change to stats and back to inventory to see the recent value of your defence.

**To Reproduce**
1. Go to 'Inventory'
2. Have an item on your body parts which gives you more defence
3. Look at the defence value; it should be more than your standard +1
4. Pick up an item from your inventory or from the body parts
5. Look at the defence value again; it is now back to +1

The same happens if you wear no protection and put your first protection on, the number is still +1. You can't check the new value directly. You need to leave the inventory window and open it again or change to the stats screen and back to the inventory.

**Expected behavior**
As soon as you change your protection the defence value should directly show the new defence value and the defence value should not be changed if you move your items.

**Screenshots**
![Defence01](https://github.com/Pyrdacor/Ambermoon.net/assets/160653225/a9ca6ccc-d10d-482e-82aa-e212f2ea7f5e)
![Defence02](https://github.com/Pyrdacor/Ambermoon.net/assets/160653225/d8f3645f-c43d-4d5f-9b71-22dcd67d5a8b)

**Desktop (please complete the following information):**
 - OS: [Windows 10]

**Additional context**
 - Game Version [v1.9.08]
 - Ambermoon Original Version 1.19
 - Language: German

**Comment by Pyrdacor** [comment]
Should be fixed in 1.10
