### ISSUE TITLE
Sprite Bug on 2D Map

### ISSUE THREAD

**Issue by Thallyrion** [Pyrdacor/Ambermoon.net#38]
I noticed the following bug:
![sprite bug](https://user-images.githubusercontent.com/69513157/93358071-58869880-f841-11ea-8e05-ad6d02b0827e.png)
![sprite bug2](https://user-images.githubusercontent.com/69513157/93358202-7e13a200-f841-11ea-86d1-2448d9cb0ed8.png)

should look like this:
![original](https://user-images.githubusercontent.com/69513157/93358540-e6fb1a00-f841-11ea-87d5-c4a88014438c.png)

**Comment by Pyrdacor** [comment]
Damn I thought I fixed it already. Which version did you try?

**Comment by Thallyrion** [comment]
1.15

**Comment by Pyrdacor** [comment]
Ok I will check tomorrow.

**Comment by Pyrdacor** [comment]
I can't reproduce this in 1.1.5. How did you do it?

**Comment by Thallyrion** [comment]
I made a video showing it

https://drive.google.com/file/d/1g7koZb2zqzUcV2RJjnpBXJC4PfwV1Fu-/view?usp=sharing

**Comment by Thallyrion** [comment]
1.17 did not fix it. I just tried it. same spot.

![sprite bug3](https://user-images.githubusercontent.com/69513157/93484642-75cf6b80-f902-11ea-9828-8f8c474fd12a.png)

**Comment by Pyrdacor** [comment]
Ok this is caused when you don't move and only the direction is changed. I will fix this tomorrow. :)

**Comment by Pyrdacor** [comment]
Should be fixed in v1.1.8.

**Comment by Thallyrion** [comment]
Yes it is fixed

**Comment by Pyrdacor** [comment]
Ok I could reproduce this and fixed it. Will be available in next release. :)

**Comment by Pyrdacor** [comment]
Should be fixed in 1.1.9
