### ISSUE TITLE
Automatic Message Appearance on 2D World Map

### ISSUE THREAD

**Issue by Thallyrion** [Pyrdacor/Ambermoon.net#39]
There needs to be some check whether the Message should be displayed when near a position or just when active clicking on something with Eye or Hand.

Example is this message:
![message appearance](https://user-images.githubusercontent.com/69513157/93358715-1d389980-f842-11ea-93c7-9941a6744a66.png)
This message should not appear automagically. Only when actively clicked on the signpost.

**Comment by Pyrdacor** [comment]
In general there should be a condition event before that event which specifies that it only can be triggered this way. At least I thought so. In grandfathers house it worked well with that assumption. I will investigate the map events further soon. For example some text popups events should not occur twice. But I don't know how this is implemented yet.

**Comment by Pyrdacor** [comment]
This should work now with v1.1.6.
