### ISSUE TITLE
Messages from executable have different indexes in DE and EN version

### ISSUE THREAD

**Issue by Metibor** [Pyrdacor/Ambermoon.net#46]
Hi, I am still there! Just too much stuff going on right now. 🤔

The DontForgetItems has index 24 in the English v1.07 but 22 in the German v1.05 version.

**English**
![grafik](https://user-images.githubusercontent.com/12674912/94345904-74e8b900-0029-11eb-9c8f-35217260b39b.png)

**German**
![grafik](https://user-images.githubusercontent.com/12674912/94345950-a19cd080-0029-11eb-9541-5817348ff7f2.png)

The German version is missing index 5 and 23 in comparison to the English version.

**German LoadWhichSavegame is 2 off**
![grafik](https://user-images.githubusercontent.com/12674912/94346170-2805e200-002b-11eb-94c4-dfefefa80cfb.png)

**English is correct**
![grafik](https://user-images.githubusercontent.com/12674912/94346233-8337d480-002b-11eb-9995-a0dbb9fd9173.png)

**Comment by Pyrdacor** [comment]
Decoding the data is not perfect yet. Maybe you have time to have a look at it. I didn't fully understand the data storage logic but added it in a way so it worked most of the time. But it wasn't good enough I guess. Maybe you find a way to load the data correctly for all game versions? If not I'll have a look at it next week maybe.

**Comment by Pyrdacor** [comment]
For a start have a look at the big comment at the start of this file: https://github.com/Pyrdacor/Ambermoon.net/blob/master/Ambermoon.Data.Legacy/ExecutableData/Messages.cs.

This should give you the idea. But this all were suggestions from observation which worked quite well.

I assume that the 0-longwords have a purpose like denoting empty entries etc. But I am not sure about that.

**Comment by Pyrdacor** [comment]
I reworked message loading and it should work now. At least in the tested german and english versions I have. But let me know if you still have problems in 1.1.17.
