### ISSUE TITLE
Add cursor change with mouse wheel

### ISSUE THREAD

**Issue by jr-riketz** [Pyrdacor/Ambermoon.net#50]
When i just started a new game, i cant add any item into my wallet.
Ill remember that i can scroll the actions with the middle mousebutton and do a left click on a chest or a bookshelf.

Thas not possible right now.

**Comment by Pyrdacor** [comment]
Hi thanks for your feedback. I am not sure if I get you right.

To open a chest you have to use the hand or eye cursor. Your can access them on the lower right buttons. If the arrow buttons are visible there, just right-click on the buttons.

When you see the chest items you can drag&drop them to the portrait of a party member. You can also right click the portrait while dragging the item to enter the inventory and drop it there.

Did you mean that? Or does this not work somehow?

**Comment by Pyrdacor** [comment]
I didn't know about the middle mouse thing. Have to check that as well.

**Comment by jr-riketz** [comment]
> I didn't know about the middle mouse thing. Have to check that as well. My Amiga mouse didn't have a middle mouse button.

At Amiga times you there was the posibility to access the different cursors by mouse wheel.

**Comment by jr-riketz** [comment]
> Hi thanks for your feedback. I am not sure if I get you right.
> 
> To open a chest you have to use the hand or eye cursor. Your can access them on the lower right buttons. If the arrow buttons are visible there, just right-click on the buttons.
> 
> When you see the chest items you can drag&drop them to the portrait of a party member. You can also right click the portrait while dragging the item to enter the inventory and drop it there.

The cursor keys at the bottom right are not available and grayed out for me. i stand here in grandfather's house by a book rule and nothing happens.

**Comment by Pyrdacor** [comment]
Ok so you can open chests now? I will add the mouse wheel thing too soon. ;)

**Comment by jr-riketz** [comment]
> Ok so you can open chests now? I will add the mouse wheel thing too soon. ;)
> 
> You can leave this open until I've added it. Will mark it as an enhancement instead of a bug now.

Yes i can Open Chests now ;-) Thanks

**Comment by Pyrdacor** [comment]
@jr-riketz Hi there. I just release 0.1.6beta. It contains cursor toggle with mouse wheel on 2D maps. I hope it is how you meant it. Would be nice if you could test it and give me feedback. ;)
