### ISSUE TITLE
[Feature request] Auto De-rune

### ISSUE THREAD

**Issue by a1exh** [Pyrdacor/Ambermoon.net#55]
In the original Amiga game there is a rune sheet included in the game box and some of the fun is decoding the writing you find around Ambermoon. But it soon becomes a chore. How about an enhancement that once you've found the rune sheet in the game (I think there is a rune sheet item in the game) all the runes are displayed as plain text? OR perhaps if you hold down a key, like TAB or something?

This idea was suggested/implemented by Ambermoon fan st-th in 2009 when he was making his own Amiga patch. However he disappeared without releasing anything. I still think it is a good enhancement.

**Comment by Pyrdacor** [comment]
I like the idea. I would add that as an optional game option though so players can decide if they want to use it.

Maybe we can also use an ingame lyramion map when you find the map of lyramion ingame.

**Comment by Pyrdacor** [comment]
I think I'll add this to 1.0 as well as most players today don't have the rune alphabet at hand. I add it as an optional feature which is active by default.

**Comment by Uukrull** [comment]
Could you change the color of the translated text? That way it will be easy to see the text has runes that usually is important information.

**Comment by Pyrdacor** [comment]
I am not yet sure how to implement the feature. I agree that the player should see that there are runes, otherwise he will think that the rune alphabet is useless. Adding an animation which converts the runes into letters came to my mind but I guess it's hard to implement to all kind of text popups and fields. Another option would be some kind of reveal button (could be the eye symbol or the rune alphabet item sprite) but this is also hard to implement. Especially because user input except for general clicks is often forbidden while a text is displayed.

A different color might be an option but I don't know if this is clear enough.

**Comment by Uukrull** [comment]
The different color option seems to be the only doable option if the other ones are hard to implement. Ideally this could work but, as you said, it isn't that simple.

![image](https://user-images.githubusercontent.com/5891591/128644621-c1b65e44-c43f-483e-bd08-de438d29a778.png)

**Comment by Pyrdacor** [comment]
I added the color version now and an option for it in the option menu and configuration file.

**Comment by a1exh** [comment]
Are there items in the game which correspond to the world map and the rune translation table? That are in themselves useless as items but advise you to look at the physical items that came in the game box? Perhaps this was Amberstar?

**Comment by Uukrull** [comment]
> Are there items in the game which correspond to the world map and the rune translation table?

Yes, the runes table and the map. When you get them, the game says you can use the real objects.

**Comment by a1exh** [comment]
If you could make an event which only turned on Auto De-rune when you have discovered the runes table? That could introduce players naturally? (i.e. they probably encounter runes before they find the item in the game?)

**Comment by Pyrdacor** [comment]
The normal version is now in the current TestRelease. You still need the item to see the runes as text of course and the option activated as well.

I guess I will change the texts a bit when you use the item. The question is if the runes should be shown as text even when you don't carry the rune table but already found and used it? At the moment you have to carry it with you to unlock the text.

**Comment by Pyrdacor** [comment]
If auto de-rune is active, using the rune table will now display a different text which says that runes will be shown as text if you have the table in your inventory. If auto de-rune is disabled the normal text is shown.

I will close this issue now. Displaying a map when using the lyramion map item can be handled by a different issue or most likely after 1.0.
