### ISSUE TITLE
[Feature suggestion] Add some filters and/or shaders to interface and/or fullscreen

### ISSUE THREAD

**Issue by Pat9496** [Pyrdacor/Ambermoon.net#57]
Right now the high resolution rendering of the 3D-world clashes with the low resolution of the game interface and 2D-world. 

My suggestion would be twofold:

1. Add a fullscreen filters like 2xSAI and HQ2x and combine this with a bilinear filter
and/or
add the option of using a full screen shader (for example crt-caligari) or even the option the add your own shaders

2. Allow a filter (again for example 2xSAI or HQ2x) to be added to all 2D elements like the interface, 2D sprites and 3D textures.

**Comment by Pyrdacor** [comment]
How about this? I'll add an option like "legacy rendering". If it is on I use the current 2D shader and use a 3D shader which renders in a more pixelated way. If it is not on, I use current 3D shader plus a new 2D shader like 2xSAI etc.

What do you think about that?

**Comment by Pat9496** [comment]
That sounds like a great idea!

**Comment by ssuukk** [comment]
Any way to scale the game would be great, as now on my screen, it is just a thumbnail, too small to enjoy playing it!

**Comment by Pyrdacor** [comment]
> Any way to scale the game would be great, as now on my screen, it is just a thumbnail, too small to enjoy playing it!

You can already do so. There should be a Ambermoon folder with a config file inside your %APPDATA% folder. There you can change the resolution if the game is not running.

**Comment by Pyrdacor** [comment]
You can also play in fullscreen by pressing F11.

**Comment by Pa9an** [comment]
> 
> 
> > Any way to scale the game would be great, as now on my screen, it is just a thumbnail, too small to enjoy playing it!
> 
> You can already do so. There should be a Ambermoon folder with a config file inside your %APPDATA% folder. There you can change the resolution if the game is not running.

Does this work for the Linux version also?
Don't see any folder or config file being created that I could edit...

**Comment by Pyrdacor** [comment]
It should be in `home/.config/Ambermoon`. This is the application data folder which .NetCore uses on Linux.

**Comment by Pyrdacor** [comment]
FYI: Since 0.2.0 the config is stored next to the program if this is possible (access rights etc).

**Comment by Pyrdacor** [comment]
@Pat9496 In the most recent TestRelease I added an optional graphic filter. It's now scaling like Hq2x etc but at least it looks a bit smoother in relation to the 3D scene.

I am not sure if this is enough but maybe it's ok for the first release.

**Comment by Pyrdacor** [comment]
As further filters are not a topic for 1.0 I remove this issue from the 1.0 project here on GitHub now.

**Comment by eierfrucht** [comment]
Please consider implementing this (periodically updated) shader, it gives an almost pixel perfect crispy picture no matter the actual display resolution: https://github.com/Pyrdacor/Ambermoon.net/issues/265#issuecomment-2849264669
