### ISSUE TITLE
[Feature suggestion] Battle turbo mode

### ISSUE THREAD

**Issue by Pyrdacor** [Pyrdacor/Ambermoon.net#58]
Originally suggested by @a1exh on Twitter. I add it here to don't forget about it.

A turbo mode option should be added to minimize monster battle sequence duration.

**Comment by Shinhobi** [comment]
This is sure one of the top things to implement. While it does have a meditative aspect to watch ennemies do slow motion attack moves in battles in a game that consists of so many battles.. I am not sure that the majority of players is rejoicing in it as much as I do...

**Comment by Pyrdacor** [comment]
@a1exh @Shinhobi This is now integrated in the most recent TestRelease. You can activate it in the options "Fast Battle Mode" / "Schneller Kampfmodus".

It includes the features in the original: No click necessary after each action or text. And also it will half all animation times and delays. I think it is fast enough.

If the current implementation is sufficient, I will close this. Please give me your feedback.
