### ISSUE TITLE
[Announcement] Game tester version

### ISSUE THREAD

**Issue by Pyrdacor** [Pyrdacor/Ambermoon.net#67]
The next release will add some stuff which should ease game testing.

First of all you will be able to save the game. Either into the original game data folder (e.g. WinUAE) or into a save folder next to the program.

Moreover there will be cheats available.
- Move through obstacles and walls
- Max or change attributes, abilities, etc.
- Learn all spells and languages
- etc

In addition the game data of several versions (german and English) will be included and you will be able to choose one when starting the game. Other configuration options will be changeable in-game as well so you won't need to bother with the config file.

Do you have some suggestions related to easing game testing?

**Comment by Thallyrion** [comment]
If possible a fight generator would be nice so can select the enemy you want to fight against.

**Comment by Pyrdacor** [comment]
> If possible a fight generator would be nice so can select the enemy you want to fight against.

A generator is but too much but there is a console window in the background or you can start the game from CMD/bash. I would print all monster groups there along with the names of the monsters in that group. Then you can start a battle from any place by entering the monster group id in the console. Would be no fancy in-game feature nor key shortcut but it will do I guess. Is that ok for you?

**Comment by Thallyrion** [comment]
Sure that is absolutely enough. :)

**Comment by Pyrdacor** [comment]
Beta 0.2.0 now has 2 builtin game versions. You can provide your own as a third like before. When starting Ambermoon there will be a version selector where you can choose which version you want to play. The builtin versions have no savegames of course.

Moreover configuration files are now stored next to the Ambermoon executable if possible.

Next releases will then bring the ability to save the game, cheats and so on.

Please test if the current version works for you.

**Comment by Pyrdacor** [comment]
I implemented a first version of game saving. I created a test release for it. You can manually download it here: https://github.com/Pyrdacor/Ambermoon.net/releases/tag/TestReleaseSaving

Just expand the assets and download the version you want.

Would be nice if you can test this feature. **But backup your original saves!** This is still work in progress and it might mess up your saves.

There are 2 save options:

The first one is the default. It will create a folder called "Saves" next to the program. Then it creates a subfolder called "german" or "english" for the two built-in versions of "external" for your own external game data. There the save games are stored and also loaded from. This is a save option as it won't override the original savegames.

The second option is only available if you use your own non-ADF game data. This mode will save back to the original save files and might mess up your original savegames. You can select this mode in the version selector "Save game in data path".


I would be happy if you can excessively test all kinds of scenarios.

**Note:** Some things are not implemented yet. While the savegame already writes the complete data, the game logic might not update all savegame data yet. So it's very likely that not every savegame will exactly match your real progress. But hopefully at least the map, position and party members should work.

Improvements and more features will follow soon.

**Comment by a1exh** [comment]
If I am reading this correctly,  the saves will be compatible with Amiga saves?

**Comment by Pyrdacor** [comment]
Yes in theory they are. But I didn't test if they really can be loaded in WinUAE etc. This has to be tested.

**Comment by Shinhobi** [comment]
I just installed the newest version and saving the game works fine so far. That was fast, nice! I move around grandfathers house, collect and equip what there is and go to the dungeon to pick some fights. As soon as I click the disk symbol though i cannot continue the fight. If I don't I can finish the fight and I think also collect the loot.

**Comment by Shinhobi** [comment]
Also, REALLY nice to have the data in and to simply select from the versions. More motivating for testers. I will sure send it out to some people!

**Comment by Pyrdacor** [comment]
Thanks for testing. Will have a look at the issue with disk symbol in fights next week.

**Comment by Pyrdacor** [comment]
Ok I will add the main menu (in progress) and character creator (already finished) and a handful cheats and then proceed with adding places (merchants etc). Can't put too much time into the game testing stuff as the game should also advance and game testing makes even more sense when all is implemented. I already fixed the disk symbol issue in battles. Will release all the mentioned stuff in the next 2 days hopefully.

**Comment by Shinhobi** [comment]
Great. I do understand tge logic in that. first clone the thing, then start
bugging it out. still impressed.. you do things fast!

Pyrdacor <notifications@github.com> schrieb am Mo., 1. Feb. 2021, 18:18:

**Comment by Pyrdacor** [comment]
Main menu and character creator are now available in 0.2.2beta. Some cheats will follow soon.

**Comment by Pyrdacor** [comment]
> I just installed the newest version and saving the game works fine so far. That was fast, nice! I move around grandfathers house, collect and equip what there is and go to the dungeon to pick some fights. As soon as I click the disk symbol though i cannot continue the fight. If I don't I can finish the fight and I think also collect the loot. 

This bug should also be fixed in 0.2.2beta.

**Comment by Pyrdacor** [comment]
Ok I added several cheats / commands. You can use them in the console window that pops up behind the application window or if you start the game from the console (bash, CMD, etc) you can type the commands there.

Start off with the command `help`. It will show a list of available commands. You can then use `help commandName` like `help godmode` to get further information.

If you encounter something like this `[something]` or `<something>` in the command descriptions this means "optional parameter" and "required parameter".

You can use the TAB key to expand the commands. So if you typed a 'g' and hit TAB it should auto fill "godmode" in.


Quick overview:

- **godmode**: Makes all party members immune to damage. You will still see the damage and the damage messages are shown but you won't lose any LP. You can turn it on or off: `godmode 0`, `godmode 1`. If you omit the parameter, the godmode is activated.
- **netsrak**: Fills the LP/SP, max all attributes and abilities, learn all spells and languages. This can't be reverted.
- **monsters**: Shows a list of all monster groups in the game with their associated index.
- **fight**: Starts a fight with a given monster group. You have to pass the monster group index as a parameter. You can get the index from the *monsters* command.
- **maps**: Lists all maps with their associated index.
- **teleport**: Teleports you to a given map. You have to specify at least the map index as a parameter. Optionally you can provide additional parameters for x-coordinate, y-coordinate and look direction. The direction can be given as 0-3 or up, right, down, left.

Would be nice if someone could test this and tell me if it's useful.

For now I will proceed with implementing places. ;)

**Comment by Shinhobi** [comment]
Well on a quick test, starting a fight works and teleporting somewhere works as well! Netsrak does max everything. Godmode also seems to work. 

I started a fight with my character with nothing equiped at all and got killed immediately (no wonder). I was still able to continue and walk around though my portrait showed the death skull. I teleported to the artist house and tried to start a conversation with a guy there, though dialogue does not seem to be properly in place yet. 

I realise this is all in pogress - though maybe my feedback helps anyway!

keep up the good work. feels honestly awesome to teleport to the places and start picking fights. 

you should put in some cheats to recruit some people and equip them with like beginner, mid-game and end-game equipment. then one could actually get a feeling for how and if the fight mechanics work properly.

might be you implemented that already and I missed it.

regards

**Comment by Shinhobi** [comment]
Just realised that my save games don't work anymore as soon as I use newer
(Beta) Versions of your Ambermoon. Maybe it makes sense to find a way of
keeping the save games? or maybe it does not and it's better to start anew
everytime, put something together with cheats / commands and test out
different levels and regions. in the later case a beginning game / mid game
/ end game party with equipment would make sense (I know, coming back to my
previous point). Maybe some save games to load that say "beginning game" /
"mid game" and "end game" could help with that. just trying to be
constructive about it. let me know if it's to early for this or if I am
going in the wrong direction. cheerio

**Comment by Pyrdacor** [comment]
When you lose a fight and the whole party is dead, normally the game over screen would appear. This is not implemented yet. I guess that's why you can still move around then.

Conversations are only partially implemented. It is planned for a later release to finish them.

What do you mean by "savegames don't work anymore"? Do you mean you can't play the saves from Ambermoon.net with an emulator? If so, this might be the case. But I would like to see those savegames to check what's wrong.

If you mean, you can't load savegames in Ambermoon.net which you saved with an early version of Ambermoon.net, I would like to get the save files too.

And if you mean, you can't load original saves in Ambermoon.net anymore, maybe you can tell me what you tried to do exactly.

Either way this should not happen and we should have a look at it.

**Comment by Pyrdacor** [comment]
I need some help testing a few things about places.

It's enough to test with 1-2 different healers, trainers, etc.

- Get the cursed item and tell me what different healers want to remove it (price)
- What do different healers want to heal 1 LP (price)
- What do different healers want to cure some conditions (price)
- What effects do different Inns have (LP healing, how many hours slept, how much recovery ->hours without sleep, other effects?)
  - You can verify hours without sleep by wait some hours afterwards and look when the message "get tired" occur
  - The data suggest that each Inn has 5 values (1 is the price and 1 seems to be the LP fill, so there are 3 more I don't know yet)
  - 1 of the unknown values is 0 for Spannenberg Inn and House of healer sleeping room (both Spannenberg) and > 0 otherwise.

**Comment by Thallyrion** [comment]
I have checked some of your questions. Here is what i found out:

> * What do different healers want to heal 1 LP (price)
Spannenberg 5G
Illien 6G
Newlake 4G

> * What do different healers want to cure some conditions (price)
Poison everywhere 100G
Death Spannenberg+Newlake 1000G - Illien 500G

> * What effects do different Inns have (LP healing, how many hours slept, how much recovery ->hours without sleep, other effects?)
Hours slept: between 19:00 - 3:55 sleep until dawn (7:00) 
between 4:00 - 18:55 8 Hours
Sleeping does not cure effects. If you are poisend poison damage is applied first, then LP regeneration is applied
after 24h without sleep the message "get tired" appears
after 36h message "you are totally exhausted" appears + Effect exhausted is applied (attributes are halved) some damage is applied (10% of current character HP) from now on every hour damage is applied again (10% of current character HP) 
   
>   * The data suggests that each Inn has 5 values (1 is the price and 1 seems to be the LP fill, so there are 3 more I don't know yet)
>   * 1 of the unknown values is 0 for Spannenberg Inn and House of healer sleeping room (both Spannenberg) and > 0 for all others Inns in the game.

Sleeping at the Healer's House in Spannenberg regenerates round about 75% of  Max HP (values differed between 73,5% to 75% in my tests)
Sleeping an an Inn always recovers 100% of Max HP

**Comment by Pyrdacor** [comment]
Thanks a lot. That will help to decode the last bits of the place data.
 
>    
> >   * The data suggests that each Inn has 5 values (1 is the price and 1 seems to be the LP fill, so there are 3 more I don't know yet)
> >   * 1 of the unknown values is 0 for Spannenberg Inn and House of healer sleeping room (both Spannenberg) and > 0 for all others Inns in the game.
> 
> Sleeping at the Healer's House in Spannenberg regenerates round about 75% of  Max HP (values differed between 73,5% to 75% in my tests)
> Sleeping an an Inn always recovers 100% of Max HP
> 
> 

Yes beside the price there are 4 values for each Inn. One of them is 100 for all but the house of healers which has 75 (as you mentioned). I also identified it as the healing.

But I don't know what the other 3 values per Inn could be.

**Comment by Pyrdacor** [comment]
I decoded all the places data. The 3 unknown words in the Inn data represent the location of the bedroom (X- and Y-coordinate and map index) to which the party is teleported when resting.

The healer stores prices for all conditions that can be cured and are not battle-only as well as a price to heal 1 LP and a price to remove a curse from an item.

It's all documented here: https://github.com/Pyrdacor/Ambermoon/blob/master/FileSpecs/PlaceData.md

**Comment by Pyrdacor** [comment]
FYI: The new release 0.4.1beta brings some new cheats:
- items: Lists all items
- give: Gives items to a party member
- fly: Enter flying mode on world maps (this was also possible in development phase of original Ambermoon so there is even a sprite and movement blocking flags for that)

**Comment by Pyrdacor** [comment]
Anyone knows what happens to items which broke during battle when the party fled? Are the items lost in that case?

**Comment by Pyrdacor** [comment]
Another niche question: When a monster locked in a spell (they decide to do so at the beginning of a battle round) and I steal SP with SP-Stealer spell before the monster's turn, will the monster still be able to cast the spell if the SP isn't sufficient anymore?

**Comment by Thallyrion** [comment]
> Anyone knows what happens to items which broke during battle when the party fled? Are the items lost in that case?

Never had this case but I will try to achieve this. Also I will be looking into your Trap request. Hopefully i will get some results soon.

**Comment by Pyrdacor** [comment]
Very nice. Thanks for testing.
