### ISSUE TITLE
Battle hangs after entering Menu

### ISSUE THREAD

**Issue by Thallyrion** [Pyrdacor/Ambermoon.net#68]
I encountered the following problems:

1. i have set Battlemode to fast but it still behaves like slow so you have to click after every action
2. battle is working normally but after entering the menu in battle and going back to the battle screen the battle can't be continued. Clicking on the OK button now does nothing

I noticed that there is a music option which can be turned on and off. Is music playback already integrated as the option does nothing?
Next question is: Is the Sky in 3D Cityview implemented as it still is black for me?

**Comment by Pyrdacor** [comment]
Neither fast battle mode nor music are implemented yet. I should show them as disabled I guess.

Skies are not implemented as well. They are planned for a later release.

The bug with the option menu in battles is fixed in code and will come in the next release (hopefully tomorrow).

**Comment by Thallyrion** [comment]
Ok good to know. Then my knowledge of the development is updated. :)
And indeed it would be a good idea to grey out implemented options to avoid some confusion.

**Comment by Pyrdacor** [comment]
All the planned releases and features are tracked in #63 btw. I update it very frequently so you can rely on it.

**Comment by Pyrdacor** [comment]
The option menu bug during battles should be fixed in 0.2.2beta. Moreover the options that are not available are displayed disabled now.
