### ISSUE TITLE
Request: build instructions (for arm architecture)

### ISSUE THREAD

**Issue by michas0602** [Pyrdacor/Ambermoon.net#72]
Hi, recently found this, very interesting - 
unfortunately I see no build instructions at all.

Want to try this on a Raspberry Pi

Many thanks already.

**Comment by Pyrdacor** [comment]
Hi there. To build the project you will need the .NET Core 3.1 SDK. You can get it here: https://dotnet.microsoft.com/download/dotnet/3.1. There are also downloads for ARM32 or ARM64.

To run the game you won't need the SDK but at least the Runtime (same link as above).

Then to build the solution you have to call
    dotnet build Ambermoon.net.sln

For more info you can have a look at the dotnet commands.

## Additional note

I integrate the built-in game versions and the version selector by a post build step. Without it you won't have the built-in versions. But you still can run the game by putting your own game data next to the binary or specify the path to the game data in the ambermoon.cfg data path entry. The config will appear after first game start.

**Comment by Pyrdacor** [comment]
If you have more questions then be my guest.

**Comment by Pyrdacor** [comment]
If you manage to build and run the game it would be nice if you could share your steps so that I may integrate this into the build pipeline and provide builds for arm on a regular basis.

**Comment by Pyrdacor** [comment]
@michas0602 Did you already try it out?

**Comment by Pyrdacor** [comment]
Long time no answer. As there is another request regarding raspberry I will continue there: #78
