### ISSUE TITLE
Name in Startpage will not adopted

### ISSUE THREAD

**Issue by jr-riketz** [Pyrdacor/Ambermoon.net#73]
If You Change The Name on a NewGame Charakter the name is nor adopted.

It Switches zu Thalion instead.

**Comment by Pyrdacor** [comment]
Ok I will look at it.

**Comment by Pyrdacor** [comment]
Hm works fine for me. Which version of Ambermoon.net do you use and which game data (version/language, builtin or external)?

**Comment by Pyrdacor** [comment]
Ok I found one issue. You have to press Enter after you entered the name. The small write cursor should disappear than. The name should than be locked in. I will fix this behavior so that it will also work without hitting Enter explicitly.

**Comment by Pyrdacor** [comment]
Will be fixed in next release.

**Comment by Pyrdacor** [comment]
@jr-riketz Should be fixed in 0.5.2beta which is available now. :)
