### ISSUE TITLE
Can´t say "Hallo" to grandfather

### ISSUE THREAD

**Issue by Searcher1978** [Pyrdacor/Ambermoon.net#74]
Hello,

i try the german version of 0.5.2. 

If i want to speak with the grandfather, the menu opens with the option "Hallo". But if i click on it, nothing happens.

If i try to type words like "hallo" manually, nothing happend too.

Thx for testing and thanks you try to progamm my most liked game on amiga for pc! :)

**Comment by Pyrdacor** [comment]
Hi. Yes conversations were only implemented rudimentary back then. The coming release will finalize them which includes fixing your mentioned stuff. So it's normal that conversations don't work at the moment. I'll take care of it the next days or weeks. ;-)

**Comment by Pyrdacor** [comment]
This is possible since 0.6.0beta.
