### ISSUE TITLE
Crash after reload

### ISSUE THREAD

**Issue by BigStephan1978** [Pyrdacor/Ambermoon.net#76]
Hi,

Saved the game (0.52 as well as 0.6)  and try to reload (continue) the game stops/closes without comment. Use the file with integrated net framework in win64.

**Comment by Pyrdacor** [comment]
Will have a look at it.

**Comment by Pyrdacor** [comment]
Hi, can you please test again with 0.6.1? Should load the corrupted savegame and if you save now should not produce corrupted saves anymore. The first time when loading you should see the message "Fixed corrupted savegame" in the console window. Then after saving and loading again this should be gone. Can you confirm?

**Comment by BigStephan1978** [comment]
Can confirm this. First load starts last savegame...then it crashed with the mentioned message (repair savegames). Then load again and it works.
