### ISSUE TITLE
Freeze after idle

### ISSUE THREAD

**Issue by BigStephan1978** [Pyrdacor/Ambermoon.net#77]
When i leave the game for a few minutes, the mouse cursor disappeares. Also keyboard inputs are not workin anymore. 
Mouse is working outside the gamewindow.
Have to close it over the windows taskmanager. No screensaver activated.

**Comment by Pyrdacor** [comment]
Does it happen everywhere and is it reproducable or just happened once? If you have a savegame where this happens, please upload it for me.

**Comment by BigStephan1978** [comment]
It happens after 1-2 minutes, doin nothing else on the pc. For now inside the starthouse and the first dungeon.

**Comment by Pyrdacor** [comment]
Hm I tried to reproduce it but with no luck. I fear this might be hardware related. Sometimes a driver (e.g. graphics) cause these problems.

Can you test with 0.6.2? I didn't change anything related to it but I fixed a lot of stuff and maybe your issue is gone now.

**Comment by BigStephan1978** [comment]
Ok....I now tried it again (on another computer) and no freeze (0.6.2).
So close this.
