### ISSUE TITLE
Re-entering vine-cellar not possible

### ISSUE THREAD

**Issue by BigStephan1978** [Pyrdacor/Ambermoon.net#79]
Sorry for another issue. When leaved the cellar of grandpa, i can't re-enter it. Its like running again a solid wall....

**Comment by Pyrdacor** [comment]
No need to apologize. Finding and reporting bugs is really important. At which exact spot is this "wall"?

I found and fixed some similar issues for the next release. Maybe it's fixed already but I will check your finding.

**Comment by BigStephan1978** [comment]
Don't know what you mean with spot...the entry to the cellar doesnt allow me to go through.

**Comment by BigStephan1978** [comment]
After reload the game i can go back to the cellar, but inside there, i can't move anymore...only turning myself is possible.

**Comment by Pyrdacor** [comment]
Ok I will check that on Tuesday.

**Comment by Pyrdacor** [comment]
I released 0.6.2 today. Maybe you can test it this still occurs.

**Comment by BigStephan1978** [comment]
It seems to work now...fine :-)
