### ISSUE TITLE
Wine Cellar: Word "Wein" ok, but the way isn´t free

### ISSUE THREAD

**Issue by Searcher1978** [Pyrdacor/Ambermoon.net#80]
When I'm in the wine cellar at the point where the moon face blocks the way, I can say WINE and the wall disappears. However, I cannot go any further, but hit the wall that is no longer there.

**Comment by Pyrdacor** [comment]
Thanks for reporting. I already fixed it. Comes with next week release.

**Comment by Searcher1978** [comment]
Thanks for your fast info. 👍
