### ISSUE TITLE
[Approach Suggestion] Custom icon

### ISSUE THREAD

**Issue by Wickez** [Pyrdacor/Ambermoon.net#84]
Like in the title. The default icon assigned by Windows is very boring and uninspiring. Also, I know a person who can create such an icon: me.

**Comment by Pyrdacor** [comment]
Hi I would like to do so. If you can create one this would be amazing. Can you provide it as *.ico and *.png?

**Comment by Wickez** [comment]
Great. I made two icons: "pixel perfect" style and "GOG" style. Each in .ICO and .PNG format. I uploaded the archive with them to [MEGA](https://mega.nz/file/U89CBT7I#Anx92qinNABTBwWvqVekVQV96lKFenNUszIUYkhmsqw).

If you have any ideas what you would like to see for an icon for Ambermoon.NET, then tell me, if neither of the above fits.

**Comment by Pyrdacor** [comment]
The GOG one looks awesome. I'll try to add it and see how it fits. ;) Thank you for your efforts!

**Comment by Pyrdacor** [comment]
The icon looks good as large icons but not as medium or small icon (in explorer). The window also uses the small icon version (I guess 16x16 pixels).

AFAIK icons can contain multiple sized versions. If a size is not available the window manager automatically shrinks it and I guess this messes up the icon. Maybe you could add the smaller version (16x16 and 32x32) manually?

**Comment by Pyrdacor** [comment]
![image](https://user-images.githubusercontent.com/8607784/122400417-fbf50d00-cf7b-11eb-91d9-86731cf05a02.png)

**Comment by Pyrdacor** [comment]
Ah and could you provide the PNG also as 16x16? Because I need the PNG for the window icon.

**Comment by Wickez** [comment]
Alright. I used an online converter instead of GIMP icon saving option and "baked in" several custom sizes into the .ICO file. Now it should look better. Also, included that 16x16 .PNG you wanted. All on [MEGA](https://mega.nz/file/RllxkQbK#LyyAPtU5YrFuVtetAx3pi2jlDTGuCX5vOkYe7FgIB4o) again.

**Comment by Pyrdacor** [comment]
The new 0.9.1beta release uses your icons. It's really cool and some people already said that they like it. Good work! Thanks you. :)

**Comment by Wickez** [comment]
No problem. If you would need more custom graphic work, just call me on Twitter via PM. Since this "issue" is over, I'm closing it.

**Comment by Pyrdacor** [comment]
@Wickez Could you please provide a 1024x1024 version of the icon as PNG. Someone wants to prepare a bundled version for Mac where you have to create a so called "icns" file. If you have a Mac and know this format you could also provide such an icns file but I have no clue about this Mac stuff. :D

**Comment by Wickez** [comment]
Now hold up. I can't reliably resize this to 1024, since I got it from Ambermoon's original cover (the biggest and most satisfying I could find), and no letter there was more than 150 pixels large in any direction. I cut and filtered the original icon via most solid image resizer, but beyond 256 pixels it's not going to look that nice. Effects below.

[MEGA](https://mega.nz/file/9h0m0IgB#yCVqrygS68EwkUZJLqAxVzm4q8eRbeOdXofQVGZ1K7E)

I produced three versions: no filtering, medium filtering, and maximum filtering. Finally, I have no idea on how to create Mac icons without accessibility to that system (and I didn't see anything on that in GIMP "knowledge library").

**Comment by a1exh** [comment]
All the pictures of Ambermoon you can find on Google are a photo of my box and contents I did for my site and HOL. If you need a higher resolution I could probably make one in a few days. But ultimately limited by the print quality.

**Comment by a1exh** [comment]
The box is in the attic and I just don't have the time to battle giant spiders right now. Sorry.

**Comment by Wickez** [comment]
Bro, it would take you less time to just do that than you spend on playing the game and reporting the bugs. Just muster the power and execute, please. Thanks, we knew you would do it for us!

**Comment by Pyrdacor** [comment]
Is this of any help? https://gitlab.com/ambermoon/research/-/blob/master/data/df/v101-1993-10-22-german/cover_front.jpg

**Comment by Wickez** [comment]
> 
> 
> Is this of any help? https://gitlab.com/ambermoon/research/-/blob/master/data/df/v101-1993-10-22-german/cover_front.jpg

So-so. It would really be easier if I would have it at least 4k in width, but I will try make it work with this.

**Comment by Wickez** [comment]
Alrighty. I believe this newest 1k outcome is pretty good, given the circumstances. Grab it on [MEGA](https://mega.nz/file/Iw1VVAxA#2wuRIIUjvyLnvHnviIFSOx3jEEPa_fvF9n9PEdT3CYY).

**Comment by Pyrdacor** [comment]
Great. It will be used for the Mac icons. Good job! Thank you.

**Comment by Pyrdacor** [comment]
The large icon is now used in the Mac release. Thanks again for the nice work @Wickez. ;)
