### ISSUE TITLE
GFX corruption Windows Stand Alone 64-bit Release 0.9.2

### ISSUE THREAD

**Issue by a1exh** [Pyrdacor/Ambermoon.net#87]
This is the first time I've tried Ambermoon.net on this Toshiba Tecra Laptop. It's OS is Windows 10 Pro 64-bit 20H2. 

The window that opens has lots of green lines across it and is unusable.

![Capture](https://user-images.githubusercontent.com/25319420/123982447-f3102c80-d9ba-11eb-9291-9201d8e17516.PNG)

I'll install .NET and try the non-stand-alone.

**Comment by a1exh** [comment]
If I edit the ambermoon.cfg and change "Fullscreen": false, to true it doesn't run and I get the following : 
>CursorMode.Disabled is not supported by SDL.
   at Silk.NET.Input.Sdl.SdlCursor.set_CursorMode(CursorMode value)
   at Ambermoon.GameWindow.SetupInput(IInputContext inputContext)
   at Ambermoon.GameWindow.Window_Load()
   at Silk.NET.Windowing.Internals.ViewImplementationBase.Initialize()
   at Silk.NET.Windowing.WindowExtensions.Run(IView view)
   at Ambermoon.GameWindow.Run(Configuration configuration)
   at Ambermoon.Program.Main()

This laptop does have 3 screens attached.

**Comment by a1exh** [comment]
The normal version does the same.

**Comment by a1exh** [comment]
You cannot click but you can move the mouse cursor around. It's incredibly slow to move.

**Comment by a1exh** [comment]
I tried 0.93 and some earlier releases and they do the same. Strange.

**Comment by Pyrdacor** [comment]
Hm I wonder why it uses SDL when switching to fullscreen. This should not happen and looks like a bug in Silk.NET which I use as a window backend.

I will investigate this.

**Comment by Pyrdacor** [comment]
The crash in fullscreen will be fixed in next release.

About the green lines. Is this maybe related to this? https://community.intel.com/t5/Graphics/Intel-HD-630-green-lines-in-OpenGL-apps/m-p/1192516

**Comment by a1exh** [comment]
Switching to the latest Intel 520 (release) driver for my Laptop fixes the green lines.
