### ISSUE TITLE
Crash: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by qwertz098** [Pyrdacor/Ambermoon.net#88]
Hi and thx for the great effort bringing that wonderful game back to modern computers.

Tried out V0.92 incl. the dll from #85 as standalone x64 on Win10. Just starting a new game and don't modify anything.

When entering the left chimney in GF house right after the start the crash mentioned above appears. No matter if german or english data set.

If there is an opportunity to get hand on any logs please describe and i provide.

**Comment by Pyrdacor** [comment]
Hi there. I fixed a lot already after 0.9.2. and I guess this crash as well. Will release another huge bugfix release soon. But thanks for reporting.

**Comment by Pyrdacor** [comment]
Please test with 0.9.3

**Comment by qwertz098** [comment]
Done, it's working!
