### ISSUE TITLE
Mouse / Keyboard input issues

### ISSUE THREAD

**Issue by a1exh** [Pyrdacor/Ambermoon.net#89]
The cursor is very sluggish and doesn't redraw very often. Left mouse click is very difficult to get detected. It requires you to click at a very fast rate to make a detection.

When clicking on the OK button sometimes the gfx show a depress but don't show the button coming back up.

At first I thought it might be the OpenGL requirements of Ambermoon.net are beyond those of my laptop's integrate Intel 520 chipset but the screen redraw seems fine, animation is fine, when I can get the mouse click to work the scrolling is fine. Music is playing happily in the background.

Just seems to be an issue with converting mouse inputs. I can't get keyboard inputs to work either.

**Comment by a1exh** [comment]
I wonder if you've implemented some sort of input filter and it's not working correctly for me?

**Comment by a1exh** [comment]
I downloaded glfw and put the files glfw3.dll and glfw3dll.lib in the same directory as Ambermoon.net.exe and the control issues are now gone.

**Comment by Pyrdacor** [comment]
Ok thanks but I will come back to you for testing SDL maybe. Some systems only have SDL. Please leave this open until we fix the SDL issues.

**Comment by Pyrdacor** [comment]
I talked to the Silk.NET maintainers. SDL is only meant for mobile support so it's best to use glfw when possible.

When I have the time I will try to girly SDL in Silk.NET as well.

**Comment by Pyrdacor** [comment]
As this is about SDL support and this is only relevant for mobile platforms and Silk.NET will remove SDL support eventually I close this now. Moreover the current version should now have builtin glfw support when possible.
