### ISSUE TITLE
Chest items not shown

### ISSUE THREAD

**Issue by Thallyrion** [Pyrdacor/Ambermoon.net#9]
I don't know how many chest are implemented. In 2D environment i wasn't able to open any. Only Moving Cursor and ZZZZ cursor is available. But in the 3D environemnt i could access some stashes. But no items are shown. 
![stash](https://user-images.githubusercontent.com/69513157/91635309-b28cfe80-e9f7-11ea-92fc-40df6648fba4.png)

**Comment by Pyrdacor** [comment]
Try to use keys 7, 8 and 9 on Numpad. They will give you cursors for eye, hand and mouth. Use the eye cursor on a chest or cupboard.

Items should be shown in 1.0.14. If not please tell me if for all chests ore only a few and which.

**Comment by Thallyrion** [comment]
Okay Keys work and chest show items. I think i know why some chests are empty. I made some test and am i correct that Ambermmoon.net loads the last used savegame? This would explain it as of course i have played furhter in the game so some chest are empty. But it doesn't show the portraits of other party members only the Main character is visible. And i once got this error after loading a savegame in Winuae and after that starting Ambermoon.net. 
![crash](https://user-images.githubusercontent.com/69513157/91635658-8161fd80-e9fa-11ea-8060-f8d590c20ed6.png)

**Comment by Pyrdacor** [comment]
Yeah it uses the savegame you provide. If there is no initial savegame (folder "Initial") it uses the normal files like Chest_data.amb etc in the main folder. The ADF disk files should have an initial savegame. Otherwise it uses the most recent played as you said.

About the portraits. It might be possible that only the first one is displayed but I will check if it a bug.

Will also look into the crash. 

Yes scrollbars are not implemented yet.

**Comment by Pyrdacor** [comment]
I guess the crash occurs if the latest savegame was on a 3D map. I think I fixed it (will come in next release) but maybe you can just test with your current game version if the crash happens when you saved on a 3D map.

**Comment by Thallyrion** [comment]
> I guess the crash occurs if the latest savegame was on a 3D map. I think I fixed it (will come in next release) but maybe you can just test with your current game version if the crash happens when you saved on a 3D map.

Yes this is the case. The crashing savegame was on a 3D map.

**Comment by Pyrdacor** [comment]
Tomorrow there will be an update with correctly loading all characters and their items and equipment. And also with working scrollbars etc. The crash will be gone then too.

**Comment by Pyrdacor** [comment]
Ok v1.0.15 should fix the crash and has a bunch of new things.
