### ISSUE TITLE
Crash at Start - Mouse-Problem with the first "OK"

### ISSUE THREAD

**Issue by Searcher1978** [Pyrdacor/Ambermoon.net#93]
Hi, 

after i start the 0.9.4 RC1 version i can´t click on "OK", because the mouse gets out of the window before i can click on "OK" (i want to choose the german version).

Then i edit the config on fullscreen "true", so i can choose german and can click on "OK". After that the program crashed. This screenshot is the short and last i´ve seen, before it crashes:

![0 9 4 RC1 - Absturz beim Start](https://user-images.githubusercontent.com/81861209/125134063-121f6480-e107-11eb-99b0-92a1690f1414.JPG)

**Comment by Pyrdacor** [comment]
Hi thanks for reporting. I will fix this asap. Can you test the following please:

Choose the English version, then change to windowed in the option menu (fullscreen of). Restart and try if you can now hit Ok in windowed mode.

**Comment by Pyrdacor** [comment]
I fixed the crash. Please download 0.9.4 again. German version should work now. I will take care of the mouse issue soon as well.

**Comment by Searcher1978** [comment]
Thx, the german version runs now :)
