### ISSUE TITLE
potion in battle

### ISSUE THREAD

**Issue by VhYXgWTzgD** [Pyrdacor/Ambermoon.net#94]
in 0.9.4 RC1 (Linux 64bit) i can use only one potion from a stack of potions. The second time i use a potion from the stack i get this error (in german): "Dieser Gegenstand hat keine magischen Ladungen mehr" meaning "no charges left on this item".

**Comment by Pyrdacor** [comment]
Thanks for reporting. Will have a look at it.

**Comment by Pyrdacor** [comment]
Should be fixed in test release. Please test with this version: https://github.com/Pyrdacor/Ambermoon.net/releases/tag/TestRelease
