### ISSUE TITLE
Resting not working

### ISSUE THREAD

**Issue by Shinhobi** [Pyrdacor/Ambermoon.net#96]
#Resting in the tavern or the healer center in Spanberg is not possible:

Object reference not set to an instance of an object.

This is on the Test Version.

Good to see you are progressing well however!

**Comment by Pyrdacor** [comment]
Is fixed in test release now: https://github.com/Pyrdacor/Ambermoon.net/releases/tag/TestRelease

**Comment by Shinhobi** [comment]
looks fixed, yes.
