### ISSUE TITLE
smaller radius of Zzzz in 2d mode

### ISSUE THREAD

**Issue by Shinhobi** [Pyrdacor/Ambermoon.net#98]
when moving around in with the mouse in 2d mode one has to make a wide radius around the player sprite to move it. if you are too close the waiting symbol shows up (Zzz). In the original game this radius was smaller and it made it easier to move around in 2d.

**Comment by Pyrdacor** [comment]
I improved this in the test release just now: https://github.com/Pyrdacor/Ambermoon.net/releases/tag/TestRelease

**Comment by Shinhobi** [comment]
Hey. works! much better.
