### ISSUE TITLE
mouse in mac full screen mode relase not working

### ISSUE THREAD

**Issue by Shinhobi** [Pyrdacor/Ambermoon.net#99]
in the bundled standalone release for mac the mouse stops workign properly when in full screen mode. it seems to move in a smaller frame than the game window bein locked in the upper left part. it makes it impossible to play the game. also I found no way to leave full screen mode again - even when re-installing the package even in another version.

**Comment by Pyrdacor** [comment]
Ok I will have a look. You can toggle fullscreen with F11 (I guess on Mac F11 is some kind of key combination). You can also toggle fullscreen in the ingame option menu if you can reach it.

**Comment by Pyrdacor** [comment]
Please test again with this version: https://github.com/Pyrdacor/Ambermoon.net/releases/tag/TestRelease

I updated the test release.

**Comment by Shinhobi** [comment]
still does not work and no, cannot get anywhere as this problem occurs from the beginning on

**Comment by Pyrdacor** [comment]
Which desktop resolution do you use and is this a high DPI monitor?

**Comment by Shinhobi** [comment]
It's a macbook pro with a retina display 2880 × 1800. changing the
resolution does not solve the problem however.

**Comment by Pyrdacor** [comment]
Does it work correctly in window mode?

**Comment by Shinhobi** [comment]
seemed to be working correctly. but once I switched to full screen i was
inable to switch back

**Comment by Pyrdacor** [comment]
You can change to window mode by editing the ambermoon.cfg file and set fullscreen to false.

**Comment by Pyrdacor** [comment]
Can you please test again with the current Test Release?

**Comment by Shinhobi** [comment]
downloaded, tested, failed again. check the picture to see how far down and right the mouse pointer wants to go. maybe someone else should test on mac. maybe I am missing something obvious, but I cannot get it to run. it seems like once I changed to full screen it locked itself in a smaller window that does not equal the size of the actual displayed ambermoon interface. no re-installing seems to change it, whatever version. 

<img width="1440" alt="Bildschirmfoto 2021-07-19 um 20 42 21" src="https://user-images.githubusercontent.com/77516575/126210594-e3e0917f-91bb-4a50-a5f9-a68278c1059c.png">

**Comment by Shinhobi** [comment]
okay. I went into the config file and set full screen to 'fals' this solved it. I was able to play ambermoon on my macbook pro. 

however (and sorry to say) i ran straight into the next problem. as soon as I choose one of the pointer options (like mouth for talking or the hand to manipulate something) or I go into the party battle stance selection, the mouse movement slows down to such a low speed that I can hardly get anything done (takes like several repetitive mouse movements into one direction to make the cursor go anywhere. 

<img width="1065" alt="Bildschirmfoto 2021-07-19 um 20 48 00" src="https://user-images.githubusercontent.com/77516575/126211632-30f0c34f-943c-4a3e-b5ff-d95cc2900487.png">

**Comment by Shinhobi** [comment]
by the way. as soon as I go in-game and choose the full-screen option it WORKS in full-screen. However. If I save, quit and restart the game I get the same original issue: the mouse pointer seems stuck again in its own window or resolution and I cannot reach the whole interface.

**Comment by Pyrdacor** [comment]
Ok thanks for your testing. Can you try to download glfw for Mac and put it next to Ambermoon? The slow mouse movement was observed before when no glfw was available.

**Comment by Pyrdacor** [comment]
> downloaded, tested, failed again. check the picture to see how far down and right the mouse pointer wants to go. maybe someone else should test on mac. maybe I am missing something obvious, but I cannot get it to run. it seems like once I changed to full screen it locked itself in a smaller window that does not equal the size of the actual displayed ambermoon interface. no re-installing seems to change it, whatever version.

Another Mac user has exactly the same problem. Seems like a "fullscreen on startup" issue. I will have a look at it.

You can just use Fn+Alt+F11 to switch to window and again to switch back to fullscreen. This way you can always play in fill

**Comment by Pyrdacor** [comment]
Can you please test with the most recent TestRelease if it still happens?

**Comment by Shinhobi** [comment]
shall do when i find time

Pyrdacor ***@***.***> schrieb am Mi., 21. Juli 2021, 12:50:

**Comment by Shinhobi** [comment]
Hey!

All works now. I download, install, it's straight in fullscreen mode works
flawlessly and also the mouse pointer doesnt slow down anymore weirdly.
Also, the 3D movement is now varying in movement speed depending on how far
the mouse is from the center.

congrats.

**Comment by Pyrdacor** [comment]
Yeah I did a lot improving today and added much cool stuff. ;) I'm glad everything works now.
